### ISSUE TITLE
Deletion of embedded code nodes on backspace after focusing empty node

### ISSUE THREAD

**Issue by mk** [ProseMirror/prosemirror#1000]
### Issue details

When giving focus from an embedded code editor to an empty paragraph following this editor using the mouse and then pressing backspace, the code editor gets removed. 

When there is more than one code editor above the empty paragraph, they also gets removed (see screencast below)

In the case that the following paragraph isn't empty, the cursor moves correctly into the code editor on backspace.

### Steps to reproduce

1. Go to https://prosemirror.net/examples/codemirror/
2. change the paragraph following the code cell to be empty
3. click into the code editor
4. click into the paragraph
5. hit backspace

### ProseMirror version
prosemirror-view 1.13.2

### Affected platforms

At least Chrome and Safari are affected

### Screenshots / Screencast (Optional)

![Kapture 2019-11-15 at 15 03 16](https://user-images.githubusercontent.com/1187/68948854-1c198480-07b9-11ea-850e-f2d29fcf4a9e.gif)

**Comment by jljorgenson18** [comment]
This looks expected. Prosemirror is not opinionated when it comes to this type of functionality and it's been typically up to the implementor to do custom backspace handling.

To create this functionality, you would have to create a plugin that implements `handleKeyDown` for backspace. Then in the backspace handler, you check if the position is right after the codeblock, move the selection at the end of the codeblock, and then return `true` to say that the backspace is handled to prevent the default deletion.

**Comment by kommen** [comment]
@jljorgenson18 for me this is very unexpected, since the backspace behavior shown above is different if one navigates out of the code editor with the arrow keys: using the Arrow Down key to move the cursor (instead of clicking), then pressing backspace results in the cursor just being moved into the code editor and nothing is deleted.

**Comment by jljorgenson18** [comment]
It is unexpected for an actual editor inside of an application, but it is expected for prosemirror out of the box. It's up to the implementor to decide what happens if you press backspace in front of a codeblock. The default behavior on a contenteditable based editor is that the block is deleted when you hit delete or backspace.

For example, our editor has a special node attribute called "selectOnDelete" that prevents the default backspace handling in front of certain block nodes and just selects the entire node. If we didn't include that attribute on a node, then that node would be deleted by a backspace.

**Comment by mk** [comment]
@jljorgenson18 did you see that it also deletes multiple code nodes with just one press of backspace? It seems to me that there's an issue with detecting where the selection should be in this case.

**Comment by jljorgenson18** [comment]
O crap I did not. My apologies, it visually looked like a single codeblock.

**Comment by marijnh** [comment]
This was a bug in selection management—the editor still had the old selection, pointing into the editor, and failed to update when the cursor was moved into the empty paragraph. Attached patch fixes this.
