### ISSUE TITLE
Cursor is in really weird places...

### ISSUE THREAD

**Issue by slava-vishnyakov** [ProseMirror/prosemirror#1002]
### Issue details

The cursor is not where it appears to be, when editing "code" elements and often you can't even get where you need to be. The `code` element has `padding` and `background` to make it visually nicer. That's about it.

![](https://user-images.githubusercontent.com/817931/68966832-10958000-07f0-11ea-8234-43270aa58967.gif)

![image](https://user-images.githubusercontent.com/817931/68967068-7c77e880-07f0-11ea-94c4-722a9b344230.png)

Here's the version that you can rewind: https://imgur.com/a/8oQ7AbC

### Steps to reproduce

https://glitch.com/edit/#!/bottlenose-part

### ProseMirror version

Probably, latest? It's a clone of the demo.

### Affected platforms

- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Other

### Screenshots / Screencast (Optional)

The video is here:
https://imgur.com/a/8oQ7AbC

**Comment by marijnh** [comment]
Do I summarize this correctly as:

 - ProseMirror will, when text is inserted before a code mark, not apply the mark to the new text (by design)

 - Chrome will, when the code mark is styled with a horizontal padding, render the cursor after the padding

 - This looks weird

As far as ProseMirror is concerned, there are no two cursor positions (before and inside the mark), there's is just 'the position at the start of the mark'. Browsers mostly work the same way (except for Firefox, in _some_ situations) they treat a selection position inside and outside an inline element as the same, and will insert content in the same way for both. So I don't think there's a lot we can do about this.

**Comment by slava-vishnyakov** [comment]
Well, the problem with 1st point is that I'm specifically clicking INSIDE of the code block, to add the text there, but it adds outside. But the more I dig into it - the more it seems like it's a browser issue, not ProseMirror's. 

Thank you for looking into it.
