### ISSUE TITLE
Cannot remove a heading node when the node is at the beginning of the document

### ISSUE THREAD

**Issue by pocke** [ProseMirror/prosemirror#1018]
### Issue details

We cannot remove a heading node when the node is at the beginning of the document even if `baseKeymap` is available.

So we add the following keybind to our application to remove the heading node by backspace key.

```javascript
const removeHeadingAtFirst = (headingType) => {
  return (state, dispatch, _view) => {
    const { $cursor } = state.selection;
    if (!$cursor) {
      // $cursor is only available for TextSelection
      return false;
    }

    const node = $cursor.parent;
    if (node.type !== headingType) {
      return false;
    }
    if (node.textContent !== "") {
      return false;
    }

    if (dispatch) {
      dispatch(state.tr.deleteRange($cursor.before(), $cursor.after()));
    }
    return true;
  };
};
```

But I guess it will be better if the behavior is the default.

### Steps to reproduce

https://glitch.com/~spangle-dress

### ProseMirror version

We use prosemirror-commands v1.1.2 for the baseKeymap.

### Affected platforms

I've confirmed this problem on the checked browsers, but I guess it does not depend on the browser.

- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer
- [ ] Other

### Screenshots / Screencast (Optional)

![Peek 2019-12-25 16-11](https://user-images.githubusercontent.com/4361134/71436541-456eee00-2731-11ea-9492-52fc29e9fab0.gif)

**Comment by marijnh** [comment]
Since typical schemas require at least _something_ to be in the document (the effect of your command is to replace the heading with a paragraph, which is automatically inserted to satisfy the schema constraints). So the way to change the type of the single last textblock in a document is with `setBlockType` commands. I don't see 'resetting the block type to the default block' as obviously something that backspace should do, so I'm not convinced the behavior proposed here should be the default.

**Comment by charescape** [comment]
@marijnh It might be a good strategy to add a configuration option and let the user decide whether to enable it by default.

**Comment by marijnh** [comment]
Keyboard behavior is configurable by adding key bindings. The behavior requested here is non-trivial and schema-specific, so I don't think it makes much sense to implement it in the core library.
