### ISSUE TITLE
handleClickOn is not correctly fired in IE 11

### ISSUE THREAD

**Issue by TheRealNic** [ProseMirror/prosemirror#1021]
### Issue details

In IE11 the handleClickOn handler is not always correctly fired.

### Steps to reproduce

1. Open repository https://github.com/mediatis/pm975-repro on branch handleClickOn-in-IE11 (https://github.com/mediatis/pm975-repro/tree/handleClickOn-in-IE11)
2. Move the cursor just underneath the placeholder 
3. click the mouse

Expected: The cursor is set into the placeholder and the handleClickOn of the placeholder Handler is fired (console shows handleClickOn).
Actual: The cursor is set, but the handler is not fired.

### Affected platforms

- [ ] Chrome
- [ ] Firefox
- [x] Internet Explorer
- [ ] Other

### Screenshots / Screencast (Optional)

![handleClickOn](https://user-images.githubusercontent.com/8322279/72348834-8e381800-36db-11ea-80a9-ce5896e71534.gif)

**Comment by TheRealNic** [comment]
I already tried to find the bug in prosemirror and debugged my way to the domcords.js file in prosemirror-view. In the method posAtCoords you try to get the descendant by calling `view.docView.nearestDesc(elt, true)` (line 226) and to me it looks like this is not finding the descendant...

**Comment by marijnh** [comment]
The problem with your demo appears to be that its bundling mechanism doesn't wrap modules in any kind of scope, dumping everything into the global scope. That's likely to cause problems. One immediately visible issue appears to be that IE is calling ProseMirror's internal `dispatchEvent` to dispatch events. It also appears to be the cause of the `handleClickOn` issue—if I wrap `bundle.js` in a function and call it, I do get the `console.log` output.

**Comment by cmlenz** [comment]
Hey @marijnh. Thanks for looking into this.

Looking at our bundle, I don't see it dumping everything into the global scope, only a few things like `OrderedMap`, `RopeSequence`, and `w3cKeyname`.

Logging the global `dispatchEvent` in Chrome says it's `dispatchEvent()  { [native code] }`.

We used Rollup in this repro because it's more prevalent in the ProseMirror environment. For our actual code we are using Webpack, and the click behavior in IE11 is the same as with the Rollup bundle.

**Comment by marijnh** [comment]
> Looking at our bundle, I don't see it dumping everything into the global scope

I do. After I build the branch you pointed me at, dist/bundle.js has all of ProseMirror on the top level of the file.

**Comment by cmlenz** [comment]
> I do. After I build the branch you pointed me at, dist/bundle.js has all of ProseMirror on the top level of the file.

Are you sure? I thought so too at first, but in reality the vast majority of code, including `dispatchEvent` is declared inside `createCommonjsModule(function (module, exports) {}` functions.

**Comment by marijnh** [comment]
Yes, I am sure—after OrderedMap, the whole of `prosemirror-model` is inlined. I didn't check beyond that. There are uses of `createCommonjsModule`, but a lot of code isn't in them.

**Comment by cmlenz** [comment]
Okay, I see that too when updating package.json to reference the latest version of Rollup. Still I think it's not the cause of this issue here. We'll update the repro to do the bundling differently.

**Comment by cmlenz** [comment]
> We'll update the repro to do the bundling differently.

Actually @TheRealNic has already done that on his branch. Please run `npm run build-webpack` to get a better bundle.

**Comment by marijnh** [comment]
When I do that I see the same thing that I saw when I manually wrapped the bundle in an iffe, the handleClickOn works and the console.log appears in the dev tools.

**Comment by TheRealNic** [comment]
I've updated the prosemirror dependencies, but I can still reproduce this behaviour. It is important, where I click though, so I get the cursor set without seeing the console message, if the cursor is around 30% over the placeholder and 70% over the area under the placeholder. Should I create another gif/video to maybe show the cursor placement?

**Comment by cmlenz** [comment]
Let me explain what we're trying to achieve here:

The placeholder is a span of text that the user should replace with their own content. So if the user clicks on it, we want the whole placeholder to be selected, instead of the default behavior of the selection being set to the insertion point. Then the user can start typing and would replace the whole thing, and not just type somewhere inside the placeholder.

That doesn't work as nicely as we hoped in IE11 because if the user clicks *on the edge* of the placeholder (as @TheRealNic described), the `handleClickOn` method is not called, but IE still puts the selection at the clicked point. So when the user starts typing, they actually insert characters in the middle of the placeholder, instead of replacing the whole thing as they have come to expect.

Maybe there's a better way to achieve what we're trying to do. Open to suggestions!

**Comment by marijnh** [comment]
So is the issue that the handler isn't called when you click between the paragraphs, even though that does move the cursor? That's the expected behavior for `handleClickOn`—that only notifies you of clicks that actually touch the DOM node for a given document node. It behaves the same in other browsers. If you're interested in the cursor ending up in a given position, just observe the editor state, not the clicks.

(It'd have saved us both a lot of time if you'd have explained the issue properly in the initial report, _and_ made sure the demo actually worked.)

**Comment by cmlenz** [comment]
Okay, we will try the suggested approach. Sorry for the confusion. This issue can be closed, I guess.
