### ISSUE TITLE
img followed by emoji and use Chinese input method

### ISSUE THREAD

**Issue by wangxg6** [ProseMirror/prosemirror#1039]
### Issue details

img followed by emoji and use Chinese input method, I can not input chinese, and emoji would be deleted
it can be reproduced on the demo https://prosemirror.net/

### Steps to reproduce
 * insert img
 * input any emoji
 * use Chinese input method input Chinese

### ProseMirror version

        "prosemirror-commands": "^1.0.7",
        "prosemirror-dropcursor": "^1.1.2",
        "prosemirror-keymap": "^1.0.1",
        "prosemirror-model": "^1.7.2",
        "prosemirror-state": "^1.2.2",
        "prosemirror-view": "^1.11.1",

**Comment by marijnh** [comment]
I'm not able to reproduce this, but that's not too surprising since you didn't mention which browser you're using, or which platform and IME system, or which Emoji was involved. Some more information would be helpful.

**Comment by wangxg6** [comment]
😊😊😊😊😊😊  behind any image
When I input Chinese  （use Mac Chinese input method ） between emoji would be deleted，and Chinese can not be typed
I use Chrome 80.0.3987.163 with MacOs 10.14.6
just on the demo https://prosemirror.net/

**Comment by marijnh** [comment]
Strange, this doesn't happen for me, at least not as clearly as you indicated. I did get some odd behavior, in very specific circumstances, but I'm seeing those in a plain contenteditable element (with no ProseMirror code connected) as well. For example, if you have a paragraph containing

     Test <img src="img.png">😊坲佛坲佛坲foo

If I put my cursor before "foo", press f, and select the second option (using macOS's Pinyin input), it doesn't insert a new character but moves the cursor over the `f` in "foo" instead. If the paragraph is slightly different (no leading text or no image), it inserts a character as expected, so that does look like a bug in Apple's IME.

But it doesn't really sound like what you're describing. Maybe be even more specific—there's a whole bunch of Chinese IME methods in macOS, and you didn't specify which one you're using. Nor which keys you are pressing when the problem occurs.

**Comment by wangxg6** [comment]
you will insert a real picture and insert Chinese between emoji
just like
<p>
<img src="https://timgsa.baidu.com/timg?image&amp;quality=80&amp;size=b9999_10000&amp;sec=1588765672916&amp;di=6aff96859b7eff4ceca85ae00453fc6f&amp;imgtype=0&amp;src=http%3A%2F%2Fimgsrc.baidu.com%2Fforum%2Fw%3D580%2Fsign%3D976d3e62e1fe9925cb0c695804a95ee4%2Fcec1913df8dcd10017e5de86738b4710b9122f26.jpg" alt="" title="" contenteditable="false" draggable="true">😊😊😊😊😊😊😊😊😊😊😊坲坲坲😊😊😊😊😊
</p>

and when you insert fo by Chinese input method emoji will be deleted and can not insert Chinese

**Comment by marijnh** [comment]
- _Which_ Chinese input method are you using precisely

 - How are you picking a character after typing 'fo'

**Comment by wangxg6** [comment]
I just use Mac Chinese input Method Pinyin-Simplified
![image](https://user-images.githubusercontent.com/17082969/81267349-e58e3980-9078-11ea-9d45-399ffeeab6f7.png)

step1:
![image](https://user-images.githubusercontent.com/17082969/81267712-79f89c00-9079-11ea-841a-8d9127f713b4.png)

**Comment by marijnh** [comment]
So you type "fofofofofo" and then press space, right? I do see the input vanishing, but here too, a plain contenteditable div shows the same issue, so the bug is probably not ProseMirror-related.

**Comment by wangxg6** [comment]
but image with emoji and type Chinese can reproduce the problem
only emoji，type Chinese works good

**Comment by marijnh** [comment]
That's true, but I don't see how that affects my conclusion.
