### ISSUE TITLE
Selection not restored when switching between two editors

### ISSUE THREAD

**Issue by gambolputty** [ProseMirror/prosemirror#1055]
### Issue details

Hello!

I have two ProseMirror editors and would like to switch between them by keyboard navigation via TAB and SHIFT+TAB. But doing so resets the selection each time one editor is focused. 

For example, I have two editors (editor-1 and editor-2):
1. My cursor is at position **26** in editor-2
2. I'm switching to editor-1 via SHIFT-TAB
3. I navigate back to editor-2
4. The selection is reset to the start of the editor (but was expected at position **26**)

This only happens if I switch _between_ two editors. If I navigate even further, let's say to the browsers address bar, and go back to one of the editors, the selection is successfully restored. 

### Steps to reproduce

I cloned the basic ProseMirror example and created two editors to demonstrate this behavior here: https://glitch.com/~jolly-foremost-land

### ProseMirror version

latest (the one in the example)

### Affected platforms

Tested this in Chrome (latest) on Windows 10 and Mac (latest)

**Comment by marijnh** [comment]
> The selection is reset to the start of the editor (but was expected at position 26)

This is what the browser does when you focus an input field with tab—it puts the DOM selection at its start. Since ProseMirror syncs its internal view of the selection with the browser selection, that'll also move the editor selection.

As such, this is the expected behavior. There doesn't seem to be an easy way to work around it—you can call `EditorView.focus` on the `"focus"` event, and that'll do what you want here, but that'll mess with focusing by mouse (in which case you don't want this to happen, since it'll interfere with the new selection set by the mouse), so more scary kludges would be needed.

**Comment by gambolputty** [comment]
Hey, thanks for explaining this to me. I'm glad this is cleared up.
My use case is a text editor with multiple tabs/editors and switching between them should restore the selections. But because I'm storing the selections anyway when blurring the editor (like VSCode does when you close a tab) somewhere else, I can catch the TAB and SHIFT-TAB keys programmatically and restore the selection I saved (from the Vuex store).
Again, thanks for clearing this up! I'm so grateful this projects exists. Have a good day!
