### ISSUE TITLE
`coordsAtPos` returns incorrect coordinates

### ISSUE THREAD

**Issue by kuiro5** [ProseMirror/prosemirror#1096]
### Issue details
Hi, I'm running into a minor issue with `coordsAtPos`, hoping you could help.

When selecting text at the beginning of a line and that line also begins with a decoration, the `coordsAtPos` value is incorrect (it appears to be returning the value for the previous line).

This does not happen if the line does not begin with a decoration or if your selection starts with anything other than the first character in the line.

I've upgraded to the latest version of `prosemirror-view` and have reproduced it across browsers. I've attached a gif of the issue, let me know if there's any other additional information that I can provide.

### Steps to reproduce
* Add a decoration to the beginning of a line
* Select the text starting at the very beginning of the line
* Observe the `coordsAtPos` `left`/`right` value 

### ProseMirror version

    "prosemirror-commands": "^1.1.4",
    "prosemirror-history": "^1.1.3",
    "prosemirror-inputrules": "^1.1.2",
    "prosemirror-keymap": "^1.1.4",
    "prosemirror-menu": "^1.1.4",
    "prosemirror-schema-basic": "^1.1.2",
    "prosemirror-schema-list": "^1.1.2",
    "prosemirror-state": "^1.3.3",
    "prosemirror-view": "^1.15.7",

### Affected platforms

- [X] Chrome 85.0.4183.121
- [X] Firefox
- [X] Internet Explorer
- [ ] Other

### Screenshots / Screencast (Optional)
![out](https://user-images.githubusercontent.com/4662473/94751916-a1107c80-033e-11eb-8673-84682cfd3b98.gif)

**Comment by marijnh** [comment]
This is caused by an unresolved ambiguity in the way `coordsAtPos` was designed—a position does not actually unambiguously specify a position, if the objects before and after it aren't directly adjacent.

Patch 250d4337216b5c24cc adds an argument to `coordsAtPos` that allows the caller to specify which position they are interested in, and tightens up the code to actually respect that, and not return whichever side is more convenient.

**Comment by kuiro5** [comment]
Thanks @marijnh, appreciate the response!
