### ISSUE TITLE
Inconsistent behaviour in Chrome based on presence of "href" attribute

### ISSUE THREAD

**Issue by rudolfbyker** [ProseMirror/prosemirror#1100]
### Steps to reproduce

1. Open this example
    - https://glitch.com/edit/#!/juniper-lyrical-fontina
    - https://juniper-lyrical-fontina.glitch.me/
2. Place the cursor after the word "llama".
3. Type any text, e.g. `!`.
4. Expected behaviour: The text should either be inside or outside the llama node. Not sure which is best, but it should be consistent. My preference would be how it behaves on Firefox, where it depends on whether the cursor is inside or outside the node, which again depends on from which side you navigated towards that position. My use case is that I want to allow the user to append text inside an inline node.
5. Actual behaviour:

The actual behaviour depends on the type of tag used (to test it yourself, modify lines 14 and 19 of `index.js` and line 13 of `index.html`) and whether the `href` attribute is added in the `toDOM` function (comment out line 21 of `index.js`).

...                   | Firefox | Chrome
------------------|-----------|-------------
`a` with `href` | `<a href="http://example.com">I am a llama!</a>` |   **`<a href="http://example.com">I am a llama</a>!`**
`a` without `href` | `<a>I am a llama!</a>` |   `<a>I am a llama!</a>`
`span` with `href` | `<span href="http://example.com">I am a llama!</a>` |   `<span href="http://example.com">I am a llama!</a>`
`span` without `href` | `<span>I am a llama!</a>` |   `<span>I am a llama!</a>`

Notes:
- I omitted `style` attributes for brevity.
- I know `span` with `href` is nonsensical. It's just for argument's sake.

### ProseMirror version

Whatever version is hosted at https://prosemirror.net/examples/prosemirror.js

### Affected platforms

- [x] Chrome
- [x] Firefox

Did not test on IE, because I'm on Linux.

**Comment by marijnh** [comment]
This is a known and intentional limitation of the library—browsers don't provide control over this, and there's no one-size-fits-all way to fix it in the library. See [this thread](https://discuss.prosemirror.net/t/discussion-inline-nodes-with-content/496) for background. You'll need to do your own handling of cursor motion and editing around the inline node type if you want this kind of structure and consistent behavior.

**Comment by rudolfbyker** [comment]
That makes sense. Thanks for the pointer! Hopefully I can figure out how to implement my own handling of the cursor. All I need is for that specific node type to always be "sticky" at the end (the front does not matter).

**Comment by marijnh** [comment]
(Using marks instead of nodes for links is going to be a lot easier, if you don't have a pressing reason you need a node.)

**Comment by rudolfbyker** [comment]
I was afraid you were going to say that. I first developed it using marks,
based on the Link mark that comes with tiptap, but running plugins with
popups that activate when the cursor is on a the mark, and getting the text
from the mark, etc. was becoming quite a mess, and I could do everything
with much less code after I changed it to node. But maybe I'm missing
something.

**Comment by tbroyer** [comment]
Fwiw, implementing links as marks is full of issues.
For example, go to https://tiptap.dev/links, select "the world" (or even just "world") and click on the "update link" button that appears and change the link (say, to https://prosemirror.net :wink:), now select "wide" and click "update link": the original URL appears, because your first action actually split the mark in two.
This could possibly be solved, but now instead of "update link", hit Ctrl+I to make the selection italic; this will split things into smaller text nodes, and will split the linked text too.
This means that to actually update the URL for the whole link, you need to chase all adjacent text nodes with the same link mark and change them all.
When transforming to other formats (such as HTML), you also need to take that into account, rather than transforming nodes to other nodes (unless you're OK with several adjacent links rather than a single one enclosing all the marked-up text: bold, italic, etc.)

FYI, my problem with an inline node (which otherwise works rather well) is with marks: when making text bold or italic around the start of the inline node (in the tictac example above, selecting "the world" and making it italic), the inline node itself gets the mark (in addition to the inner text), which visually makes the whole link italic!
Should I file a new issue about that?

**Comment by rudolfbyker** [comment]
The issues described by @tbroyer are among the reasons why I chose to implement links as nodes rather than marks.

@marijnh Would you be so kind as to point me to some example code or documentation on "own handling of cursor motion and editing around the inline node type" ?
