### ISSUE TITLE
Duplicated first letter with IME input after selecting multiple lines

### ISSUE THREAD

**Issue by orange030** [ProseMirror/prosemirror#1132]
### Issue details
The first letter of your input will be duplicated when you input Chinese to replace selection in multiple lines
It happen in Chrome with macOS

![prosemirror-ime-bug](https://user-images.githubusercontent.com/475560/107130635-7943ad80-690a-11eb-9626-7a621dffe75f.gif)

### Steps to reproduce
1. Open the homepage https://prosemirror.net/
2. Enable a Chinese IME.
3. Select two lines in text editor.
4. Type zheli with Chinese IME.

You will get "zh" after you type the "h" letter. The "z" which you first input will be out of input bound

### ProseMirror version

    "prosemirror-commands": "^1.1.4",
    "prosemirror-example-setup": "^1.1.2",
    "prosemirror-gapcursor": "^1.1.5",
    "prosemirror-markdown": "^1.5.1",
    "prosemirror-menu": "^1.1.4",
    "prosemirror-schema-basic": "^1.1.2",
    "prosemirror-schema-list": "^1.1.4",
    "prosemirror-state": "^1.3.3",
    "prosemirror-tables": "^1.1.1",
    "prosemirror-utils": "^0.9.6",
    "prosemirror-view": "^1.17.5"
### Affected platforms

- [X] macOS
- [X] Chrome 88.0.4324.146

**Comment by marijnh** [comment]
Are you absolutely sure you're testing with prosemirror-view 1.17.5, not 1.17.4? The previous version had a problem very much like this, but I can't reproduce it on Chrome Linux anymore. (Of course, that could be because Linux IME works differently, so if this does still occur, let me know and I'll go find a Mac.)

**Comment by yunwuxin** [comment]
It also happen in Windows .

**Comment by xiaody** [comment]
I can reproduce this on both https://prosemirror.net/ and my project (prosemirror-view 1.18.4).

Chrome 90.0.4430.93
macOS Big Sur 11.3.1 built-in Chinese input method (简体拼音).

**Comment by ocavue** [comment]
I can reproduce this issue on my Mac not only with CJK IME but also when I want to type letters with accents (for example, `Option + u + i` for `ï`). 

I record a video to show the expected behavior from Microsoft Word and Apple Notes compare to the ProseMirror behavior.


https://user-images.githubusercontent.com/24715727/126538924-de0b052e-7e00-40fc-8322-c2db135f8cb3.mov

**Comment by marijnh** [comment]
Indeed, I was able to reproduce this on desktop browsers, which made it a lot easier to diagnose. Attached patch should help.
