### ISSUE TITLE
The selected text will disappear after lose focus when select multiple lines in iOS

### ISSUE THREAD

**Issue by orange030** [ProseMirror/prosemirror#1135]
### Issue details

The selected text will disappear after lost focus when select multiple lines in iOS

### Steps to reproduce

1. Open the homepage https://prosemirror.net/
2. Create three lines text.
3. Select three lines in text editor.
4. Tap address bar.

https://user-images.githubusercontent.com/475560/108607456-8a58e800-73fb-11eb-9027-ff51429b5431.mov

https://user-images.githubusercontent.com/475560/108608017-f2f59400-73fe-11eb-87e2-b13a4f5aa2a6.mov

### ProseMirror version

    "prosemirror-commands": "^1.1.4",
    "prosemirror-example-setup": "^1.1.2",
    "prosemirror-gapcursor": "^1.1.5",
    "prosemirror-markdown": "^1.5.1",
    "prosemirror-menu": "^1.1.4",
    "prosemirror-schema-basic": "^1.1.2",
    "prosemirror-schema-list": "^1.1.4",
    "prosemirror-state": "^1.3.3",
    "prosemirror-tables": "^1.1.1",
    "prosemirror-utils": "^0.9.6",
    "prosemirror-view": "^1.17.6"
### Affected platforms

- [X] iOS 14.2
- [X] iOS 14.4
- [X] Safari

**Comment by marijnh** [comment]
I can't reproduce this in iOS 14.4 (or desktop Safari, if that's what was meant by the "Safari" checkbox). Not sure what the relevant difference between our setups might be.

**Comment by orange030** [comment]
It happens only in iOS. Maybe it's difference in input method. Everything work fine when you select text and your IME is not Chinese state. Please switch the IME to Chinese state, then **refresh** the page, repeat the above steps again . It will reproduce

**Comment by marijnh** [comment]
Hm, still no success reproducing this. When you're in the URL bar, you press 'Cancel' to get out again?

**Comment by jljorgenson18** [comment]
We are seeing a similar issue. A few notes

* It seems to only happen on Chinese Simplified, not Chinese traditional
* I believe this only happens on device
* I believe we could repro this on both iOS 13 and 14
* We could more easily repro this when you are inside of a table

**Comment by orange030** [comment]
Sometime it needs input some character with IME first

### Steps to reproduce

1. Switch the IME to Chinese Simplified. 
2. Open the homepage https://prosemirror.net/
3. Create three lines text with linebreak
4. Input a Chinese character with IME. For example "ha"  "哈"
5. Select three lines in text editor.
6. Tap address bar, or switch to other app . Anything to make it loses focus is ok

I find 'compositionend' event will be trigger before editor loses focus when the bug happens

**Comment by orange030** [comment]
I find it happened in any contenteditable in iOS safari , not only prosemirror.
I don't know how to deal with this kind of problem

**Comment by orange030** [comment]
I find a simple solution

``` typescript

import {Plugin} from "prosemirror-state"

export function iosDeleteCompositionTextCheck(){

  return new Plugin({
      props: {
      handleDOMEvents:{
        beforeinput(view, event){
          if(event.inputType ==  "deleteCompositionText"){
            let selection = view.state.selection
            if(!selection.empty){
              // Disable contentEditable to prevent selection deleted when error deleteCompositionText event triggered
              (view.dom as HTMLDivElement).contentEditable = 'false'
              return true
            }
          }
          return false 
        },
        compositionend(view, event){
          if((view.dom as HTMLDivElement).contentEditable != 'true' ){
            // Recover contentEditable
            (view.dom as HTMLDivElement).contentEditable = 'true'
          }
          return false 
        }
      }
    }
  })
}

```

Set contentEditable to "false" when the error happens, then recover it later

**Comment by jljorgenson18** [comment]
@orange030 We were able to resolve this by filtering out transactions that changed the document due to inputs that deleteCompositionText _if_ you are not in the middle of a composition. We listen for beforeinput and if we see an inputType of deleteCompositionText and then save a little piece of state in the plugin called preventDeleteCompositionText if view.composing is false. Then, we look for that piece of state filterTransaction and then unset preventDeleteCompositionText when the actual input event fires.

**Comment by jljorgenson18** [comment]
The actual problem is with the Chinese IME on iOS. They just seem to randomly fire off deletes in certain cases. We were seeing it happen during select alls or when you minimize the app.

**Comment by marijnh** [comment]
I finally managed to reproduce this. The conditions under which it happens seem quite specific—for example, I could only get it when I split the paragraph during the editing session, not when starting with a three-paragraph document.

What appears to be happening is that the browser (due to a bug in the Simplified Chinese IME, I assume) just deletes that content from the DOM when you focus the address bar. I can produce the same effect in a regular `contenteditable` element. As such, I think this is outside of ProseMirror's scope, and more of a Safari or iOS bug. Getting it fixed there is not going to be easy, of course, since Apple has left much worse bugs in their products for years, but I can't really think of a reasonable way to work around this on the ProseMirror level, since all the library sees is a change being made to the DOM, indistinguishable from regular, valid changes made by the user.
