### ISSUE TITLE
Support for inline nodes with content

### ISSUE THREAD

**Issue by johanneswilm** [ProseMirror/prosemirror#114]
Given

```
class Footnote extends Inline {
  get contains() { return "inline" }
}
```

I try to move the caret inside the inline node. This throws an error:

```
IndexSizeError: Failed to execute 'setEnd' on 'Range': There is no child at offset 1.
```

And the caret is moved to be outside of the inline node.

**Comment by marijnh** [comment]
Inline nodes having content is something that is possible at the data structure level, but not tested or thought through beyond that yet. I do want to work on this at some point, but there's a bunch of things with higher priority.

**Comment by marijnh** [comment]
There's some more discussion on this at https://discuss.prosemirror.net/t/discussion-inline-nodes-with-content/496/4 . The upshot seems to be that dealing with cursor motion and editing on the boundaries of such nodes is really tricky because they don't fit the rest of the content model. [Custom node views](https://discuss.prosemirror.net/t/rfc-node-views-to-manage-the-representation-of-nodes/463) might still make such structure useful though.

**Comment by marijnh** [comment]
I've decided to only support this when the node is drawn using a custom node view, since browsers just behave to awfully to have this work generally without custom special-case code.
