### ISSUE TITLE
Second text line longer than first inhibits upwards selection on chrome

### ISSUE THREAD

**Issue by Violeta-Amza** [ProseMirror/prosemirror#1143]
### Issue details

Second text line longer than the first one inhibits upwards selection. 

### Steps to reproduce

1. load https://prosemirror.net/
2.  replace the content with a simple plain text distributed on two lines( the second line should be longer than the first one). The example that I used is the following one: (see also the attached picture)
> Rich content editors should, ideally, produce clean, semantically meaningful documents  while still being easy for users to understand. ProseMirror tries to bridge the gap between editing explicit, content
3. press shift + arrow up keys => the second line is selected
4. press shift + arrow up keys one more time => as you can see nothing happens.

### ProseMirror version

latest

### Affected platforms

- [ ] Chrome

Note: I cannot replicate the issue on Firefox.

### Screenshots
![input](https://user-images.githubusercontent.com/32900172/111961677-024d2780-8afa-11eb-9b43-11cff39b248c.JPG)
![after_select](https://user-images.githubusercontent.com/32900172/111961549-ddf14b00-8af9-11eb-8ce4-f0442184aad8.JPG)

**Comment by marijnh** [comment]
This seems to be Chrome's native behavior (probably not intentional). I can reproduce it in any contenteditable element with a `white-space: pre-wrap` style.

I understand it can be annoying, but I don't think it's worth adding a custom workaround to the ProseMirror library for this. You could try reporting it in the [Chrome bugtracker](https://bugs.chromium.org) (but they don't usually respond very quickly there).

**Comment by Violeta-Amza** [comment]
Okay, I understand . Thank you for your response.
