### ISSUE TITLE
Broken "End"-Key Behaviour for Automatically Hyphenated Words

### ISSUE THREAD

**Issue by amxmln** [ProseMirror/prosemirror#1145]
### Issue details

Hitting the `End` key on a line with a word hyphenated by the browser (through `hyphens: auto;`) on Google Chrome on Linux causes the selection to jump to right after the first letter of the first line in that paragraph.

A similar issue also happens with the `Home` key in that it jumps to the last character before the automatic hyphen. The two are likely caused by the same issue.

### Steps to reproduce

1. Go to Prosemirror.net
2. Copy and paste the first paragraph *below* the demo editor into the editor
3. Enable `hyphens: auto;` on the `#editor` element via the Inspector panel
4. "being" and "unambiguous" should now be hyphenated
5. Place the caret in the first or second line and hit the `End` key
6. Caret (selection) jumps to right after first letter of paragraph

### ProseMirror version

Latest version from npm: 1.18.2 of View, 1.1.7 of Commands, and 1.13.3 of Model

### Affected platforms

Ubuntu 20.04

- [X] Chrome (latest)
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Other

I could not reproduce the issue on Firefox on the same system. Seems to be a Chrome thing, especially since they only very recently released automatic hyphenation on Linux.

Thank you for your time and keep up the great work!

**Comment by marijnh** [comment]
The editor leaves Home/End behavior to the browser, so what you're seeing here is a Chrome bug. Since `hypens: auto` isn't the default behavior, I don't want to add complexity to ProseMirror to work around this. So your best bet is to report this to the Chromium project and hope they fix it (might take ten years, unfortunately), or to add your own keybinding for End where you apply custom logic to try and do the right thing.

**Comment by amxmln** [comment]
Thanks for the quick update! Makes total sense. :+1: 

I guess the easiest workaround would be to just disable hyphens in my editor until Chrome fixes it.
