### ISSUE TITLE
Block-level decorations misapplied when dragging and dropping NodeView blocks

### ISSUE THREAD

**Issue by nkeynes** [ProseMirror/prosemirror#1166]
### Issue details

Dragging blocks controlled by NodeViews causes block-level decorations to be misapplied if NodeView.update() returns false. More specifically, it looks like the decoration update is applied to the node that _was_ at the position that the block was dropped at, then the dropped node is updated for its new position, but the first updated node is not re-updated.  

The issue only occurs if NodeView.update() returns false and a new NodeView is constructed; otherwise the updates execute correctly.

### Steps to reproduce

https://glitch.com/edit/#!/flawless-absorbing-result
1. Cmd-click to select e.g. the bottom text block   - the selected block is now coloured yellow
2. Drag the block up so that it is in a higher position - both the dropped block and the block immediately after it are now highlighted. Expected that only the dropped block would be highlighted 

Note also that the incorrect highlighting on the next block persists until that block is explicitly selected and then unselected.

### ProseMirror version

prosemirror-view: 1.18.2
prosemirror-model: 1.13.3
prosemirror-state: 1.3.4

### Affected platforms

- [X] Chrome
- [X] Firefox
- [ ] Internet Explorer
- [ ] Other

**Comment by nkeynes** [comment]
:facepalm: Thanks!
And yes, I was under the impression that the NodeView instance was being thrown away and recreated when update() returned false, but obviously it's not in this case, at least.

**Comment by marijnh** [comment]
What is happening is that `update` is called (with the dragged node as argument) on the node below the drop point. When that returns false, a new node view is created for the dropped node, and then the old node view (that had `update` called on it) is compared to the next node (which is the node the view was originally created for, but since nodes don't have identity, the view doesn't know that), which is identical, so no update has to happen and the (now mutated) node view is reused.
