### ISSUE TITLE
Drop cursor breaks table when table cell does not support node that will be dropped

### ISSUE THREAD

**Issue by pmairoldi** [ProseMirror/prosemirror#1176]
### Issue details

In the editor that I am building there are tables with table cells that can contain only 1 node. When using the dropcursor over these nodes it causes a weird layout and allows a drop where content is not possible causing the table to break.

### Steps to reproduce

Here is a project that reproduces the issue https://stackblitz.com/edit/prosemirror-dropcursor-position?file=style.css. To reproduce the bug the image has to be moved to on top of the green cells.

### ProseMirror version

`prosemirror-dropcursor 1.3.5`

### Affected platforms
I have only tested Chrome but probably applies to all browsers
- [X] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Other

### Screenshots / Screencast (Optional)
Reproduction:
![Jun-01-2021 20-00-38](https://user-images.githubusercontent.com/296718/120404302-142a2280-c314-11eb-9a2b-b14f6f994353.gif)

Error:
![Screen Shot 2021-06-01 at 7 57 26 PM](https://user-images.githubusercontent.com/296718/120404163-c01f3e00-c313-11eb-9af0-acde9274d361.png)

**Comment by marijnh** [comment]
The error in the demo happens because your document wasn't valid to begin with (there's a paragraph in the table). The table-munging behavior in the screencast is just the replace algorithm creating the necessary structure to fit an image at the place below the cursor.

The drop cursor indeed assumes a rather simple blocks + inline content layout, and doesn't seem to be able to handle tables or other columnar layouts well. It may be necessary to write your own custom drag handling for your use case.

**Comment by pmairoldi** [comment]
Thanks for the quick reply. I'll look into moving to our own drop cursor implementation. Ah you're right about the paragraph my bad on that one.
