### ISSUE TITLE
Whitespace is not preserved in marks when using DomParser.parseSlice

### ISSUE THREAD

**Issue by jordandh** [ProseMirror/prosemirror#1182]
### Issue details

When parsing a part of a document that contains only a mark with whitespace the resulting slice is empty.

### Steps to reproduce

```html
<div style="display: none" id="slice1"><b> </b></div>
```
```javascript
const parser = DOMParser.fromSchema(schema);
const slice1 = parser.parseSlice(document.querySelector("#slice1"), { preserveWhitespace: true });
```

https://glitch.com/edit/#!/prosemirror-mark-parseslice?path=README.md%3A1%3A0

### ProseMirror version

Latest in the Glitch based off of prosemirror-basic

### Affected platforms

- [ x] Chrome
- [ x] Firefox
- [ x] Edge
- [ x] Node

### Screenshots / Screencast (Optional)

![image](https://user-images.githubusercontent.com/68006/122154099-14004b80-ce19-11eb-83d0-07bc3568e437.png)

**Comment by marijnh** [comment]
`preserveWhitespace: true` will still drop whitespace-only text in non-inline context. `parseSlice` starts without context (it doesn't parse a full doc, only some random content slice). So at the point where that text is seen, it hasn't established that it should be in an inline context, and will ignore the whitespace-only content. Attached patch adds a heuristic that avoids the problem in this case, but you'll still see it if you remove the `<b>` tag, because the parser can't reliably guess how to interpret the content in that case.

**Comment by jordandh** [comment]
Thanks @marijnh, the attached patch fixed the problem for me.
