### ISSUE TITLE
Node decoration causes odd selection behavior 

### ISSUE THREAD

**Issue by cameronmbell** [ProseMirror/prosemirror#1200]
### Issue details

Creating a node decoration that depends on the selection, will cause the selection to behave in an unintuitive way, often losing the selection anchor

### Steps to reproduce

Create a node decoration based on the selection in a simple document with paragraph nodes.

```js
new Plugin({
    props: {
        decorations: (state) => {
            const { doc, selection } = state;

            if (selection.from === selection.to) {
                return null;
            }

            const decorations = [];
            doc.nodesBetween(selection.from, selection.to, (node, pos) => {
                decorations.push(
                    Decoration.node(
                        pos,
                        pos + node.nodeSize,
                        { class: 'selected-node' },
                    ),
                );

                return true;
            });

            return decorations.length !== 0 && DecorationSet.create(doc, decorations);
        },
    },
})
```

### ProseMirror version
```json
"prosemirror-commands": "^1.1.10",
"prosemirror-gapcursor": "^1.1.5",
"prosemirror-history": "^1.2.0",
"prosemirror-inputrules": "^1.1.3",
"prosemirror-keymap": "^1.1.4",
"prosemirror-model": "^1.14.3",
"prosemirror-state": "^1.3.4",
"prosemirror-transform": "^1.3.2",
"prosemirror-view": "^1.19.3",
```

### Affected platforms

- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Other

(I could only test chrome)

### Screenshots / Screencast (Optional)

Expected (selection behavior without plugin):
![expected-behaviour](https://user-images.githubusercontent.com/16931162/131871882-f898864e-9d98-4d04-b262-9d4899524542.gif)

Unexpected (selection behavior with plugin, notice how the bottom lines get unselected):
![unexpected-behaviour](https://user-images.githubusercontent.com/16931162/131871867-452a0fe6-f1d4-4944-a436-ca31540bfc4a.gif)

**Comment by marijnh** [comment]
ProseMirror relies on the browser's native drag-selection behavior. Unfortunately, Chrome is quite bad about randomly disrupting a drag-select when the DOM around it changes (wrapping something in a node does that). In this case, though, I suspect it's pretty easy to work around by only adding the class to block nodes, or at least making sure you're not adding it to text nodes (which weren't supposed to even allow node decorations, but I just found that due to a bug they did, which will cause an extra `<span>` node to be rendered around them, which is probably the cause of this issue).

**Comment by cameronmbell** [comment]
Thanks for the quick reply and continued work to keep this great project going. That sorted it out.
