### ISSUE TITLE
Pasting, node ignored

### ISSUE THREAD

**Issue by amk221** [ProseMirror/prosemirror#1203]
### Issue details

https://glitch.com/edit/#!/pine-pyrite-dumpling?path=index.js%3A65%3A14

The above Glitch renders some coloured text.

The fact that it is coloured isn't important to the reproduction, it's just there to show _ProseMirror correctly parsed it_ from JSON.

However, pasting results in the node being ignored

### Steps to reproduce

1. Visit: https://cdn.sekurak.pl/copy-paste/playground.html
2. Paste `<span style="color: red">World</span>` into the first box
3. Click copy as HTML
4. Paste into the ProseMirror instance.
5. Acknowledge that the schema supports spans with a style attribute, therefore the text should be red.

Repeat, but this time:

1. Visit: https://cdn.sekurak.pl/copy-paste/playground.html
2. Paste `Hello <span style="color: red">World</span>` into the first box
3. Click copy as HTML
4. Paste into the ProseMirror instance.
5. Acknowledge that the text is red, as expected

### ProseMirror version

1.20.0

### Affected platforms

- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Other

**Comment by marijnh** [comment]
ProseMirror's pasting will, for content that doesn't come from a ProseMirror editor, consider pasted nodes to be ['open'](https://prosemirror.net/docs/ref/#model.Slice.openStart), and if its content is valid in the position where you're pasting, directly merge it. This is because browsers will usually include a bunch of parent nodes when copying content, and we don't want, if you copy some text and the browser gives us `<p>abc</p>`, to start a new paragraph when you paste that into an inline context.
