### ISSUE TITLE
`autoJoin` can't accept a command with three arguments

### ISSUE THREAD

**Issue by ocavue** [ProseMirror/prosemirror#1211]
The [`autoJoin`](https://github.com/ProseMirror/prosemirror-commands/blob/ab3dfd169f8710fd6c4b37209c0c769a9e127ce0/src/commands.js#L574) currently returns a new command function which only accepts two arguments `(state, dispatch)`. This won't work for commands which accept more arguments.

It seems that this could be fixed easily by adding `...args` as below:

```js
export function autoJoin(command, isJoinable) {
  if (Array.isArray(isJoinable)) {
    let types = isJoinable
    isJoinable = node => types.indexOf(node.type.name) > -1
  }
  return (state, dispatch, ...args) => command(state, dispatch && wrapDispatchForJoin(dispatch, isJoinable), ...args)
}
```

I'm also thinking maybe we could export `wrapDispatchForJoin`, so that users can build their own `autoJoin` even if their command functions don't accept the argument pattern `(state, dispatch, ...args)`.

**Comment by marijnh** [comment]
Good point. There isn't really a command calling convention that takes anything other than (state, dispatch) or (state, dispatch, view), so no need for a rest argument here I think.

I don't want to export special-case utility functions like this, since making them public will lock them into the interface forever. It should usually be possible to use `autoJoin` directly with a little function-call acrobatics.

**Comment by ocavue** [comment]
@marijnh Thank you for the quick fix and explanation.
