### ISSUE TITLE
Copy multiline text from contenteditable to prosemirror spoils linebreaks

### ISSUE THREAD

**Issue by GaurangTandon** [ProseMirror/prosemirror#1218]
**Steps to Reproduce**

1. Goto https://jsfiddle.net/27of5xmb/ to see a minimal `div[contenteditable]` setup
2. Insert content so that it becomes `a\n\nb`. See screenshot attached for visual and DOM tree:
    ![image](https://user-images.githubusercontent.com/6308683/140956175-980a4231-0008-409e-ad17-4b23eacafc2e.png)

3. Select all content in the conteneditable and copy it (Ctrl-A and Ctrl-C)
4. Paste it in the prosemirror instance on https://prosemirror.net

**Expected result**

Prosemirror editor contains **three lines total** (middle line being blank)

**Actual result**

Prosemirror editor contains three paragraphs, and the middle paragraph has two lines separated by a line break. So, **four lines total**. See DOM tree and visual below:

![image](https://user-images.githubusercontent.com/6308683/140956653-78c66407-c304-42f6-bded-ceb0dbf0e365.png)

**Notes**

It seems to me that this method - `addHackNode` - has something to do with this situation:

https://github.com/ProseMirror/prosemirror-view/blob/master/src/viewdesc.js#L1264

Judging by its name, perhaps it should be replaced with a non-hacky approach.

**Comment by marijnh** [comment]
Browsers will add extra `<br>` nodes to editable content, for weird historic reasons (they prevent empty paragraphs from collapsing, for one thing). So it seems that when you copy content from such an editor, the browser puts those nodes on the clipboard as well. What you are seeing here is ProseMirror seeing `<br>` nodes and parsing them as hard breaks, which is not entirely unreasonable. Attached patches change it so that clipboard parsing will ignore trailing `<br>` nodes—this may in some cases be bad, if the HTML content actually contains significant trailing break nodes, but I guess the situations where copying from contenteditable content introduces unwanted breaks are more common.

**Comment by katepol** [comment]
This fix causes another issue with prosemirror-markdown model: pasting html like
```
<div><meta http-equiv="content-type" content="text/html; charset=UTF-8"><pre><span># heading<br></span>plain text</pre></div>
```
into the editor at https://prosemirror.net/examples/markdown results in lost line break :(

@marijnh should I file a separate issue?

**Comment by marijnh** [comment]
Hm, good point. This remains a heuristic and will probably never do the right thing in all situations, but attached patch might help in this case.

**Comment by katepol** [comment]
thank you! could you make a new tag for prosemirror-view, please?

**Comment by marijnh** [comment]
Tagged as 1.23.3.
