### ISSUE TITLE
Inline nodes with editable content behave unexpectedly 

### ISSUE THREAD

**Issue by schostac** [ProseMirror/prosemirror#1238]
Hello,

#### Use cases
I have 3 types of custom nodes whose attributes contain business data and displayed borders convey certain meaning to users:

1. Block node (`content: 'block+'`, `atom: false`);
2. Inline node with _editable_ content (`content: 'inline+'`, `atom: false`);
3. Inline node with _non-editable_ content (`content: 'inline+'`, `atom: true`).

Of course, I could use marks instead of inline nodes with editable content. But mixing nodes and marks is inconvenient in my case.

Below you can see an example of 2 such nodes (inline node with editable content and red borders and selection inside, and block node with gray borders).

![image](https://user-images.githubusercontent.com/20142779/151672648-0b36e5c9-3de7-4772-964f-a0d94a6e3f0e.png)

#### Problems
For the most part, I managed to make inline nodes with editable content behave more or less like marks using `ReplaceAroundStep`, joining siblings with the same attributes, etc.

However, I'm still facing the following problems:

1. Given the selection inside an inline node with editable content, pressing `Enter` does not split anything. I see that in the [keymap](https://github.com/ProseMirror/prosemirror-commands/blob/master/src/commands.js#L638) `Enter` does not seem to have a command for such split while [splitBlock](https://github.com/ProseMirror/prosemirror-commands/blob/master/src/commands.js#L306) command expects only block nodes.

2. Given the selection right after an inline node with edible content, pressing `Backspace` removes the whole node not not just a part of text inside (as it would be in case of a block node and mark).

I understand the above behavior makes perfect sense for inline nodes with non-editable content (atoms). But for inline nodes with editable content I'd expect the behavior to be more or less like in case of marks.

#### Questions

1. Are those 2 described behaviors of inline nodes with editable content  by intent or some fixing is needed?
2. If by intent, what is the rationale?

**Comment by marijnh** [comment]
The library, more or less intentionally, doesn't try to handle nested inline content, because the way that should behave is so tricky and use-case dependent that we didn't find a reasonable way to handle it by default. See [this thread](https://discuss.prosemirror.net/t/discussion-inline-nodes-with-content/496) for some background. The general idea is that you'll want to define custom key handlers that do what you want them to do in and around your nodes.

I'm going to close this issue, since it's more of a question than an issue, but feel free to add replies or start a forum thread.
