### ISSUE TITLE
Chrome renders cursor in wrong place when it's in between two atom nodes

### ISSUE THREAD

**Issue by cpmsmith** [ProseMirror/prosemirror#1245]
This is easily reproducible in the [Dino example](https://prosemirror.net/examples/dino/) by:
a) moving a dino directly next to another
b) placing the cursor in between the two dinos

<img width="569" alt="image" src="https://user-images.githubusercontent.com/9437625/155249543-0a6182ac-1d38-40aa-bd0a-049fc751f55d.png">

Firefox doesn't render the cursor at all, and Safari renders the cursor fine, at full line height. I've tested on macOS and Windows (excl. Safari, obviously)

**Comment by marijnh** [comment]
Yes, this is a Chrome bug. See also [this thread](https://discuss.prosemirror.net/t/cursor-appears-in-the-wrong-position-in-chrome-98/4409/4).

**Comment by cpmsmith** [comment]
Ah, I didn't check the forum, thanks. [lflan's tip](https://discuss.prosemirror.net/t/cursor-appears-in-the-wrong-position-in-chrome-98/4409/4) seems like a good lead. Is there an upstream bug report I can track in the meantime?

**Comment by marijnh** [comment]
I can't find whether this specific issue was submitted to Chrome yet. So it may be a good idea to add one (and link it here). Should be pretty easy to derive the minimal HTML needed to trigger it, though you might need to use `getSelection().collapse` to put the selection between two uneditable nodes in a reproduction, since the default arrow motion probably won't.

**Comment by cpmsmith** [comment]
This appears to have been fixed in Chrome 🎉 

<img width="593" alt="image" src="https://github.com/ProseMirror/prosemirror/assets/9437625/b84f7e7e-8e39-4c2c-9871-9e3e4355b289">

**Comment by marijnh** [comment]
Great to hear! Thanks for posting an update.
