### ISSUE TITLE
Deleting first node in NodeView with backspace deletes entire node view content

### ISSUE THREAD

**Issue by whawker** [ProseMirror/prosemirror#1257]
I have a node which uses a NodeView to render editable content. 

When I empty the first node in the NodeView (using backspace in the example below) it deletes the entire node view.

https://user-images.githubusercontent.com/2003804/159926983-248c4e8e-3fc8-459f-962b-fb719ff27d9c.mov

I would expect this to lift the paragraph out of the node view, and preserve the remaining content in the NodeView.

### Reproduction steps
1. Delete text in the first line of blue callout node, leaving one character remaining
2. Delete this remaining character with backspace
3. Observe the entire content of the NodeView is removed.

### CodeSandbox minimal reproduction
https://codesandbox.io/s/prosemirror-node-view-6q4wdj

**Comment by marijnh** [comment]
Attached patch should help with this. It was caused by some rather odd Chrome behavior (it recreates the paragraph's parent element when you backspace out that last character).

But also, unless your actual use case has a purpose for it, you might as well do `this.contentDOM = this.dom` in your node view to keep the DOM structure simple and avoid this kind of complexity entirely.

**Comment by marijnh** [comment]
Thanks for spotting that!

**Comment by whawker** [comment]
Any chance this fix could be published?

**Comment by marijnh** [comment]
Sure, tagged 1.23.11
