### ISSUE TITLE
Composition ended on Android after 5s delay when typing in an empty paragraph

### ISSUE THREAD

**Issue by igandrews** [ProseMirror/prosemirror#1262]
On an android device (e.g. Samsung S20):
* Run chrome
* Navigate to prosemirror.net
* Select all the content in the editor
* Press backspace to delete it
* Change the keyboard to an ime one (e.g. Japanese Qwerty)
* Type `k` 
![image](https://user-images.githubusercontent.com/17983788/163056339-edf9129c-6acd-41bd-8e1e-1ac64edd34c9.png)

* Wait 5 seconds 

Result: The composition is ended. 
![image](https://user-images.githubusercontent.com/17983788/163056360-336c2dea-80ef-4c43-87d4-f8deac6a5ca3.png)
This happens as a result of something done in the 5s timeout invoked from the composition start|update handler [here](https://github.com/ProseMirror/prosemirror-view/blob/97faf3033bd99c28739fe23f3b584da159ca4546/src/input.js#L454).

Note if the paragraph is not empty the composition is _not_ ended. E.g. type another k and wait 5 seconds and it remains in composition: 
![image](https://user-images.githubusercontent.com/17983788/163056439-4d91fa72-de4f-4b44-9229-41ae48fc52bc.png)

**Comment by marijnh** [comment]
Active composition can prevent ProseMirror from properly updating its content (it can't change the nodes directly touching the cursor, because that would abort or even corrupt the composition). So, since Android tends to pretty much always be in composition, it intentionally flushes its DOM after 5 seconds of inactivity. Apparently that only actually ends the user-visible composition in some cases (I guess because in the case of the originally-empty paragraph it removed the `<br>` kludge node), but this is all pretty much working as intended.
