### ISSUE TITLE
Node selections can't be dragged

### ISSUE THREAD

**Issue by marijnh** [ProseMirror/prosemirror#127]
They probably should allow that.

**Comment by marijnh** [comment]
So Firefox, in its infinite wisdom, seems to make it impossible for `contentEditable` elements to be draggable in the HTML5 drag/drop API sense. This is a pretty big damper, on the possibility of this feature, unless we find a workaround.

Attached patch implements the feature in a way that works on Chrome. Haven't tested IE yet.

**Comment by marijnh** [comment]
Latest attached patch sorta works around the issue, but might end up having undesirable side effects.

**Comment by ericandrewlewis** [comment]
If I make a node-level selection of a paragraph, I must click and drag from the end of the paragraph where there is no text (i.e. where the internal `<span>` does not continue). If I have made a node-level selection, I expect to be able to click and drag from somewhere obvious, perhaps even on the text of the paragraph itself?

If I have two paragraphs and try to drag the bottom paragraph above the top paragraph, the two merge into one paragraph. I think a user expectation would be to rearrange nodes instead of combining their content when dragging around node selections.

**Comment by marijnh** [comment]
In general, it seems `draggable` affects all child nodes, but in the case of contentEditable, there seems to be an exception for (unselected) text, which keeps its drag-to-select behavior. I agree that being able to drag from the text of a selected node would be good, but I also want to keep click-to-set-cursor working in such nodes (so a solution like setting `pointer-events: none` on its children is not going to work).

**Comment by ericandrewlewis** [comment]
Modifying the [mightDrag logic](https://github.com/ProseMirror/prosemirror/blob/dc090215e7259983011558234fb38bfc6863105e/src/edit/input.js#L211-L216) to be aware of a node selection on mousedown seems like a good first step. 

Here, we could check if where the user clicked is within a current node selection, and then set `draggable="true"` and `contenteditable="false"` on the selected node accordingly. 

What's the best way to check whether a ProseMirror document node contains a DOM node? I didn't see any API methods available for this sort of check (only see `pathFromDOM()`.

After that, we can look into filling in the clipboard data appropriately.

**Comment by marijnh** [comment]
> What's the best way to check whether a ProseMirror document node contains a DOM node?

`pathFromDOM` will tell you the path that the dom node is part of, which can then lead you to the document node.

Setting `contenteditable="false"` when mousedowning on text in a selected node will break click-to-set-cursor in that node.

**Comment by ericandrewlewis** [comment]
> Setting `contenteditable="false"` when mousedowning on text in a selected node will break click-to-set-cursor in that node.

I wonder if we could handle "click-to-set-cursor in the node" manually, so that when the user has a node selected we can allow for the user to drag anywhere in the node including the body text, and also support click to set cursor. I've been able to get this working [here](https://github.com/ericandrewlewis/prosemirror/commit/e82d0513e724ce29ed0b8a477f6a93e8ca12410d).

I [commented out some functionality](https://github.com/ericandrewlewis/prosemirror/commit/e82d0513e724ce29ed0b8a477f6a93e8ca12410d#diff-120433adafe0a50dd44fe017782a0da0R267) that I'm unfamiliar with for the proof of concept here.

**Comment by marijnh** [comment]
> I wonder if we could handle "click-to-set-cursor in the node" manually

We could, but the reason I'm shying away from that as much as possible is that it gets rather complicated in bidirectional code, and invasive mouse handling code that works on mobile is also tricky. I guess as a last-ditch solution it's acceptable (`posAtCoords` finds the place), but try to do it in such a way that as many mouse events as possible still do the native thing unobstructed.

**Comment by ericandrewlewis** [comment]
After looking across a few browsers, I'm noticing what is in `master` works well already in Safari and Firefox without any changes.

This also works on Chrome, although the behavior is slightly different. After making a node selection, you have to wait about 500ms and then drag. Otherwise the browser decides that you want to modify the head of your current selection.

I'm also seeing this behavior working well without the [modifications for Firefox](https://github.com/ProseMirror/prosemirror/commit/d8eb3cb446d8a5ff8e864307e0545e18c29d66d4) by dragging the text content. I [made a screen recording](https://www.youtube.com/watch?v=avPMCiSa5VU&feature=youtu.be) to show the Chrome and FF experiences. 

We can iterate on the drag-and-drop experience, but to the issue's original intent, nodes can definitely be dragged. Maybe we can close out this issue and open up new ones for follow-up?

**Comment by marijnh** [comment]
> After making a node selection, you have to wait about 500ms and then drag. 

Huh, that's obscure. Oh well. Agreed, let's close this and open specific ones as they come up.
