### ISSUE TITLE
Memory leak because of `resolveCache` in prosemirror-model

### ISSUE THREAD

**Issue by MihirGH** [ProseMirror/prosemirror#1325]
Since we are declaring the `resolveCache` [as a global variable here in line 247](https://github.com/ProseMirror/prosemirror-model/blob/master/src/resolvedpos.ts#L247) and adding entries in the `resolveCache` and never clearing them when the respective view/state is destroyed, it causes a memory leak via leak of closures and the size of the leak is dependent on how much data the closure of entries in the `resolveCache` bring - as can be seen in the second screenshot.

I also think that declaring the resolveCache globally is incorrect and the entries are not segregated based on respective view/state and if more than one editors are mounted then the cache will have entries from different editors.

Attaching screenshots of the leak for my app. Sadly I am not able reproduce it in isolation since there are many plugins in my app and it is difficult to replicate such a long closure chain. Hope the description and screenshots help.

![image](https://user-images.githubusercontent.com/48630359/198939902-baeeb4f5-bd9d-4ce6-9150-9f015cdb4beb.png)

![image](https://user-images.githubusercontent.com/48630359/198940532-ca1d4b22-efba-49e0-814c-9d86eb1734f3.png)

**Comment by marijnh** [comment]
There are no closures in `resolveCache`. It holds on to up to 12 recently resolved positions. If you had read the code, you'd see that entries _do_ have their `doc` checked when reused, so this is all correct and intentional. The holding on to a few documents is a cost intentionally paid for the ability to avoid re-resolving the same position when queried.
