### ISSUE TITLE
Pasted content from Word on Windows not sanitized properly

### ISSUE THREAD

**Issue by tgecho** [ProseMirror/prosemirror#137]
When I paste text from Word 2013 (Win 7, IE 10 or Chrome), PM fails to strip out the formatting garbage.

![image](https://cloud.githubusercontent.com/assets/49615/12403855/eed896fc-be04-11e5-9c51-3e3e6fa0b4bb.png)

This is what word placed in the `text/html` data part of the clipboard: https://gist.github.com/tgecho/44382d028957f46aa529

In this case, I would personally be happy if we just got the plain text. I haven't finished tracing out where ProseMirror accidentally accepts what should have been comments or some other ignorable thing, but I wanted to document this for now.

**Comment by tgecho** [comment]
So there are two fun pieces in here that are slipping through.

The comments above "This is a test" are actually inside a style tag... yep, Word emits `<style> <!--  .... --></style>`. Since these are not valid css comments, the browser sets them as textContent of the style element. When ProseMirror comes along, it doesn't recognize a style element, so it strips that and is left with this beautiful gunk.

The gibberish at the bottom is actually after the `</html>` in the pasted html string. Other than that it's just garbage.

I can't think of a clean, elegant way to tighten things up. I assume you're trying to avoid a mess of application specific sanitizers. The simplest/most reliable fix I can come up with would be to snip out everything between the `<!--StartFragment-->` and `<!--EndFragment-->`. I don't have any other copies of Word for windows kicking around to test other variations, but from a bit of light googling this appears to be commonly used.

This isn't super pretty, but it seems to work well enough. Worth a PR @marijnh? Thoughts/changes beyond a test case and explanatory comments?

```js
export function fromHTML(schema, html, options) {
  let wrap = (options && options.document || window.document).createElement("div")

  let startComment = '<!--StartFragment-->'
  let startSlice = html.indexOf(startComment)
  if (startSlice > -1) {
    wrap.innerHTML = html.slice(
      startSlice + startComment.length,
      html.indexOf('<!--EndFragment-->'))
  } else {
    wrap.innerHTML = html
  }

  return fromDOM(schema, wrap, options)
}
```

As an aside, I was going to vote for https://github.com/ProseMirror/prosemirror/issues/72, but am I right to think that overriding the html (or text) source functions with `defineSource("html", myFromHTML)` is a reasonable way to accomplish most any super custom string level paste preprocessing?

**Comment by tgecho** [comment]
Hrm. I was actually mistaken, and the paste handler is currently hardcoded to use the stock `fromHTML` function. It's a simple change, so my question still stands :)

**Comment by marijnh** [comment]
Attached patch causes the DOM parser to ignore the content of 'non-displaying' tags like `<style>`. That should take care of one of the problems.

As for the Unicode garbage at the end of the document... I'm not sure what to make of that. Do you have any idea what it means and why it ended up on your clipboard?

**Comment by tgecho** [comment]
Great! Filtering out <style> should definitely fix the worst of the problem.

I really can't figure out more on the gibberish. All I'm doing is copying some unstyled text from word and pasting it into PM. I'll try to get my hands on another version of Word or something. In this case it's Word 2013/Win 7/Chrome.

**Comment by mattberkowitz** [comment]
What about using a DOMParser rather than innerHTML?

```
	export function fromHTML(schema, html, options) {
	  let doc = (new DOMParser()).parseFromString(html.replace(/<\/html>[\s\S]*/, "</html>"), "text/html")
	  return fromDOM(schema, doc.documentElement.querySelector('body'), options)
	}
```

Which would throw away all the (assumedly unimportant) non-`<body>` stuff

`html.replace(/<\/html>[\s\S]*/, "</html>")` gets rid of any gibberish after `</html>` (if it's present). I only have Word 2011 for OSX to test with, which doesn't include any gibberish, only a newline after `</html>`. When I copied the text from the gist, Chrome's DOMParser moved the gibberish inside the body, which is annoying, but expected, based on what I've seen of native dom parsing in the past.

DOMParser has relatively good support (https://developer.mozilla.org/en-US/docs/Web/API/DOMParser) and you could always fall back to the current innerHTML method, if need be.

**Comment by pboysen** [comment]
While I can't think of a use case now, there might be a time when I want to look at the content of one of those nodes.  Would it make sense that if no command processes it (they all return false), you just throw it away?

**Comment by marijnh** [comment]
I am not interested in having Word-specific hacks in the core library, since I expect it'll take a whole platoon of them to get around all the junk that Word adds. The `transformPastedHTML` and `transformPasted` events should give a 3rd-party module the hooks it needs to implement.

If you feel a specific HTML-cleanup issue should be handled by the core library, open a specific issue.

**Comment by juliankrispel** [comment]
Thanks @marijnh - I've updated the blogpost, this makes the solution a lot cleaner!
