### ISSUE TITLE
Pasting text inside of a link splits the link in two

### ISSUE THREAD

**Issue by ericandrewlewis** [ProseMirror/prosemirror#1386]
Consider a document that has a link in it:

```
Hey Eric, here is the <a href="some-url">event I am going to</a>.
```

If you copy and paste plain text into the link, the link is split:

```
Hey Eric, here is the <a href="some-url">event </a> on Friday, Jun 8th<a href="some-url"> I am going to</a>.
```

This is unexpected to me. I'd expect the pasted plain text to become part of the link. 

I believe the [`doPaste()`](https://github.com/ProseMirror/prosemirror-view/blob/3e09a363af52593b8cb889b0405fb8d464227c02/src/input.ts#L601) method is related.

I notice this in Chrome on Mac, although would guess the behavior applies to other browsers as well.

You can reproduce this in the editor on [the homepage](https://prosemirror.net/).

**Comment by marijnh** [comment]
If you paste plain text (i.e. paste from the URL bar or Emacs) it seems to add the link mark to the pasted text.

If you paste html that holds just text, it keeps the markup (i.e. no link) from the pasted content.

Are you suggesting there should be some logic to recognize HTML that holds just text, and treat that as a text insertion rather than a paste of already-styled content? Or do you think context marks should always be added to pasted content? (Only inline content, or also pastes that span multiple blocks?)
