### ISSUE TITLE
Publish prosemirror to the npm registry

### ISSUE THREAD

**Issue by monkbroc** [ProseMirror/prosemirror#14]
The package.json uses the package name prosemirror but it's not available on npm yet. You should publish it at least to reserve the name before someone else does.

**Comment by marijnh** [comment]
Good point. I've published an empty placeholder package.

**Comment by BigBlueHat** [comment]
@marijnh I'm loving ProseMirror so far, thank you (again...as a CodeMirror fan of old)! :smiley_cat:

What's needed to get ProseMirror install-able on NPM? I'd dearly love to be able to simply `npm install` vs. the steps that are needed now.

Happy to help if I can!

**Comment by marijnh** [comment]
> What's needed to get ProseMirror install-able on NPM?

The interface will have to get stable enough for me to bother putting a version number on it. (Right now, there's breaking changes every few days, and there's things in a messy state that no one should be using in production.) In the meantime, just pin to a git revision (you can put git urls in `package.json`), since that the only way you'll get a stable API.

**Comment by BigBlueHat** [comment]
Got it. I'll just "automate" the sub-`npm install` and `npm run dist` bits in the meantime, I suppose.

Thanks for the speedy response! :bullettrain_side:
