### ISSUE TITLE
Dragging and dropping a node selection breaks other nodes in two

### ISSUE THREAD

**Issue by ericandrewlewis** [ProseMirror/prosemirror#188]
Say I have multiple paragraphs. If I make a node selection of one paragraph and drag it into the middle of another paragraph, the paragraph I drag it into will be split into two paragraphs, with the dragged paragraph inserted between the two. Here's a [screen recording](https://www.youtube.com/watch?v=2FXCp97SE9g&feature=youtu.be) showing the behavior.

If a user has made a node selection, I'd expect they want to re-order nodes (e.g. I want to move paragraph between these two other paragraphs) rather than split up existing nodes.

**Comment by marijnh** [comment]
Splitting the paragraph in two when a block is inserted into it is reasonable behavior, I think. The issue is how we determine block positoin. Currently the drop handler looks for a text cursor position nearest to the mouse position.

We could make a rule where, if the dropped content is a block, we use a different algorithm, which tries to find a between-blocks position near the cursor (or, probably even better, looks at the dropped content type, and finds a position where that content is allowed).

You'd need something similar to `posAtCoords`, but which selectively walks down the tree looking for a suitable position, doing appropriate rounding (i.e. if you drop near the top of a paragraph, the block should go before it, if you drop near the bottom, after it).

**Comment by ericandrewlewis** [comment]
Work in progress [here](https://github.com/ericandrewlewis/prosemirror/commit/0f2fd0f8032ae7cbd158fdd0324aef7af4365037). Feedback welcome, will continue on this.

**Comment by marijnh** [comment]
The way clipboard/dragged data is current represented, you'll always get a block node at the top level, because the data is wrapped in a `doc` and those only allow block nodes as direct content.

I'm thinking about modifying this representation, since it is a bit awkward (often pulls in a bunch of wrapping nodes that aren't directly relevant to the clipboard content, and then relies on the position of `from` and `to` to drop these wrappers again when a replace step is generated). The reason it is the way is currently is is that the DOM parser will, if given a fragment that doesn't fit in the document, make up intermediate nodes to connect it, and then, in the resulting magic, we won't know what the `from`/`to` positions (which are significant to determine the amount of 'open' nodes on both sides) should refer to.

The solution to this is probably to set up the parser so that it can parse without trying to root the content in a `doc` node. But then we'd also have to adjust `transform/replace.js`'s algorithm to not rely on full documents being passed in. (I'm currently working on `replace.js`, preparing it for locked nodes, I'll look into this.)

**Comment by ericandrewlewis** [comment]
> I'm thinking about modifying this representation, since it is a bit awkward

Yes, that sounds useful. Let me know if I can help with anything.

**Comment by pboysen** [comment]
I my use case I need to control where a draggable question node can be dropped (top level).  Who knows better than the schema developer where a draggable node should be dropped? At the point where your drop code gets the insertPos, you could invoke a method on the draggable node type to let you know the position.  Something like
```
export class Question extends Block {
  get draggable() { return true  }
  getDropPos(pm, from, to) { // return pos of drop point or null if drop should be cancelled}
}
```
I would use `from` to inform the decision if need be.  Wouldn't this avoid a complex algorithm where to automatically put it?  If getDropPos was not defined, use your existing insertPos.

**Comment by pboysen** [comment]
Here is my latest hack to determine the drop position in handlers.drop:
```
    let insertPos = pm.posAtCoords({left: e.clientX, top: e.clientY})
    let df = pm.input.draggingFrom, node = pm.doc.path(df.from.path.concat(df.from.offset))
    if (node.type.draggable && node.type.getDropPos)
    	insertPos = node.type.getDropPos(pm,df.from,insertPos)
    if (!insertPos) return
```
Here is the schema:
```
export class Question extends Block {
	get draggable() { return true }
	getDropPos(pm, from, to) { return to? getTopPos(to): null }
}
```
As with insertPos, getDropPos will return null if the drop should not happen.
