### ISSUE TITLE
Make it possible to escape from list item to next list item

### ISSUE THREAD

**Issue by marijnh** [ProseMirror/prosemirror#21]
Currently, if you're in a wrapped  continued list item, you can't get back to the original list.

We're using backspace as conceptually blanking out stuff in front of the cursor, so backspace in a (non-first) list item removes the number, putting you into the item above.

So we can't also use backspace to get out of a continued item -- that'd get you in a loop where you can't escape from the list itself.

Currently enter in an empty continued list item will escape the list. Making it get you back into the list item doesn't seem like it'd make a lot of sense.

Overloading the wrap-in-list control for this is also not acceptable -- you might want to create a nested list in this situation.

Not sure what options that leaves us with.

**Comment by funkyeah** [comment]
In the current demo, when you create a list item, the text in that list item is not put directly into the `<li>` but rather inside of a `<span>` that is inside of `<p>` that is inside of the `<li>` e.g. 

```
<li>
    <p><span> first li text here </span></p>
</li>
```

backspace in a (non-first) list item does remove you out of the second list item and into the first list item, but importantly it places you into a sibling `<p>` to the `<p>` of the text of the original list item. e.g.
```
<li>
    <p><span> first li text here </span></p>
    <p><span> new text here </span></p>
</li>
```
I can see how this could make for the ability to add some nicely formatted text in the very specific case of:
 * you don't want the text to be in the next list time or a nested list item
 * you do want the text to be in a separate paragraph from the first list item

I would argue though that this nicety is not worth the amount of standard use patterns it breaks and might be better implemented as a dedicated function like a button for "continue previous list item".

Having said that I think the more overarching problem here is that Prosemirror does not have a dedicated outdent / indent system. It is actually utilizing the standard icon for outdent as the "Move out of block" button. I believe there is a recipe for long-term confusion in doing that.

Are there technical reasons indent and outdent can't be implemented? If they can be then it seems the only issue that would be left to resolve is the semantics of what keystrokes/shortcuts initiate indent and outdent and in what contexts they initiate it.

A survey of some of the popular editing interfaces shows (depending on the context) indent can be initiated with:

 * tab
 * ctrl+]
 * alt+shift+right arrow

outdent

 * shift+tab
 * ctrl+[
 * alt+shift+left arrow
 * hitting enter twice will escape you from the list block

Tab is a sensitive one for the web because it already has a dedicated meaning. Google takes that approach that if you are in google docs tab should act as an indenting function because it is a dedicated word processor and tabbing around to different parts of the page isn't really a thing. In Gmail they take the opposite approach and tab sticks to its default behavior. In both instances ctrl+] and ctrl+[ work as expected. Maybe this would be a configuration setting for a particular instance of prosemirror?

Cheers,
George (and congrats on the Indiegogo success, I made a measly portion for what its worth)

**Comment by funkyeah** [comment]
Any thoughts on this? I'm happy to do more research if it helps.

**Comment by marijnh** [comment]
I've changed the way enter and backspace work to be somewhat less standard but more coherent (for one thing, they are now, whenever applicable, each others inverse).

Enter in a list item now continues it. Enter again moves to a new list item. Enter a third time escapes from the list.

To get back into a previous list item, backspace at the start of the paragraph can be used. Backspacing or deleting out a paragraph between lists merges those lists.
