### ISSUE TITLE
iOS Holding down the delete key for extended period has unexpected results.

### ISSUE THREAD

**Issue by nickvelloff** [ProseMirror/prosemirror#218]
iPhone 6s Plus, iOS 9.2.1, PM version 0.3.0

Holding down the delete key for extended period has unexpected results.

Expected result:
Characters begin deleting 1 by 1, slowly. Character deletion speed increases, still 1 by 1. Entire words are deleted until button is released. 

Actual result:
Characters begin deleting 1 by 1, slowly. Character deletion speed increases, still 1 by 1. Deleting slows back down even slower than at first, and remains that way 1 by 1 character.

Possibly related:  https://github.com/ProseMirror/prosemirror/issues/25

**Comment by marijnh** [comment]
I can reproduce this. These end up being handled though key bindings (as opposed to composition events, which is what Android Chrome creates on backspace), and at some point, the keydown events just start coming in more slowly. 

What appears to be happening is that the fact that ProseMirror prevents the event's default behavior somehow triggers iOS/Safari into slowing down the events. I can reproduce the same behavior with this little piece of HTML (no ProseMirror).

```html
<!doctype html>
<textarea>some editable text</textarea>
<script>
document.querySelector("textarea").addEventListener("keydown", function(e) {
  console.log("EVENT")
  e.preventDefault() 
})
</script>
```

So that's just one more item to add to the list of weird Mobile Safari behaviors. Handling key events is what ProseMirror does. If that causes the browser to do silly things, I'm not sure there's much we can do about that (sometimes there are workarounds, but finding them is the hard part -- I couldn't find anyone talking about this issue online).

**Comment by nickvelloff** [comment]
@marijnh Not the worst weird behavior, likely low priority. Maybe file under _more of a Safari bug_. Bigger fish to fry. Thanks for looking :+1:

**Comment by marijnh** [comment]
This seems to work again, now that we let backspace through unobstructed.
