### ISSUE TITLE
iOS - Sticky toolbar does not stick

### ISSUE THREAD

**Issue by nickvelloff** [ProseMirror/prosemirror#223]
iPhone 6s Plus, iOS 9.2.1, PM version 0.4.0

Expected result:
Toolbar stays visible and fixed upon scrolling.

Actual result:
Toolbar becomes invisible and blinks off and on upon scrolling.

![ed-bug-scroll-2](https://cloud.githubusercontent.com/assets/885369/13337878/df24c622-dbd2-11e5-9113-617bf40471cb.gif)

**Comment by marijnh** [comment]
Safari is the new IE, as they say.

One problem here is that my scroll handler (which determines when menubar is leaving the viewport and should be floated) is only called after the whole scroll finishes, rather than, as it is on desktop browsers, repeatedly during scrolling. So it can't really do its job in this case.

But sometimes the bar ends up in a bogus position (200-500 pixels above the viewport), even after scrolling has finished. Its css says `position: fixed` and `top: 0` in this case, so that's just Safari being broken about positioning.

I think these are bad enough to recommend not enabling a floating menubar on mobile Safari. I could find lots of talk about these issues online, but no workaround — the general recommendation was not to rely on position: fixed in Mobile Safari.

**Comment by nickvelloff** [comment]
@marijnh Thanks for looking into it. We were hoping we could perhaps use it in a version 1 but it looks like we will need to take it all the way to a native toolbar out of the gate.

**Comment by forresto** [comment]
The workaround :see_no_evil: seems to be doing a manual `fixed` implementation with debounced scroll event and absolute positioning. It isn't pretty, but the native tooltip is even less workaroundable.

I could try to make a PR to move my fix upstream. Should it sniff mobile safari?

**Comment by marijnh** [comment]
Don't debounced scroll events produce a very noticeable and annoying jittering of the positioned element? Especially on mobile, where scroll events arent fired immediately, the thing will be scrolled far out of view and then snap back.

**Comment by forresto** [comment]
You're right, that debounce was premature optimization. It's smoother and better without. Still a bit jittery.

**Comment by marijnh** [comment]
I am surprised you're able to get anywhere near smooth with that technique. But if you can turn it into a relatively functional fallback that the module uses on iOS, I'd definitely be interested in a patch.

**Comment by nickvelloff** [comment]
@marijnh - we hacked in a solution that really does not work very well. We will go native toolbar on this for the time being.

**Comment by marijnh** [comment]
Moved to https://github.com/ProseMirror/prosemirror-menu/issues/3
