### ISSUE TITLE
Node selections aren't set when clicking around document quickly

### ISSUE THREAD

**Issue by ericandrewlewis** [ProseMirror/prosemirror#229]
Our mousedown handler [respects doubleclick events](https://github.com/ProseMirror/prosemirror/blob/d293d71e1344de873b5d5f6ef00a3ec4b883ed62/src/edit/input.js#L198), and lets browsers natively handle this behavior.

Quickly clicking around the editor causes this logic to kick in, a node selection may not be made when it should be (see [screencast](https://www.youtube.com/watch?v=SVd_0wAYYQk&feature=youtu.be)).

**Comment by ericandrewlewis** [comment]
What is the situation where we want to leave the browser to handle the event? When the double click is on the same element?

**Comment by marijnh** [comment]
Are you talking about clicking on one element and then quickly on another? Ideally, we'd have the same concept of a double click as the browser, but since those are opaque, and in some cases configurable, we'll have to make do with an approximation (we can't wait for the dblclick event, since that only happens _after_ mousedown).

Moving our approximation closer to what browsers do, for example by not treating clicks a certain distance apart as double/triple clicks, would be a good thing.

**Comment by ericandrewlewis** [comment]
> Are you talking about clicking on one element and then quickly on another?

Yep, that's the behavior.

> Moving our approximation closer to what browsers do, for example by not treating clicks a certain distance apart as double/triple clicks, would be a good thing.

This sounds great. I'm going to mark this with the "starter" label as it seems self-contained and small change.
