### ISSUE TITLE
structural ideas from implementing recently

### ISSUE THREAD

**Issue by ianstormtaylor** [ProseMirror/prosemirror#241]
Hey, just wanted to start by saying thank you for this library. It's seriously awesome. I'm currently working on a concept for a realtime collaborative CMS-like system, and ProseMirror seems to be exactly what I need. 

I've been implementing it over the past week or so, running into different little things as I go, and had a recent though about architecture. I'm not sure if this is the kind of discussion you want to have, but figured I'd write it up in case it's useful at all, from someone who had a big learning curve recently.

Thanks!

So the idea... (There's a big chance I don't know what I'm talking about, and missed something obvious, if so let me know!) 

It seems like the way the codebase is currently architected, a lot of the defaults are hard to override and customize without having to re-roll your own in big ways. (It's also complicated to find out where things are defined in the first place, for the same architectural reasons, I think.)

Right now the system seems to be defined like this:

```
editor
↳ menu
  ↳ inline content
    ↳ menu group(s)/items(s)
  ↳ block content
    ↳ menu group(s)/item(s)
↳ input rules

base commands
↳ key bindings
↳ menu item
  ↳ menu group

schema
↳ commands
  ↳ key bindings
  ↳ menu item
    ↳ menu group
↳ input rules

auto input rules
↳ input rules
```

The biggest surprise I found was `menu items` and `key bindings` were defined directly on `commands`, and that then `commands` were defined directly on `schemas`. Whereas, for flexibility, it seems like the relationship should be defined the other way around for re-use sake.

What seems like it would make more sense is:

```
editor 
↳ schema
↳ commands
↳ key bindings
↳ input rules
↳ menu
  ↳ group(s)/item(s)
```

That kind of structure would allow us to build up editors from their logical parts a bit easier I think. In pseudo-code it might look like:

```js
const strongMarkCommand = new Command({
  name: 'toggle-strong-mark',
  mark: StrongMark,
})

const strongMarkKeyBinding = new KeyBinding({
  command: 'toggle-strong-mark',
  keys: ['Mod-B'],
})

const strongMarkMenuItem = new MenuItem({
  label: `Bold (${resolveShortcut('Mod-B')})`,
  command: 'toggle-strong-mark',
  element: createIcon({
    width: 805, height: 1024,
    path: '...',
  }
})

const inlineMenuGroup = new MenuGroup({
  items: [
    strongMarkMenuItem,
    ...
  ]
})

const editor = new ProseMirror({
  commands: [
    strongMarkCommand,
    ...
  ],
  keyBindings: [
    strongMarkKeyBinding,
    ...
  ],
  menu: [
    strongMarkMenuItem,
    ...
  ]
})
```

Which affords complete control. Of course we still want to have the easy default behavior that we currently have. But I think structured like this the default behavior is even more obvious (and potentially more file-size-saving when customized), since each type would be implemented across a series of files:

```
src/
  commands/
    delete-selection.js
    toggle-strong-mark.js
    toggle-em-mark.js
    ...
    index.js
  input-rules/
    em-dash.js
    open-double-quote.js
    start-ordered-list.js
    ...
    index.js
  key-bindings/
    delete-selection.js
    toggle-strong-mark.js
    ...
    index.js
```

Such that implementing the default behavior is as easy as mixing in:

```js
import ProseMirror from 'prosemirror'
import defaultCommands from './commands'
import defaultKeyBindings from './key-bindings'
import defaultMenuItems from './menu-items'

function ProseMirror ({
  commands = [],
  defaults = true,
  keyBindings = [],
  menuItems = [],
}) {
  if (defaults) {
    commands = [ ...defaultCommands, ...commands ]
    keyBindings = [ ...defaultKeyBindings, ...keyBindings ]
    menuItems = [ ...defaultMenuItems, ...menuItems ]
  }

  ...
}
```

But it affords a ton more flexibility (and readability) to customizing the editor. For example, maintaining all of the default commands while picking and choosing certain key bindings or menu items could be easy:

```js
import ProseMirror from 'prosemirror'

new ProseMirror({
  defaults: true,
  keyBindings: [
    myKeyBinding
  ],
  menuItems: [
    myMenuItem
  ]
})
```

Or if you want to completely customize everything:

```js
import ProseMirror from 'prosemirror'
import commands from 'prosemirror/commands'
import deleteSelection from 'prosemirror/key-bindings/delete-selection'
import strongMark from 'prosemirror/menu-items/strong-mark'
import emMark from 'prosemirror/menu-items/em-mark'

new ProseMirror({
  defaults: false,
  commands: defaults.commands,
  keyBindings: [
    deleteSelection,
    ...
    myKeyBinding
  ],
  menuItems: [
    strongMark,
    emMark,
    ...
    myMenuItem
  ]
})
```

Or even imagine easily just overriding a single command to tweak behavior (for things like needing to customize how pressing `enter` in a list item for work instance, etc.):

```js
import ProseMirror from 'prosemirror'
import commands from 'prosemirror/commands'

const editor = new Editor({
  commands: {
    ...commands,
    deleteSelection: myCustomDeleteSelection
  }
})
```

I know I definitely didn't cover all use cases there, and I simplified things like `inlineMenu` vs `blockMenu` and such, but hopefully it was enough to give the general idea. I think the base concepts of ProseMirror are absolutely awesome. Just that it gets bogged down in the current architecture a bit which makes customizing the commands, key bindings, menu items, and input rules a lot more complex than it needs to be. For the most part it boils down to just flipping the relationship, so that dependents are defined on their parents, but with a reference to their parent instead, such that they can be mixed in/out without needing to touch the parents.

Hopefully something in there was useful! Happy to discuss more.

**Comment by kiejo** [comment]
I like these suggestions as I've recently run into similar problems when trying to customize the default editor behavior. These were the challenges I faced:
* Changing or disabling the key bindings of a default command
* Changing the behavior of a default command
* Disabling a default input rule
* Customizing the menu

I got most of these things working without any hacks, but achieving this and understanding the overall structure felt more complicated than it should be.

I can imagine that some decisions of the current architecture are based on the goal that commands, key bindings, input rules, and menu items should dynamically adapt to the used schema and that a schema should come with these behaviors included. It also allows easy mixing of node types from different schemas into a new schema while automatically ending up with all the available commands, menu items, key bindings, and input rules.

The idea behind your suggested architecture makes sense to me and was easier for me to grasp than the current one, which is why I like it. And having the option of turning off all defaults is a good idea, as this would make customization easier. At the same time this approach would probably require more manual work of putting all the available commands, menu items, input rules, and key bindings together when combining nodes from different schemas. To make this "mixing and matching" of node types easier, one idea could be to put these things on the node level:
```javascript
class MyInlineNode extends Inline {
  static get commands() { return [] }
  static get inputRules() { return [] }
  static get keyBindings() { return [] }
  static get menuItems() { return [] }
}
```
Now if we wanted to reuse this node type, but needed to customize for example some of the key bindings, we could do:
```javascript
const schemaSpec = defaultSchema.spec.update({
  my_inline: class extends MyInlineNode {
    static get keyBindings() { return [/* custom key bindings */] }
  }
});
```

Instead of the static getters, we could probably use the already existing schema registry, but I haven't looked into this more closely yet.

Overall, I think that the most important change to improve customizability would be a clear separation of commands, key bindings, menu items, and input rules and allowing to mix and match these types. An easy way to turn off the defaults would also be very helpful.

**Comment by marijnh** [comment]
> I can imagine that some decisions of the current architecture are based on the goal that commands, key bindings, input rules, and menu items should dynamically adapt to the used schema and that a schema should come with these behaviors included.

Yes, this is exactly the reasoning behind it. (I.e. it is trying to make schema elements easy to _compose_.)

I think @ianstormtaylor 's concerns largely overlap with @kiejo 's, who was more successful at expressing them in a succinct way, so I'll respond to those. The main mechanism for customizing these is the [`commands` option](http://prosemirror.net/ref.html#commands). It defaults to `CommandSet.default`, but you can call further methods on that, or start from `CommandSet.empty`, to influence your commands

> * Changing or disabling the key bindings of a default command

This is how you change the default binding for 'make paragraph' to `Ctrl-O`:

    commands: CommandSet.default.update({"paragraph:make": {keys: ["Ctrl-O"]}})

You can similarly set `keys` to null to remove its default keybindings.

> * Changing the behavior of a default command

You can replace a command with:

    commands: CommandSet.default.update({deleteSelection: {/* your implementation */}})

If your updated value has a `run` property, it'll completely replace the old implementation. You _will_ have to re-add any key bindings and menu group entries, but that mostly makes sense if you redefine the command. Or alternatively, you can base your new implementation on `baseCommands.deleteSelection` by inheriting (via `Object.create`) from that.

The idea is that you can group reconfigurations (such as a new key map) into an object, and pass those to `CommandSet.update` to include them in your editor.

> * Disabling a default input rule

The `autoInput` option follows a similar system, though it is currently somewhat cruder. You'd do:

    autoInput: ["schema", autoInputRules, {emDash: null}]

.. to remove the `emDash` rule.

> * Customizing the menu

You can go in two directions here, depending on your need. If you just want to slightly tweak the content of the menu, you can use the `commands` option to add and remove `menu` properties in a few commands. If you want full control, you bypass the command grouping entirely, build a menu out of individual `MenuCommand` instances, and pass that as content to your menu module.

(Closing this, since it is not really an issue, but rather a discussion -- next time, open those on the [forum](https://discuss.prosemirror.net/). Feel free to add more replies on this topic here.)

**Comment by kiejo** [comment]
Thanks for the write up. I didn't know about the CommandSet API and it certainly helped refactor some of my code. Would be nice to expose the autoInput configuration using an API more similar to CommandSet (having something like AutoInputRules.default.update), but that's not a high priority for me.

In regards to the menu I went with the second approach (custom MenuCommands) and it worked fairly well, it's just that it took me some time to grasp the concept. But we could probably make this easier by writing some example code and guides on this topic.

**Comment by ianstormtaylor** [comment]
+1 to that, I am also going with custom `MenuCommand` buttons, but it took me a while to figure out, and I had to read through the source to figure out the exact way to do it.

**Comment by marijnh** [comment]
>  But we could probably make this easier by writing some example code and guides on this topic.

Agreed. This is being tracked by https://github.com/ProseMirror/website/issues/21

**Comment by marijnh** [comment]
This ties into #305, but as I'm trying to come up with a concrete sketch of a less implicit API, I'm running into the reason why I made things this way in the first place: if you expose, for example, the set of available commands, as a plain value, that is indeed easier to understand. But that does mean that as soon as you tweak the schema by, for example, removing a node type, you need to remove a few commands related to that node type, and are forced to import and declare all the commands you _do_ need, manually. That's not an okay user experience.

The problem lies in the interconnectedness of commands, input rules, parsers, serializers, and so on, with nodes. If we want to make it possible to create custom schemas without immediately having to duplicate hundreds of lines of tying-things-together code, we will need some kind of implicit pulling in of elements. So the question is which is worse, magic or repetetive code.
