### ISSUE TITLE
Text cursor persists in sibling node when a contentless node is selected

### ISSUE THREAD

**Issue by ericandrewlewis** [ProseMirror/prosemirror#252]
When clicking to select a contentless node, the text cursor persists in the closest text node.

Here's [the example code](https://github.com/ericandrewlewis/prosemirror/commit/8c58063cf9110e1447a253dff0576535cbbbd691) I'm working with.

![text-cursor-persists-with-node-selection](https://cloud.githubusercontent.com/assets/1087646/13614586/40e543da-e53f-11e5-9021-0616d9c22457.gif)

**Comment by ericandrewlewis** [comment]
Can reproduce in OSX Chrome and Safari, can't reproduce in FF.

**Comment by marijnh** [comment]
The problem here and in #253 seems to be related to the browser refusing to set a selection around the non-editable block. When a node is selected, ProseMirror normally hides the selection (using CSS) and sets it to span the node. This to keep focus in the editor and to avoid problems with magic autoscrolling-selection-into-view moving the scroll position to the wrong place.

But it seems that there are cases where we can't have such a selection, or it is 'normalized' into an undesirable state. The eventual solution will probably be to create a temporary editable dummy node inside or near the selected node, and focus that. However, dumping random nodes into the content is tricky, due to contentEditable, our DOM parser, and our redraw algorithm, all potentially getting confused by such nodes.

The same solution that we'll need for #132 can probably apply here -- if we can robustly put nodes into our content, we can also create a mini selectable node that way. For this to work, we'll need a number of things, though. A data structure that the redraw algorithm is aware of that tells us which nodes are 'decorated'. A `decorate` method that adds something to this structure and marks the nodes leading up to the target node as dirty, so that they will be redrawn. And a way for the DOM parser to 'see through' such decorations.

In the meantime, we might be able to get away with a hack that places an absolutely positioned node at the end of the content, sets its `pm-ignore` attribute, and puts the focus in it. I'll see if I have time to create such a kludge later today.

**Comment by marijnh** [comment]
Attached patch solves this by leaving `contentEditable` on for leaf nodes. That is a risky choice in itself, but let's test and see whether it causes any problems that are hard to work around.
