### ISSUE TITLE
Demo in collaborative editing repeats keystrokes See SterDoc in demoPage

### ISSUE THREAD

**Issue by sterPap** [ProseMirror/prosemirror#303]
For some reason this (maybe after inserting a note) gets crazy and repeats what you type for ever. Stops only after reloading the page. 

See SterDoc in demoPage.

**Comment by marijnh** [comment]
Thanks for reporting that! It _seems_ to have been caused by client crashes due to the demo that handled comments code not having been entirely updated for recent API changes. I've updated the live demo, but I had to wipe the documents because they were all corrupted by these crashes. I added a bunch of comments and could no longer reproduce this issue. If you do still observe it, let me know.
