### ISSUE TITLE
export fromJSON and toJSON as a functions

### ISSUE THREAD

**Issue by ericandrewlewis** [ProseMirror/prosemirror#349]
Functions to transform from one format to another are exported by the format module. e.g. `fromDOM` creates a PM doc from a DOM node, `toText` creates a plain text string from a PM doc, etc.

JSON is also target format, but the API is a bit different. One would call `Node.toJSON()` and `Node.fromJSON()`. We could move the function `fromJSON()` and `toJSON()` from the `Node` class to the format module, to give this functionality an expectable location and use a similar API convention.

**Comment by marijnh** [comment]
There are a number of other types (`Step`, `Mark`, `Fragment`, probably more) that all follow the same `static fromJSON` / `toJSON` convention, so I think the existing location is consistent enough, and there's no need to put these in the `format` module (which otherwise has nothing to do with JSON).
