### ISSUE TITLE
Keep inline styles when pasting

### ISSUE THREAD

**Issue by iliaznk** [ProseMirror/prosemirror#36]
Not quite an issue, but a question. I'd like to have an option of keeping all (or some) inline styles when pasting formatted text from a web page. Or how do I allow any arbitrary attributes in HTML doc? What would be the easiest way to achieve that?

**Comment by marijnh** [comment]
Yes, this is probably a good idea. The `convert/from_dom` module could add some logic to spot and properly interpret these pretty easily, but I think I'll hold off on that for now since that module will have to be overhauled to properly work with modular document schemas anyway (so that it can parse user-defined node types and attributes), and this will probably be easier to do after that overhaul. I'm leaving this open and keeping it in mind for the future.

**Comment by iliaznk** [comment]
Thanks!

**Comment by yoshokatana** [comment]
Note for the future:

Microsoft Word, Apple Pages, and Google Docs all use relatively standardized markup (bold, italic, links, etc are regular tags), but there are some inconsistencies in text that is underlined, strikethrough'd (striked-through?), and other less-common styles.

Other text editors vary on how standardized their markup is, with OSX's TextEdit one of the worst offenders (everything seems to be spans referencing inline style blocks in the document).

**Comment by marijnh** [comment]
The DOM parser has supported matching on styles for a while now (the `matchDOMStyle` property in the current master branch), and the built-in strong and emphasis marks have handlers for `font-weight` and `font-style` attached.
