### ISSUE TITLE
Define clear behavior for the default list node types

### ISSUE THREAD

**Issue by marijnh** [ProseMirror/prosemirror#363]
Right now list items accept any kind of block as child, but the commands defined on them try to enforce some structure. You can, however, still get out of that structure by using other editing primitives. This is a mess. We should either go back to whatever-you-want list forms, or encode some constraints in the schema itself (maybe that the first child of a list item should always be a plain paragraph), and base the relevant commands (wrap-in-list, lift/sink-list-item) preserve that.

**Comment by kiejo** [comment]
I think it's important to define the goal of the default schema. Should it provide maximum flexibility or should it cover the 90% use case with some nice default behaviors. I prefer the more restrictive approach as it could potentially provide a better user experience for the majority of use cases even if this means giving up some flexibility.
With the coming changes in ProseMirror 0.8.0 it looks like defining custom schemas will be even better and more user friendly so it will be easier to create more powerful/flexible schemas on top of a basic more restrictive one.

I've been thinking about this quite a bit and for the kind of text editing which should cover the 90% use case, I came up with a more restrictive schema that would look like the following:
```javascript
{
    bullet_list: {type: BulletList, content: 'list_item+', group: 'block'},
    ordered_list: {type: OrderedList, content: 'list_item+', group: 'block'},
    list_item: {type: ListItem, content: 'paragraph (bullet_list | ordered_list)?'},
}
```

At first this might look a little bit too restrictive, but I think it covers the majority of use cases very well and would work similarly to what is available in other rich text editors.
Here are some thoughts on the suggested schema:
* I think that only allowing a single paragraph makes sense as pressing `Enter` is commonly used to create a new list item instead of splitting the paragraph into two. In cases where the user really wants to split the text, creating a hard break is still possible using `Shift+Enter`. It would also make sense for `Backspace` to form the inverse of `Enter` in the list item case, which would be nicely supported by this schema.
* A common use case is to turn multiple existing paragraphs into a list. In this case the user usually expects each paragraph to result in a list item instead of a single list item with multiple paragraphs. This would be well supported by the suggested schema.
* The other available default block types besides paragraph (blockquote, horizontal_rule, heading, code_block) mainly make sense at the document top level in most cases. Uses cases where you would want to put them (probably along with additional content) into some kind of list structure might be better handled with a table.
* We encountered quite some use cases where it makes sense to put ordered lists inside bullet lists and the other way around. Being able to type `1. ` at the beginning of a bullet item to turn its parent into an ordered list could be an intuitive way to allow the creation of such mixed lists. The suggested schema would allow this structure.
* As paragraphs can contain any inline content, list items would still support more advanced types of content (e.g. images in the default schema) as long as they are inline.

Additional things which I have been thinking about in terms of improving the UX when working with lists:
* Creating a new list directly below/above an existing list of the same type should automatically join it with the list above/below. Otherwise it looks like a single list, but does not behave that way, which makes it look like a bug when trying to use commands like `sink`.
* It would be nice if the `sink` command would work on paragraphs and turn them into a list of list items. This would basically mean using the same key command for `list:wrap` as for `sink`. This key command would make it consistently work as the inverse of a `lift` which does work on top level list items.

That's the way I currently see it and I think this would be a nice default schema for lists. Would be great to get some feedback on this. Did I miss any common use cases which could not be handled by the schema?

**Comment by marijnh** [comment]
> I think it's important to define the goal of the default schema.

Agreed. I'm leaning more and more towards 'an example to get people started, and maybe some useful node/mark type classes to reuse in other schemas'. I imagine every single (halfway serious) use of ProseMirror will want to tweak their schema in some way.

I don't think `"paragraph (ordered_list | bullet_list)?"` is general enough for a default schema. There's many examples of people writing non-trivial prose (including multiple paragraphs, even blockquotes or figures) inside of a single list item. I'm working on making the default lists have `"paragraph block*"` as their content expression. The list item lift/raise/etc commands are quite straightforward to define for this.

Again, that's just the default (/example) schema. Feel entirely free to do your own thing without worrying about that it is doing.

> A common use case is to turn multiple existing paragraphs into a list. In this case the user usually expects each paragraph to result in a list item instead of a single list item with multiple paragraphs. This would be well supported by the suggested schema.

Um, sure, but it's also very well supported by the existing default wrap commands.

> Creating a new list directly below/above an existing list of the same type should automatically join it with the list above/below

I am undecided about this. It (along with making any other command that can lead to two adjacent lists join them) would give the user an easier mental model to work with, but also means that *if* you want, for example, two adjacent ordered lists, you can't make them.
> It would be nice if the sink command would work on paragraphs and turn them into a list of list items. 

What kind of list? Or maybe a blockquote? If you have a list type in your schema that you consider the preferred type, it's easy to make such a keybinding.

In general, I'm tempted to just leave all of these decisions to client code. There is no behavior that'll please everybody, and I prefer working on the core to having discussions about these kind of details.

**Comment by marijnh** [comment]
Patch 9118456991408 implements this.

**Comment by kiejo** [comment]
> Agreed. I'm leaning more and more towards 'an example to get people started, and maybe some useful node/mark type classes to reuse in other schemas'.

I think this is a good approach and fits very nicely with ProseMirror's powerful schema system.

> I'm working on making the default lists have "paragraph block*" as their content expression. The list item lift/raise/etc commands are quite straightforward to define for this.

Sounds good! This should cover most use cases and will serve as a solid example for people to build upon.

> In general, I'm tempted to just leave all of these decisions to client code. There is no behavior that'll please everybody, and I prefer working on the core to having discussions about these kind of details.

You're probably right that it will be impossible to please everybody, which makes having the default schema simply serve as an example a fitting goal for ProseMirror.

I'm already looking forward to the next release as I saw some changes which should make it much easier to structure and organize custom schema code :) Great work!
