### ISSUE TITLE
Pasting removes list item

### ISSUE THREAD

**Issue by bZichett** [ProseMirror/prosemirror#397]
Kind of self-explanatory but a quick two image demonstration:

![1](http://i.imgur.com/Z5xmYLr.png)

When caret is inside the list item node, ctrl+v inserts the text but removes the bullet.  This only happens when there is no text content other than what's being pasted in.

![2](http://i.imgur.com/ZzhXr6Z.png)

**Comment by kiejo** [comment]
The same behavior occurs when pasting into an empty heading or an empty block quote. I think this behavior is the result of an overall improvement in copy/paste handling in the latest version. But I agree, that the current behavior does not feel right yet.

I thought about a more "predictable/expected" (from a user perspective) approach and also looked at how other editors handle these cases. This a possible solution I came up with:
* When pasting inline nodes, the destination's node type should not be changed (regardless of whether it is empty or not). The pasted content should be merged into the destination's content.
* When pasting a block type node (e.g. BulletList, Heading) into an empty Paragraph, the paragraph should be overridden with the pasted node. This should not change the paragraph's parent node.
* When pasting a block type node into another block type node, the destination's node type should be kept and the pasted content should be merged into the destination's content (regardless of whether it is empty or not). If this is not possible, the pasted content should be inserted at the position of the destination node and the destination node should be moved below the pasted content.

I think the important thing here is the special handling of empty paragraphs. To turn this into a more general solution, which does not depend on the paragraph node, we could add a new customizable property to a node, which tells ProseMirror whether to try to keep the node type when pasting into it when it's empty.

There are probably more edge cases especially with the schema constraints, but I think the easiest and biggest improvement would be to handle the empty paragraph in a special way and not use the same behavior when pasting into an empty ListItem, Heading, Blockquote, etc.

**Comment by marijnh** [comment]
Another symptom of this is #427. I'm going to need a more clever 'negotiation' between the content that's being inserted and the empty nodes around the selection — it's a bit of a chicken-egg problem in that the context is needed to drive the way the pasted HTML is parsed, yet the pasted content also influences how much context around the cursor is replaced. I didn't make much progress the last time I attacked it, but I will try again.

**Comment by kiejo** [comment]
Thanks for the details! It sounds like a rather hard problem to solve, but it would be great to get an update on this issue. It's currently one of the biggest UX issues we face with ProseMirror, but I have no idea on how to work around it or how to solve it :/
Is this a longer term issue that depends on other big changes in the system or is it something that might get fixed in one of the next releases? If it's longer term, do you have ideas on how one could work around this issue now?

**Comment by marijnh** [comment]
> but I have no idea on how to work around it or how to solve it

Me neither! This isn't something that depends on other work, but it is something that I'll have to sink a bunch of time into, since no easy solution seems forthcoming. As such, it'll have to wait until I have this time.

The only workaround that might be viable is to add your own special-cased handlers using `handleDOMEvent`, which detect specific circumstances and override the default behavior. But that's still likely to be awkward and error-prone.

If anyone knows of any (documented) previous work that describes approaches to this problem (the placing of inserted/pasted content in a tree structure), I'd be very interested.

**Comment by kiejo** [comment]
Thanks for the update! I'll see if I can get something working with some special-cased handlers in the meantime and keep you posted if I find something that could help solve the actual problem.

**Comment by marijnh** [comment]
Started a discussion on [the forum](https://discuss.prosemirror.net/t/paste-behavior-research/469)

**Comment by marijnh** [comment]
This should be much better in 0.13.0. Please open specific issues for further problems.
