### ISSUE TITLE
Hard line break at end of markdown is converted to backslash

### ISSUE THREAD

**Issue by patternseek** [ProseMirror/prosemirror#446]
If you pass "a\\\n" as markdown to the editor then export the editor's content back to markdown you end up with "a\\\\", which renders as "a\".

Here's a gif showing the behaviour in the markdown demo:
http://imgur.com/a/Ry2Gc

**Comment by marijnh** [comment]
I'm going to assume that you mean `"a\\\n"` (i.e. a, backslash, newline), since `"a\\n"` does not get converted to `"a\\"`.

If you were expecting a hard break, CommonMark doesn't seem to allow those at the end of a paragraph (see [here](http://spec.commonmark.org/0.26/#example-610)). So the current behavior seems sensible.

**Comment by patternseek** [comment]
Did you have a look at the gif I linked? Basically the issue is that the editor is leaking an escape when switching back and forth between importing and exporting Markdown.

**Comment by marijnh** [comment]
I see. Would you prefer for the hard break to be dropped entirely?

**Comment by patternseek** [comment]
If a trailing hard break is incompatible with valid Markdown then I suppose yes.

**Comment by patternseek** [comment]
Thanks!
