### ISSUE TITLE
Deregister items from the menubar

### ISSUE THREAD

**Issue by arekkas** [ProseMirror/prosemirror#46]
I haven't found a way to remove buttons or functionality from the toolbar. I think `menu/items.js` should export `deregisterItem()`:

```js
export function deregisterItem(tag, item) {
  (tags[tag] || (tags[tag] = []));
  let index = tags[tag].indexOf(item);
  if (index > -1) {
    tags[tag].splice(index, 1);
  }
}
```

**Comment by arekkas** [comment]
Functionality (removing blockquotes, images, ...) should also be disableable completely. Not sure if that is supported yet.

**Comment by marijnh** [comment]
This isn't supported yet. I'm going to somehow tie the way the system finds available menu items to the schema system (since most menu items only make sense if your schema supports certain kinds of nodes/features), so this is about to change anyway. I'll probably make it easier to specify your own explicit list of items as well -- having a sensible default is good, but people will want to customize this.

**Comment by arekkas** [comment]
:100:

**Comment by marijnh** [comment]
You can now

 - Specify specific items to use in your menu

or

 - Adjust the `menu` properties of specific command specs to change the way they appear in the menu

**Comment by maxnowack** [comment]
@marijnh have you an example how to do that? I can't find it in the documentation ...

**Comment by marijnh** [comment]
Something like (in your options)

```
  commands: CommandSet.default.update({selectParentNode: {menu: null}})
```

... would remove the `selectParentNode` command from the menu.
