### ISSUE TITLE
'toggleMark' fails when selection is empty on iOS/Android

### ISSUE THREAD

**Issue by owjsub** [ProseMirror/prosemirror#462]
When selection is empty, toggleMark has no effect on iOS Safari and Android Chrome with http://prosemirror.net/demo/basic.html.
[![https://gyazo.com/4eec91da8296507e7af59629d7734b01](https://i.gyazo.com/4eec91da8296507e7af59629d7734b01.gif)](https://gyazo.com/4eec91da8296507e7af59629d7734b01)

**Comment by marijnh** [comment]
This seems to work on iOS now, but Android still has problems. Because text input is modeled as composition, and the composition will only finish once the current word is committed, and we can't touch the DOM in the meantime or we'll reset the composition, the text will appear with the wrong style initially, and then only get the proper style when committed.

**Comment by marijnh** [comment]
With attached patch, compositions are immediately force-flushed when there are pending marks. This slightly interferes with expected composition behavior, but is a lot better than the thing it did before.
