### ISSUE TITLE
Inconsistent list item deletion join on Android

### ISSUE THREAD

**Issue by owjsub** [ProseMirror/prosemirror#464]
| iOS Safari / Mac Chrome | Android Chrome |
| --- | :-: |
| [![https://gyazo.com/6b66412824373a71d3781d506a72088d](https://i.gyazo.com/6b66412824373a71d3781d506a72088d.gif)](https://gyazo.com/6b66412824373a71d3781d506a72088d) | [![https://gyazo.com/1ec6050ffaffd99b11e8037aacb84095](https://i.gyazo.com/1ec6050ffaffd99b11e8037aacb84095.gif)](https://gyazo.com/1ec6050ffaffd99b11e8037aacb84095) |

ref: http://prosemirror.net/demo/basic.html

**Comment by marijnh** [comment]
Chrome Android doesn't fire any meaningful key event for backspace, so at the moment ProseMirror is not able to even know that backspace was pressed. Thus, you get the native backspace behavior instead of the one defined by the editor.

One possible (kludgey) solution would be to detect DOM mutations that sort of look like they might have been caused by backspace, and have the editor dispatch a backspace key event to itself in that case. We're already doing that for enter, so I guess it'd make sense here too.

**Comment by marijnh** [comment]
Attached patch implements this. You still see a brief flash of the wrong behavior as the browser does its thing, which is unfortunately hard to avoid, since we can only observe what happened after it happened, but it then reverts the correct behavior.
