### ISSUE TITLE
event.code cannot be trusted in every language

### ISSUE THREAD

**Issue by kapouer** [ProseMirror/prosemirror#471]
This:
https://github.com/ProseMirror/prosemirror-keymap/blob/647d563/src/keymap.js#L104
does not return the right key names for azerty keyboards on chromium 53 and firefox 45.

For example it returns "KeyQ" when i type "a".

prosemirror 0.10 did not have that problem because `event.code` wasn't used at all.

**Comment by marijnh** [comment]
Hm, what a mess. `KeyboardEvent.key` can't be robustly emulated on browsers that don't support it, and `.code` is not usable for the reason you describe. So I guess the fancy new key event properties are pretty much useless for this kind of use case, and we'll have to work with out own crummy custom key names after all. I'll give this some more thought soon.

**Comment by marijnh** [comment]
On closer look, I think the current behavior is appropriate. If you want to react to a given character being typed, bind `"'a'"` (the character with single quotes around it). If you want to react to a given _key_, as in a physical key on the keyboard, use the key name.

**Comment by kapouer** [comment]
Okay, "Ctrl-KeyZ", the binding for "undo", should then be "Ctrl-'z'" ?
What's the point of having "KeyZ" syntax, then ?

**Comment by marijnh** [comment]
So, unfortunately, you can't bind `Ctrl-'z'`, because browsers don't attach a `ctrlKey` property to keypress events. That is indeed an issue.

> What's the point of having "KeyZ" syntax, then ?

Being able to refer to the actual Z key on the keyboard.

**Comment by kapouer** [comment]
Here's hopefully some specs to lift the confusion: https://www.w3.org/TR/2015/WD-DOM-Level-3-Events-code-20150428/
> 'KeyZ'	0x1d	z on a US keyboard. Labelled w on an AZERTY (e.g., French) keyboard, and y on a QWERTZ (e.g., German) keyboard.

**Comment by marijnh** [comment]
The problem with these specs is that browsers aren't really implementing them all that quickly. The only relatively reliable and widely supported property on keydown events (the one where we have access to modifiers) is `keyCode`. I assumed the `code` property would be a more-standardized, easier-to-use form of that, but as you indicated, it has this physical-key property, making it impractical.

So I guess we have to go back to building something custom on top of `keyCode`, which is a shame, because I'd like to be able to build on something standardized...

**Comment by marijnh** [comment]
Okay, it seems we can do a halfway decent job of emulating `KeyboardEvent.key` which, combined with the fact that many browsers support it natively, should be good enough to use that. Attached patch implements this. It changes the interface of the module somewhat, and isn't entirely ideal — binding something like `Shift-1` now looks like `!`, because we are dispatching on the actual character produced, and on many keyboards Shift-1 won't actually produce an exclamation point. But I think adding multiple 'modes' of binding keys (by code or by name) is too much complexity.
