### ISSUE TITLE
Deleting content-constrained nodes with backspace/delete often doesn't work

### ISSUE THREAD

**Issue by marijnh** [ProseMirror/prosemirror#485]
If you have a figure with a caption or a table, pressing delete before it or backspace after it will not delete the node, since the delete algorithm sees the textblocks inside of the node, and will try to 'join' those with the focused textblock, which will fail due to schema constraints.

We could probably simply make backspace/delete kill the whole next node when joining fails. Or is that unexpected too?

**Comment by johanneswilm** [comment]
If we assume that the figure/table is a block node, so that the caret is at the start of the following block node (paragraph/ headline, etc.), then this may end up being a little unexpected for the user who possibly didn't realize what was about to happen.

At one point, there was a draft specification for how backspace and delete should work in browsers, that went something like below. I liked the proposal at the time, but I haven't tested what it would feel like to work like this in practice.

Collapsed selection
=======
**simple/Inline elements:** Delete when one delete/backspace is hit.

**complex/block level elements:** The selection is extended to cover the complex/block level element.

Non-collapsed selection
=======
The contents of the selection are deleted.

**Comment by ericandrewlewis** [comment]
I [recorded the delete table flows](https://cloudup.com/c-HyQHXas-I) in Microsoft Word and Google Docs in case they expose any desirable user experiences. 

> We could probably simply make backspace/delete kill the whole next node when joining fails. Or is that unexpected too?

Pressing backspace when joining fails might be a nice experience. Deleting a table in existing text editors is cumbersome — you either have to select all the table cells and delete as in Word, or delete it explicitly from a right click menu as in Google Docs (whoof). If a user does it by accident they can always undo, and hopefully get habituated to this easier path for deleting entire nodes like this.

**Comment by marijnh** [comment]
Attached patch makes the relevant commands, when they can't do anything else, fall back to selecting the node in the direction in which they were trying to delete. You can then press backspace/delete again to delete it.

Could you take a look and see how this feels?

**Comment by kiejo** [comment]
> Deleting a table in existing text editors is cumbersome — you either have to select all the table cells and delete as in Word, or delete it explicitly from a right click menu as in Google Docs (whoof).

I think that somehow being able to delete a table by selecting all cells and pressing backspace/delete should definitely be possible (depending on the size of the table it's not that cumbersome). I commented on this in #484. I'm not saying that this should be the only way to delete the table, but that it's probably expected by many users.

> Attached patch makes the relevant commands, when they can't do anything else, fall back to selecting the node in the direction in which they were trying to delete.

This sounds really good!

Nevertheless, I would still make pressing delete inside an empty text block delete the text block instead of performing a join (I commented on this in #484). I'm mentioning this here as it ties into the overall user experience when talking about the deletion of block type nodes.

**Comment by marijnh** [comment]
> I think that somehow being able to delete a table by selecting all cells and pressing backspace/delete should definitely be possible

I've adjusted the logic for deletion to make this work (it'll delete completely covered parent nodes that aren't allowed to be empty as well).
