### ISSUE TITLE
get a copy of orderedMap, and update() behavior

### ISSUE THREAD

**Issue by kapouer** [ProseMirror/prosemirror#501]
Hi,
i'm trying to copy an orderedMap (a spec.nodes map) - which made me try

    var specnc = spec.nodes.update();

Unfortunately, this appends undefined key/val to the map.

**Comment by rafbm** [comment]
Since `OrderedMap` is a [persistent data structure](https://en.wikipedia.org/wiki/Persistent_data_structure), there shouldn’t be a use case for cloning / copying one. It is **immutable**, so as soon as you call one of its methods (eg. setting / removing a value) a new map will be returned, leaving the previous version untouched. Thus, feel free to:

```javascript
var specnc = spec.nodes
```

Then use `specnc` as you will and rest assured `spec.nodes` won’t be affected.

That said, if you know what you are doing and _really_ want to create a distinct `OrderedMap` with the same data, this seems to be the current way:

```javascript
// Create a plain object and copy all key / values from `spec.nodes`.
var obj = {}
spec.nodes.forEach(function(key, value) { obj[key] = value })

// Create a new OrderedMap from this object.
var specnc = OrderedMap.from(obj)
```

**Comment by marijnh** [comment]
Indeed, this isn't something that you'd ever need, @rafbm explained it well.

**Comment by kapouer** [comment]
Hey, that's so obvious now, thank you for the explanation.
