### ISSUE TITLE
"dragend" does not fire when escape is hit

### ISSUE THREAD

**Issue by wes-r** [ProseMirror/prosemirror#509]
Hitting the escape key while dragging can result in a lingering drop-cursor, furthermore it appears the dragend event is not firing. https://developer.mozilla.org/en-US/docs/Web/Events/dragend claims it should fire on escape. Not sure how ProseMirror could be impacting this.

Tested on a Mac with:
Chrome Version 54
Firefox 50.0.2
Safari 10.0

Steps to reproduce (may take a couple of tries - on the order of 3):
* Go to http://prosemirror.net/demo/basic.html
* Drag some text and see the drop-cursor
* Hit escape to cancel the drag&drop
* drop-cursor remains!

**Comment by marijnh** [comment]
It seems that when you abort with esc, a dragleave is (at least on Chrome) only fired for the inner element that the drag was over, and since dragleave events don't have a `relatedTarget` property, there doesn't appear to be a good way to distinguish this event from a regular leave-on-inner-node-because-drag-moved-around event.

I've added a kludge to remove the drop cursor after a second of inactivity. If someone knows a better solution I'm definitely interested.

**Comment by wes-r** [comment]
Using a timeout in this way is the main solution I've come across :(

**Comment by tophf** [comment]
Chrome seems to set dragleave event's screenX and screenY to 0 when Escape was pressed.
