### ISSUE TITLE
JS Error on older Safari (parameter shadows function name)

### ISSUE THREAD

**Issue by wes-r** [ProseMirror/prosemirror#512]
In **Safari 9.0.1** I get an error like `Cannot declare a parameter named 'step' as it shadows the name of a strict mode function`.

The three offenders are:
* https://github.com/ProseMirror/prosemirror-view/blob/master/src/decoration.js#L124 (widget)
* https://github.com/ProseMirror/prosemirror-model/blob/master/src/schema.js#L403 (text)
* https://github.com/ProseMirror/prosemirror-transform/blob/master/src/transform.js#L36 (step)

A quick fix would be to rename the offending parameters to something different. This solution of course is error prone as this could come up again.

These all output code like: `Decoration.widget = function widget (pos, widget, options)`. So it's possible this can be solved by telling the compiler to not output that extra function name. It's also possible that I may be able to fix this on my end through the use of my JS uglifier and certain parameters. That said, it's probably an issue that will sneak up on people and completely break their editor for Safari 9 (which according to [w3counter](https://www.w3counter.com/globalstats.php) still has >3.5% of global usage).

**Comment by marijnh** [comment]
Ugggh. I tried to add something to catch this to my linter, but since the problem only appears during compliation to ES5, that's not really working out. I've pushed patches to fix the existing cases. It seems there's already a [patch](https://gitlab.com/Rich-Harris/buble/merge_requests/106) for the ES6 compiler we're using, but merging stuff in has been very slow on that project.

**Comment by marijnh** [comment]
We're now using a version of Bublé which works around this issue.
