### ISSUE TITLE
Selection is not restored sometimes after blur => focus

### ISSUE THREAD

**Issue by davidye** [ProseMirror/prosemirror#560]
This is a follow up to: #555. Not sure if this is useful or not since I was implementing my menu item incorrectly but posting it anyways.

I had a custom menu item that issued toggleMark() and then immediately focused the editor. Prior to 0.17.4 this worked just fine. In 0.17.4 and later, the first menu click would retain selection, but subsequent clicks would lose selection. This was tested on Chrome.

Minimal demo here: https://github.com/davidye/prosemirror-demo

**Comment by jbsulli** [comment]
@marijnh seems to use [`e.preventDefault()` on `mousedown`](https://github.com/ProseMirror/prosemirror-menu/blob/master/src/menu.js#L47) to prevent the selection from being lost in the first place. Not ideal but it's a thought.

**Comment by marijnh** [comment]
Does taking React out of the picture solve the issue? That seems to be the main difference between your example and mine.

**Comment by herkulano** [comment]
The problem seems to be during the `view.focus()`, it looses the selection. If you log the selection before the `view.focus()` it's correct but after it the `selection.to` changes to `selection.from`, so when you click again it's not applying on any text because the selection has changed, although the browser shows the correct selection.

![2017-02-13_19-07-41](https://cloud.githubusercontent.com/assets/125300/22894104/8b6d3554-f220-11e6-9e2f-22009da318fe.gif)

**Comment by herkulano** [comment]
@marijnh it's not related to React as the problem persists with vanilla js.

![2017-02-13_23-55-08](https://cloud.githubusercontent.com/assets/125300/22905184/0f8626c6-f248-11e6-80ee-2119dde6368c.gif)

Adding the `mousedown` with `e.preventDefault()` as @jbsulli suggests works. Although this is cumbersome in React because of synthesised events.

@marijnh would you consider saving the selection before `view.focus()` and reapplying it afterwards? In the log, it seems that it's only when the `view.focus()` is triggered that the selection is lost.

**Comment by jbsulli** [comment]
I've definitely been watching this closely. I did the whole `e.preventDefault()` on `mousedown` and got it to work but I had to write my own handling logic for clicks. So if you `mousedown` then move the mouse off the element and then mouse up, that isn't a true `click` event. And CSS seems to get a little wonky. 

At this point, I think a better way would be to store the selection and restore it after the click.

**Comment by marijnh** [comment]
Ah, you had to repeat the blur/focus cycle twice to actually observe the problem, that's why I wasn't seeing it before.

No need to ask me to change anything -- this is already how the editor is supposed to work. It always saves the current selection to `state.selection`, keeps it when it loses focus, and restores it when you call `focus`. But there was a bug, which attached patch should fix, that made it fail in this case.

**Comment by jbsulli** [comment]
Any idea when will this change go live?

**Comment by marijnh** [comment]
Some time next week, I hope. I was planning to do a release yesterday, but got somewhat stuck on a really scary problem (#543) which I'd like to solve first.

**Comment by jbsulli** [comment]
Sounds good. Thank you for the update!

**Comment by ThariqS** [comment]
I'm seeing this consistently. I am also using React with a seperate menu. I tried bringing in your hotfix (ignoring the atom commit in between) and just editing my prosemirror-view library but it didn't fix the problem. The problem I found was that the blur event was consistently firing but the focus event would not fire to restart the poller. `e.preventDefault` does fix it for the most part, but only because it prevents the focus from shifting away. 

The only thing I could do to get reasonable functionality back was to fork prosemirror-view and disable the blur event that causes the poller to stop. I'm not quite sure why this is and will try and see if I can make a minimal test case soon, but just wanted to report what I had to do.
