### ISSUE TITLE
copy/paste does not preserve markup / apply rules in Edge, IOS

### ISSUE THREAD

**Issue by dlants** [ProseMirror/prosemirror#595]
Edge 14 on browserstack and on iOS simulator (iOS 9.3 iPad Air). In both, copy / paste did not preserve headings or marks (this is the sample editor on the front of prosemirror.net )

I'm wondering if this is expected?

**Comment by d4rkr00t** [comment]
Can confirm this issue. 
Browsers: Edge 14 in BrowserStack, and also Edge 14 from the modern.ie image.

![edge-pasting-issue](https://cloud.githubusercontent.com/assets/200119/24483190/1560476c-1542-11e7-8fed-d8ef376394a6.gif)

**Comment by marijnh** [comment]
> I'm wondering if this is expected?

Yes, unfortunately, both those browsers don't provide scripts working access to the clipboard, so we have to just let the native behavior go through and hope it works. Which, unfortunately, it often doesn't.

I did some more research into the Edge situation, and it's pretty depressing. They are officially '[considering](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/clipboardapi/)' supporting clipboard access, but there doesn't seem to be much happening there. What they are currently shipping is some kind of inexplicably broken non-implementation where all the objects are there, but interacting with them either does nothing or raises our old friend the 'unspecified error'.

I'd actually expect the default behavior to more or less do the right thing in ProseMirror (except that we can't apply paste filters), but for some reason Edge appears to be pasting plain text instead of HTML.

I'm not sure what you mean by 'apply rules' in the issue title.

**Comment by dlants** [comment]
I meant parse rules :)

Unfortunate that this is the case. Thanks for looking into it!

**Comment by marijnh** [comment]
Okay, my windows VM has decided to force-upgrade (?!?) itself in the middle of my testing session, and it's taking forever, so I guess I'll come back to this later.

**Comment by marijnh** [comment]
If you want to help encourage microsoft to prioritize this, consider voting and commenting on [this feedback page](https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/6515107-clipboard-api).

**Comment by marijnh** [comment]
The text pasting occurs because these browsers don't let us access HTML in the clipboard, so ProseMirror is falling back on the text field, which it can read. That's easy enough to work around (see attached patch), but the resulting behavior is still not great.

Though the proper ways to do this are hopelessly broken in some browsers, it might be that the trick of quickly focusing a dummy node with the desired content on copy, and somehow detecting pasted content and re-parsing it on paste, would be a way to work around this. The parsing part is going to remain shaky, since we'll only get access to the content after the browser's own paste implementation has mangled it, but it's probably better than the really broken behavior we have now.

I'm calling it a week now, but I'll put some more energy into this next week.

**Comment by d4rkr00t** [comment]
Thanks for digging into this. Hope Microsoft will fix this eventually :)

**Comment by marijnh** [comment]
With attached patches, things seem to mostly work on both iOS and Edge. There's a unfocus-refocus-flash side effect of the hack I'm using, but I guess we'll just have to live with that.

**Comment by d4rkr00t** [comment]
Wow, awesome. Will test it later. Thank you!
