### ISSUE TITLE
ordering between onFocus/onBlur and hasFocus

### ISSUE THREAD

**Issue by dlants** [ProseMirror/prosemirror#596]
I have `onFocus/onBlur` for my `EditorView` hooked up to a view refresh. The refresh examines `view.hasFocus`. Sometimes in responding to an `onFocus` event, `view.hasFocus` returns false...

Looks like it's likely a race condition, since sometimes it works and sometimes it doesn't, and delaying the refresh by wrapping it in a `requestAnimationFrame` makes it consistently work.

Maybe worth adding a guarantee that when those events fire, `view.hasFocus` returns true.

**Comment by marijnh** [comment]
That happens because `hasFocus` checks both whether the editor's element is focused and whether the DOM selection is inside of it. Right after a `focus` event fires, the selection is often not in the editor yet. That's actually usually probably not what users expect, so attached patch changes it to simply return whether the outer element is focused.
