### ISSUE TITLE
Exception throws on excludes marks if mark is not included in schema

### ISSUE THREAD

**Issue by jchappypig** [ProseMirror/prosemirror#613]
Hi Marijn,

This usually should not be a problem. But cause inconvenience because we are using minor different schemas for different products with shared defined markspecs. 

For example,  
we defined code to excludes 'underline em strong'

But underline does not exist in some other products. It throws exception "SyntaxError: Unknown mark type: 'underline'"

It would be great if we can make the markspec and nodespec reusable for different schemas and embrace the difference.

Cheers,
Huanhuan

**Comment by marijnh** [comment]
> It would be great if we can make the markspec and nodespec reusable for different schemas and embrace the difference.

With node specs, you'll definitely have to adjust `content` expressions per-schema, since there referencing non-existing nodes is never going to work. I think it's a reasonable thing to do for the Schema constructor to check its input and provide helpful messages when it appears invalid -- could you maybe do a thing where you have your own utility function for constructing schemas that strips unneccessary mark names off the `excludes` field before calling `new Schema`?
