### ISSUE TITLE
Mark is not preserved when replacing first character of non inclusive mark

### ISSUE THREAD

**Issue by d4rkr00t** [ProseMirror/prosemirror#620]
- Having none inclusive mark (e.g. link) select first character
- If you type the same character as the one selected mark is preserved
- Typing other character removes the mark

Tested in: latest Chrome, latest Firefox, latest Safari.

Issue only occurs at the beginning  of the mark, at the end of the mark everything works as expected.

I tried to make a video demonstrating an issue but i'm not sure if it's clear enough.

![kapture 2017-04-19 at 10 30 39](https://cloud.githubusercontent.com/assets/200119/25158451/d1193b7c-24eb-11e7-960e-3db01b3b540b.gif)

It works in simple contenteditable https://codepen.io/iamsysoev/pen/oWjrYM

**Comment by marijnh** [comment]
Disregarding the inconsistency when type an identical letter for a moment, I think there's a good case to be made for not giving the new text the link mark. It's at the start of a link, and link marks are non-inclusive (don't get inherited by text inserted at its sides). Google Docs behaves the same.

The identical-letter issue is due to the DOM diffing not noticing that anything changed in that case. I agree that the two cases should behave identically.

**Comment by d4rkr00t** [comment]
Yeah, makes sense, thanks :)

**Comment by marijnh** [comment]
I've opened #631 as a followup
