### ISSUE TITLE
Preserve new lines when pasting HTML

### ISSUE THREAD

**Issue by jspn500** [ProseMirror/prosemirror#630]
When pasting a block of code from a certain text editors (e.g. Visual Studio Code) we'd like to parse it as code-block (nodeSpec parseDOM does the trick) and keep formatting. 

After pasting, it deletes all new lines. Apparently its because `parseFromClipboard` function converts new lines to paragraphs only in case of pasting plainText. 

I wonder if there is any way we could keep new lines when pasting HTML? I know we could use post-processing of slice with `handlePaste`, but I was under impression that PM should keep formatting by itself. Thanks.

**Comment by marijnh** [comment]
So the content is being pasted as HTML? Do you happen to know what the concrete HTML looks like?

**Comment by jspn500** [comment]
Correct. In case of copy-pasting any code snippet from Visual Studio Code, you'd copy a piece of HTML, because it's a HTML+CSS based app created with [Electron](https://github.com/electron/electron). 

So the HTML looks like this: 
<img width="1339" alt="screen shot 2017-05-04 at 9 35 02 am" src="https://cloud.githubusercontent.com/assets/26512812/25685771/0c634674-30ad-11e7-96a0-06046d2960f3.png">

where each nested `div` is a new line in code.

After it passes this line `var parser = view.someProp("clipboardParser") || view.someProp("domParser") || DOMParser.fromSchema(view.state.schema)` in `parseFromClipboard`, it converts all the content to textNode, because our codeBlock content is `text*` and it swallows all newlines here. I thought maybe we could do the same conversion of "new line = paragraph" on the `fromSchema` step.

**Comment by Thinkscape** [comment]
I feel like this might be a bit of a grey area of handling paste content.

We could with @jspn500 add a parser for the markup, hence supporting a subset of IDEs and Editors, until a new one comes out that produces a different output. I wonder if enabling specific plugins (i.e. git lens) or changing colour scheme in VSCode would result in different markup when copying.

I see different ways to look at it, mutually exclusive:

1. Because handling clipboard content is a common task, PM as a library, is responsible for understanding different (popular?) formats of clipboard data and mutate them accordingly.
2. Supporting 3rd party apps and clipboard sources is more of a product logic, so that should be responsibility of PM consumers to support that (or not). This potentially leads to code duplication.
3. The input is unexpected - we shouldn't cater for each 3rd party apps. Instead, we should raise an issue with VSCode (among others) that produce this kind of non-standard markup. We would need to determine what "standard markup" means in this case.

**Comment by marijnh** [comment]
This wasn't intentional behavior, but rather a bug in the DOM parser. Patch https://github.com/ProseMirror/prosemirror-model/commit/0582359f80439f1df03c1bca586ead75da72c41e should help, by making sure each line gets a block element around it.

**Comment by jspn500** [comment]
It's very close to what I expected. 

As an example, I copy the code of `DOMParser.prototype.parse`  method from VSC. When I paste, `dom` param in `parseSlice` method looks like this:

<img width="1239" alt="screen shot 2017-05-05 at 10 33 12 am" src="https://cloud.githubusercontent.com/assets/26512812/25730239/53810a06-317e-11e7-8ab6-77d932018451.png">

In my code-block schema I have:
`parseDOM` that matches `tag: 'div[style*="white-space: pre;"]'` 
`content: 'text*',`

it matches first nested `div` from the screenshot as expected. 

Ideally I'd expect all of it's content to be formatted text with preserved new lines.
Currently `parseSlice` gives me a code-block with textNode child without new lines.

<img width="1361" alt="screen shot 2017-05-05 at 10 35 47 am" src="https://cloud.githubusercontent.com/assets/26512812/25730296/c715c1be-317e-11e7-901c-3b7c0b8ee120.png">

**Comment by marijnh** [comment]
Have you tried adding `preserveWhiteSpace: "full"` to the parse rule?

**Comment by jspn500** [comment]
I'm sorry, I should have mentioned that before. I have tried that too, got the same result.
