### ISSUE TITLE
tr.replaceWith gets wrong selection mapping (codeblocks)

### ISSUE THREAD

**Issue by wes-r** [ProseMirror/prosemirror#645]
OK so I may be approaching this all wrong, I'm trying to insert a code block on an empty line OR wrap selected text into a code block. The tricky part here is that codeblocks want text and not paragraph nodes.

```javascript
let node = schema.nodes.code_block.create(
    null,
    new Fragment([schema.text(state.doc.textBetween(from, to, '\n'))])
 )
transform = transform.replaceWith(from, to, node);
```

When I do this `transform.selection` is wrong. In both cases (wrapping existing text or inserting on a new line) the new selection puts my cursor just after the code block. Ideally the cursor would be inside the codeblock for empty codeblocks OR within and highlighting all of the wrapped text.

1. Is there a better way to do this?
2. Is this a bug?

Thanks for the help!

**Comment by marijnh** [comment]
> When I do this transform.selection is wrong.

Putting the selection after the inserted content is just what `replaceWith` does, so this is not so much wrong as not what you were hoping for. Since the library can't guess what you're hoping for, the solution is to manually set the selection to what you want it to be after the fact, for example by finding the last valid cursor position after the place that `to` maps from (`Selection.findFrom(transform.doc.resolve(transform.mapping.map(to)), -1)`).

**Comment by wes-r** [comment]
From the docs:
> selection: Selection
> The transform's current selection. This defaults to the editor selection mapped through the steps in this transform, but can be overwritten with setSelection.

This had be believe that the mapping is magically handled for me.

I still can't seem to get this to work with the `findFrom`.

The position I want is `32`
```
to = 32
transform.mapping.map(to) = 34
final selection.to = 34
```

I've gotten it to "mostly" work by manipulating the positions manually and creating a new `TextSelection` although seems to be having it's own issues o_O

**Comment by marijnh** [comment]
> This had be believe that the mapping is magically handled for me.

Mapping through a given step simply means moving it if the content in front of it changed, so that it remains in the same place, or pushing it out of deleted content.

You did not describe what you want to achieve (i.e. what is 32 based on), so I can't say much about how to achieve that.

**Comment by wes-r** [comment]
In this example, `32` is the position within my codeblock after inserting it.

**Comment by marijnh** [comment]
And the codeblock is empty? I'd expect `transform.mapping.map(to)` to point directly after the inserted block, and `Selection.findFrom` to find the position inside the code block. Or maybe your start position was inside a text block that was split to insert the block, and `findFrom` returns the position you fed it because that's a text position. It should be safe to subtract one from the position (before feeding it to `resolve`) to avoid that.

**Comment by wes-r** [comment]
I have a solution I'm mostly happy with. I think there's something funky with the code block where if I setup a `setSelection` on the transform it doesn't work but if I dispatch the same selection after the insert (using `setTimeout`) it does work. Not sure why, I haven't modified your codeblock example much. This seems to be sufficient with the minor issues of 1. the cursor has a tiny jump to the position and 2. it doesn't behave perfectly with undo/redo.
