### ISSUE TITLE
Type of PluginSpec::state

### ISSUE THREAD

**Issue by timjb** [ProseMirror/prosemirror#654]
The `state` field of `PluginSpec` is currently declared as follows:

```
// PluginSpec:: interface
//   state:: ?StateField
```

This declaration is incomplete since the `StateField` interface expects a type parameter. This causes problems when using the getdocs comments to generate TypeScript type declarations. I can think of three solutions for this problem:

1. Use `any` as the type parameter:
   ```
   // PluginSpec:: interface
   //   state:: ?StateField<any>
   ```

2. Adopt the following rule for interpreting getdocs comments: Any missing type parameters are interpreted as [existential types](https://stackoverflow.com/questions/292274/what-is-an-existential-type). Then the current declaration is the correct one. I would then have to make my TypeScript generator notice the missing type parameter and use `any` as a parameter instead (since TypeScript doesn't support existential types).

3. Introduce an explicit getdocs syntax for existential types.

**Comment by marijnh** [comment]
I guess the first solution is the easiest for now, and I've implemented it in attached patch. It would be more correct to give `Plugin` and `PluginSpec` a type parameter as well, so that things like `getState` can return the correct type, but that'd cause quite a lot of extra verbosity and I'm not sure it'd help accurately type things in practice. We can revisit this in the future.
