### ISSUE TITLE
Move type-specific input rules out of inputrules

### ISSUE THREAD

**Issue by bradleyayers** [ProseMirror/prosemirror#674]
I propose we move the node-type specific input rules out of prosemirror-inputrules and into either prosemirror-example-setup or type-specific packages like prosemirror-schema-list. At the moment in prosemirror-inputrules we have:

- blockQuoteRule
- orderedListRule
- bulletListRule
- codeBlockRule
- headingRule

The rationale being that prosemirror-inputrules should be responsible for providing the infrastructure to *do* inputrules, but be agnostic to non-core node types.

**Comment by marijnh** [comment]
I am leaning towards keeping them where they are, because these are just a few lines of code and don't create any new dependencies. Note that the node type is a parameter to these utilities, so they don't depend on the specific definition of, say, blockquote nodes in the schema modules -- you can put in anything that you want to appear on `> `.

Do these being in the `inputrules` package create any specific problem for you?

**Comment by bradleyayers** [comment]
I agree that they don't create a technical problem living in inputrules. Instead I think they blur the lines of responsibility for the package (e.g. by suggesting that it's concerned with markdown conventions).

For example `headingRule` assumes that the node type expects a `level` attribute, and `orderedList` assumes an `order` attribute. Given they have specific expectations about the schema I'd have expected they'd be co-located with the schema itself. Having an otherwise schema-agnostic package (inputrules) include coupling to specific schema shapes seems inappropriate.

Fundamentally it boils down to a mismatch what I guess the package responsibilities are, compared to what they really are.

I'd argue the real-world consequences of this are:

- it makes learning the framework more challenging (APIs are not where one might expect to find them)
- it makes contributions more challenging (where should code really live? is some behaviour a feature or a bug? is this behaviour in scope?)

I don't want to derail this issue, but some other things I noticed:

- the builders/factories living in `util.js` was surprising to me, I expected them to just live in `rules.js`.
- having `allInputRules` is a challenging API to support, since added new rules to it is not clearly backwards compatible (it would change behaviour for existing users).

Sorry to nitpick 🙁.

**Comment by marijnh** [comment]
> * it makes learning the framework more challenging (APIs are not where one might expect to find them)
> * it makes contributions more challenging (where should code really live? is some behaviour a feature or a bug? is this behaviour in scope?)

I'm a bit worried that moving everything into example-setup places a too-large burden on people setting up an editor. On the other hand, I've been rather ruthlessly doing this kind of minimalism in other modules, so maybe it would be appropriate here too.

> * the builders/factories living in util.js was surprising to me, I expected them to just live in rules.js.

Yeah, util is the worst module name in the world. Would `builders.js` make more sense?

> * having allInputRules is a challenging API to support, since added new rules to it is not clearly backwards compatible (it would change behaviour for existing users).

That's true. I'm kind of struggling to come up with another way to expose these in an easy-to-consume way. Any ideas? Or is the whole idea of making them easy to consume misguided to start with?

**Comment by bradleyayers** [comment]
I would probably make a clear distinction between "building blocks" and "ready-to-go components", and keep a clear separation between the two. I've found the example-setup to be really useful in just seeing how everything can be wired up, and even though I don't think I ever directly NPM depend on it, being able to just copy/pasting as "starter code" and modifying it has been very helpful.

I'd probably embrace `prosemirror-example-setup`, and move `prosemirror-schema-basic` into it. All the pre-composed components that make assumptions about schema or such can live there, and the test of "how well prosemirror is to use" is basically how small `prosemirror-basic-editor` whilst not compromising the separation of concerns.

I think ProseMirror has two main user personas:

1. I'm just getting started and want to prototype the integration of an editor into my product
2. I'm committed to using ProseMirror, and now want to have full control of behaviour and integration

`prosemirror-example-setup` serves the first, and rest of the packages in the suite serve the second.

If `prosemirror-schema-basic` should live on, then I think none of its nodes/marks should know about each other, and instead the package would just export builders rather than pre-baked nodes.

> Yeah, util is the worst module name in the world. Would builders.js make more sense?

Yep `builders.js` or even `ruleBuilders.js` would be be quite intuitive to me.

I think a thread on discourse would also be helpful, I'm sure others would be opinions on this.

**Comment by marijnh** [comment]
> If prosemirror-schema-basic should live on, then I think none of its nodes/marks should know about each other, and instead the package would just export builders rather than pre-baked nodes.

Note that this is already the case -- the only interface between the nodes in the basic schema is that they refer to 'block' and 'inline' node groups.

I've pushed a5b0209.

It feels that if we are going to remove rules from the input rules module, we should remove all rules -- after all, smart quotes and such are also just specific instances of rules that are somewhat out of place in an infrastructure package. But at some point, you'd find yourself subdividing the system into a fractal lot of hyper-specific packages (`prosemirror-inputrules-smartquotes`) and making it just really painful to use. So in order to avoid that, I'm taking the approach of leaving things in a not-quite-clean but convenient shape when that doesn't incur any problematic coupling. And with these rules, sure, they aren't hugely general, but they also are small and, as I mentioned, without dependencies. So my proposal is to just leave them here, and maybe call them 'example rules' in the docs.
