### ISSUE TITLE
Problem with collapse of DOM nodes

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [ProseMirror/prosemirror#709]
### Issue details

Elements do not collapse as expected.
In **[Quill](https://quilljs.com/)**, this works without problems.
This is my simple test for suitability (quality) WYSIWYG-editor.

### Steps to reproduce

1. Type text ```node1 node2```
2. Make bold and italic ```node1 node2``` // **_node1 node2_**
3. Unset italic ```node1``` // **node1 _node2_**

ProseMirror result DOM (bad):
```HTML
<p><em><strong>node1</strong></em><strong> node2</strong></p>
```
Quill result DOM (good):
```HTML
<p><strong>node1 <em>node2</em></strong></p>
```

### Please specify which version of ProseMirror you're running

ProseMirror v[  site-version ]

### Affected platforms
- Vivaldi | 1.12.955.38 (Stable channel)

**Comment by marijnh** [comment]
In order to produce predictable output, ProseMirror maintains a fixed ordering in the way marks are applied. Your test doesn't actually say anything about the content model (where marks are stored as arrays, not nested nodes), and it's perfectly possible to write a DOM serializer that produces the output you prefer (the Markdown serializer already has logic like that). The default serializer doesn't currently implement this because I found it more complexity than it's worth.
