### ISSUE TITLE
Add Relative Link

### ISSUE THREAD

**Issue by amkgo** [ProseMirror/prosemirror#725]
I want to add relative links to my document because there is no domain name for my website yet and the ip address may change at later time.

When I add a link "/document/index.html", ProseMirror will add the "http://" at the beginning so the link changed to "http:///document/index.html" which will broken the link.

Is it possible to add a relative link in ProseMirror?

This issue is related to [this discuss topic](https://discuss.prosemirror.net/t/relative-path/1051)

Thanks

**Comment by adrianheine** [comment]
We could add some heuristic to check if the link target starts with `/`.

**Comment by marijnh** [comment]
But you can also have relative links that don't start with `/`. I couldn't think of a good way to disambiguate between `foo.html` and `google.com` without hard-coding top level domains (which isn't really viable anymore). Also, in the age of https-everywhere blindly adding `http://` in front of a link is flaky, so I've simply removed that cleanup rule from the example menu in attached patch.

That being said, this is the _example_ menu, and if you have specific customization needs, the preferred way to address them is to write you own menu, rather than filing bugs against the example.

**Comment by amkgo** [comment]
> blindly adding http:// in front of a link is flaky
Yes, maybe just add the link as is to keep it simple. This way I can add relative link. Also someone can add https links or even ftp links as long as they provide the full path.

**Comment by marijnh** [comment]
> Yes, maybe just add the link as is to keep it simple.

Right, that's what the attached patch does.

**Comment by amkgo** [comment]
When I add a link "/sku/123", the leading slash is missing and the link becomes "sku/123".

**Comment by marijnh** [comment]
I can't reproduce that problem — the URL is stored in the attribute just as I enter it.

**Comment by amkgo** [comment]
I'm having difficulty to make webpack work when adding the specific commit using
`yarn add https://github.com/ProseMirror/prosemirror-example-setup#cd2a731d68dec3e9ef376459a135afe61f968d7c`
 
Can you please tag the version so that I can install it using yarn.
Thanks.

**Comment by marijnh** [comment]
Done (prosemirror-example-setup 1.0.1)

**Comment by amkgo** [comment]
It works great.
Thanks.
