### ISSUE TITLE
Uncaught TypeError: Cannot read property 'pos' of null

### ISSUE THREAD

**Issue by mjmasn** [ProseMirror/prosemirror#728]
In https://github.com/ProseMirror/prosemirror-view/blob/75f89f388cc4bdc26bdbfeae5ba3947b04238a1e/src/input.js#L500

`posAtCoords`  may return `null`, so there needs to be a guard in there before trying to access the `pos` property of the result. Happy to do a PR if needed.

Btw we're possibly seeing this issue because we're drawing some stuff on top of the prosemirror editor.

**Comment by marijnh** [comment]
The code assumes that, since the drop event is delivered on the editor, the mouse coords must be over some child of the editor, in which case `posAtCoords` shouldn't return null. But I guess there can be weird edge cases where that doesn't work out. A pull request that simply returns from the handler when no position is found would be welcome.
