### ISSUE TITLE
Can you add example of implementation todo list with checkbox?

### ISSUE THREAD

**Issue by igorbelikov** [ProseMirror/prosemirror#736]
### Issue details

Can you add example of implementation todo list with checkbox?

Example:
[x] item 1
[ ] item 2
[ ] item 3

**Comment by kiejo** [comment]
Someone recently posted a working example in the discussion forum: https://discuss.prosemirror.net/t/todo-list-improvements/1449
And this is the final version that was posted: https://glitch.com/edit/#!/grave-governor

**Comment by igorbelikov** [comment]
@kiejo oh, thank you. :-)

**Comment by philippkuehn** [comment]
@igorbelikov there is also a [todo list example](https://tiptap.scrumpy.io/todo-list) for tiptap (a prosemirror wrapper for vue).

**Comment by igorbelikov** [comment]
@philippkuehn excellent, thank you.

**Comment by marijnh** [comment]
There aren't plans to add this example to the project website, so I'll close this.

**Comment by eric-burel** [comment]
Hey folks, small tips for lost googlers:
- the best approach seems to be having "todo_list" and "todo_list_item" nodes, similarly to other types of list
- another approach is to have `content: "checkbox block*"` or similar, basically adding an additionnal "todo_list_checkbox" node just for the checkbox but I think it is doomed, I couldn't get it to behave properly
- Remember to set keymap with "splitListItem" so that "todo_list_item" are created when you press Enter

A tough part is tracking the checkbox state. As a default, the checkbox may do nothing on click, or do something but you never see the updated state. 
As [recommended here](https://discuss.prosemirror.net/t/help-with-recognizing-checkboxes/1196/6), you can create a new `NodeView` that tracks clicking on checkbox.
Other tips:
- if you stick to `toDOM` for rendering, remember that you can nest elements, eg `["div", [ "input", { type: "checkbox" } ], ["div", 0 ] ]` <- the hole is nested into the second div. This was not obvious and I figured by reading Tiptap code.
- DOM inputs check state is updated via a property, not an attribute: it's `input.checked = true`, not `input.setAttribute("checked")`.

Thanks all for the info you shared earlier, it was not easy to implement but after looking at those different sources I could figure something that works!
