### ISSUE TITLE
"Only non-generatable nodes after a match state" error could use clarification

### ISSUE THREAD

**Issue by toolness** [ProseMirror/prosemirror#758]
Hi!  Working on a project, we ran into this error, raised at [`content.js` in `prosemirror-model`](https://github.com/ProseMirror/prosemirror-model/blob/8a33390e9a066d421bd2df27ea73c97fb95be339/src/content.js#L360).  I managed to figure out how to [work around it](https://github.com/18F/omb-eregs/pull/978#issuecomment-362017700) but I'm not really sure _why_ ProseMirror wanted my schema rule to contain only nodes that it could auto-generate if needed.

I'd be happy to submit a PR that elucidates the error message to the best of my limited ability, if it would help folks who run into the same error I did!

**Comment by marijnh** [comment]
The problem is that ProseMirror needs to be able to generate valid content for every node, to be able to ensure that arbitrary edit operations can be performed without violating the constraints. Some nodes, such as those with attributes that don't have a default value, can't be generated and as such may not occur in non-optional positions in the content expressions.

I agree the error message could be better (it is written that way because the way I'm detecting non-optional positions is by seeing if any of the nodes in the state machine for the expression has only out edges that can't be generated). I'm not entirely sure how to describe the situation in a short error message though. Probably the best approach is to add a section about this to the schema guide, and link to it from the error message. I'll leave this open to remind myself.

**Comment by marijnh** [comment]
Done in https://github.com/ProseMirror/website/commit/92d3ec7532aab89513d54eb625882cdc3aebcb16 and https://github.com/ProseMirror/prosemirror-model/commit/656cffc8f6a0579394fb21e73f747c8a47ab0c78
