### ISSUE TITLE
Heads up: Chrome 65 will change composition events on Android

### ISSUE THREAD

**Issue by javan** [ProseMirror/prosemirror#763]
See the following issues for details and please chime in if you have anything to add.
- https://bugs.chromium.org/p/chromium/issues/detail?id=764439#c9
- https://bugs.chromium.org/p/chromium/issues/detail?id=812674

**Comment by marijnh** [comment]
> Before this change, I think there were situations where we were firing compositionupdate events without ever firing a compositionstart event.

They were, and ProseMirror treats the two events the same for this reason. It doesn't sound like ProseMirror will be affected by these changes, since it is already not expecting any useful information from these events (they never reliably reflected what happened, on Android but also with some non-mobile IME software). But if someone finds a regression, do file an issue!
