### ISSUE TITLE
NodeSelection replace removes attrs when it's not possible remove the node

### ISSUE THREAD

**Issue by torifat** [ProseMirror/prosemirror#786]
### Issue details
Trying to replace the selection with an invalid node end up removing the selected node's `attrs`.

### Steps to reproduce

1. Go to https://gifted-dessert.glitch.me/
2. Select the purple node.
3. Press "Replace With" or "Insert Text"
4. Check **Console**

---

**`doc` before `dispatch`**
```json
{"type":"doc","content":[{"type":"nodeA","content":[{"type":"nodeB","attrs":{"id":"5"}}]}]}
```

**`doc` after `dispatch`**
```json
{"type":"doc","content":[{"type":"nodeA","content":[{"type":"nodeB","attrs":{"id":null}}]}]}
```

---

`id` became `null` from `5`

### ProseMirror version
`prosemirror-state@1.2.0`

### Affected platforms

N/A

### Screenshots / Screencast (Optional)
![kapture 2018-04-11 at 13 39 41](https://user-images.githubusercontent.com/208544/38595249-05a9c54e-3d8e-11e8-827e-fa88e9a72326.gif)

**Comment by marijnh** [comment]
This is the intended behavior—you're telling the replace algorithm to delete the node and replace it with something else. If that something else doesn't fit, it won't insert it, but that doesn't cancel the delete behavior. Since the node is then missing, the content expression is satisfied by creating a new instance of the fitting node type, with default attributes.

I recommend disabling such controls when the content they insert doesn't fit at the current selection position.

**Comment by torifat** [comment]
Thanks for explaining. I thought it's a no-op. Resetting makes sense in some context.
