### ISSUE TITLE
Selection is not populated if text selection was started from outside ProseMirror (Firefox)

### ISSUE THREAD

**Issue by Narretz** [ProseMirror/prosemirror#797]
### Steps to reproduce

Open the tooltip example: https://rightful-hawk.glitch.me/
Now start a text-selection with the mouse, but press the mousebutton outside the prosemirror and move it inside to select. This works in Firefox - in Chrome it only works if there's another element to select outside the editor.
I would expect the tooltip to show (it shows when the selection is not empty), but it never does, so this means the selection in ProseMirror is never set - but the browser selection shows.

### ProseMirror version
Version of Example - latest I assume

### Affected platforms
Windows + Firefox
(In Chrome, it's impossible to select coming from "nothing")

- [ ] Chrome
- [x] Firefox
- [ ] Internet Explorer
- [ ] Other

**Comment by marijnh** [comment]
When the editor isn't focused it's not listening for selection changes (since most browsers disallow selections across differently-editable elements). I'm not sure whether representing such a selection as a ProseMirror selection makes much sense anyway—since one side is outside of the editor, it doesn't really correspond to anything a ProseMirror selection can represent, and any time ProseMirror would update the selection (for example because its DOM changed) it'd visibly alter the DOM selection.

So I'm leaning towards considering this the correct behavior. Can you live with that?

**Comment by marijnh** [comment]
You could listen to `selectionchange` events (on the document), and when the new selection has one side (`getSelection().focusNode` / `anchorNode`) inside and one side outside the editor, update the editor selection and focus it to force an editor-only selection.

**Comment by Narretz** [comment]
Thanks I'll try that! You can close this issue if you want.
