### ISSUE TITLE
Can't drop block node into middle of text

### ISSUE THREAD

**Issue by mjadobson** [ProseMirror/prosemirror#811]
When dragging a block node, eg: a horizontal rule, you can only drop it in between block nodes, and not in the middle and split the content.

Related issues seem to have been raised previously #188 , #798 .  Although in these cases it seems the desired behaviour was to *not* split.

You can't drag and drop, but you can paste to the position, as shown in the screencast:

![http://g.recordit.co/FOrKGGP1kx.gif](http://g.recordit.co/FOrKGGP1kx.gif)

**Comment by marijnh** [comment]
Yes, this is intentional—you rarely want to insert a block element in a place where it isn't allowed (through splitting), so the editor finds the nearest place where the element fits, rather than having the user find the precise drop position. With copy paste, you have more explicit control over the insertion point, so there this isn't considered a problem.

**Comment by vmurillo** [comment]
Hello, I am looking into dropping an image inside a paragraph how could I overrule this default behaviour?

**Comment by marijnh** [comment]
You'd need a [`handleDrop`](https://prosemirror.net/docs/ref/#view.EditorProps.handleDrop) handler for that.
