### ISSUE TITLE
Error when a textblock with a mark is joined with a textblock where the mark is forbidden

### ISSUE THREAD

**Issue by jakeknerr** [ProseMirror/prosemirror#816]
### Issue details

When text content with a mark is joined with an earlier text block that does not allow said mark, an invalid_content error is thrown. 

### Steps to reproduce

Open the "Schema From Scratch" demo at https://prosemirror.net/examples/schema/

The 2nd example, the stars and shouting example.

After the "boring" paragraph, select the entire following paragraph and hit "ctrl-b" to add the shouting mark. At this point, "Press ctrl/cmd-space to insert a star, ctrl/cmd-b to toggle shouting, and ctrl/cmd-q to add or remove a link." should be shouted.

Now, select from the middle of the shouted paragraph to the middle of the boring paragraph.  

Hit backspace.

Throws "Uncaught Error: Invalid content for node boring_paragraph"

### ProseMirror version
prosemirror-model": "^1.4.4"
prosemirror-schema-basic": "^1.0.0"
prosemirror-schema-list": "^1.0.1"
prosemirror-state": "^1.2.0"
prosemirror-transform": "^1.0.10"
prosemirror-view": "^1.3.0"

### Affected platforms

- [X ] Chrome
- [X ] Firefox
- [X ] Internet Explorer
- [ ] Other

**Comment by marijnh** [comment]
Oh, right, that's bad. Attached patch fixes this by disallowing the joining of such nodes. It's not ideal, since the expected behavior would probably be to delete the marks and join the nodes, but that fits poorly with the way replace steps work—they can't (and shouldn't) touch anything outside of the replaced range. Maybe that can be addressed at a higher level at some point, for now, at least the crash is fixed.

**Comment by jakeknerr** [comment]
Thanks, I tried it out and it is working for me.

I actually prefer this behavior to automatic joining and deleting the forbidden marks because it provides a simple way to prevent text blocks from being joined without heavy transaction inspection.
