### ISSUE TITLE
Safari - Pasting html headline with nested span does not work

### ISSUE THREAD

**Issue by rootman** [ProseMirror/prosemirror#817]
### Issue details

When copying a headline that has a nested span, the content is not inserted in safari.

Pasting an article from wikipedia would not insert some of the headlines, I narrowed it down to the inline span.

It works in Chrome.

### Steps to reproduce

- https://en.wikipedia.org/wiki/Sargatsky_District , select and copy the headline "References"
- http://prosemirror.net clear editor and paste into editor

### ProseMirror version

"prosemirror-collab": "^1.0.0",
"prosemirror-commands": "^1.0.7",
"prosemirror-example-setup": "^1.0.1",
"prosemirror-history": "^1.0.2",
"prosemirror-inputrules": "^1.0.1",
"prosemirror-keymap": "^1.0.1",
"prosemirror-model": "^1.4.4",
"prosemirror-schema-basic": "^1.0.0",
"prosemirror-schema-list": "^1.0.1",
"prosemirror-state": "^1.2.0",
"prosemirror-transform": "^1.0.10",

### Affected platforms

Safari Version 11.1.1 (13605.2.8)

**Comment by marijnh** [comment]
This is the HTML Safari provides on the clipboard in this situation:

```
<h2 style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style:
normal; font-variant-caps: normal; letter-spacing: normal; orphans:
auto; text-align: start; text-indent: 0px; text-transform: none;
white-space: normal; widows: auto; word-spacing: 0px;
-webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px;
text-decoration: none; background-image: none; font-weight: normal;
margin: 1em 0px 0.25em; overflow: hidden; padding: 0px;
border-bottom-width: 1px; border-bottom-style: solid;
border-bottom-color: rgb(162, 169, 177); font-size: 1.5em;
font-family: &quot;Linux Libertine&quot;, Georgia, Times, serif;
line-height: 1.3;"><span class="mw-headline"
id="References"></span></h2>
```

Or, without the style junk:

```
<h2><span class="mw-headline" id="References"></span></h2>
```

Note that _there is no text_ in the span. If I paste in Chrome, with the same clipboard state, the word "References" _is_ in the span, so that's pretty strange. But trying to paste the same thing in a plain contentEditable div in Safari also fails, so this is a Safari bug and I don't see how ProseMirror couid possibly work around it (we can only access the clipboard content the way the browser gives it to us, and if that's wrong, we're out of luck), so I'm going to close this. You can try reporting it with Apple, if you're brave (remember, it reproduces in any contentEditable element, so it shouldn't be hard to demonstrate).

**Comment by rootman** [comment]
Thank you for looking into it! I'll think about trying my luck with Apple ;)
