### ISSUE TITLE
Android: Software Keyboard Jumping Behavior

### ISSUE THREAD

**Issue by steveccable** [ProseMirror/prosemirror#829]
### Issue details

When using ProseMirror on Android, either in a WebView within an App, or on a webpage in Chrome, the cursor is jumping around when trying to apply marks.

### Steps to reproduce

https://glitch.com/edit/#!/ember-cactus (same as the basic demo but with all the initial contents removed from the editor)
On Android, begin typing in the editor using the software keyboard and DO NOT add any whitespace to what you are typing.  At some point, tap somewhere inside of the text you typed, then tap one of the buttons to apply a mark (for example, bold).  Begin typing on the soft keyboard again.
Note that the first character typed will have the mark applied, but then the cursor will jump forward one character and further typing is applied at the new cursor position, without the mark applied.  If you tap back to the character which has the mark and type from there, the mark is applied normally.

Likely related, if when tapping to apply a mark you also call `editor.focus()` then the cursor will immediately jump to the start of the editor, and any typing from there will not have the mark applied.  This only seems to happen once, as later calls of `editor.focus()` will not cause this jump.

### ProseMirror version

Appears in the current demo version (at time of writing, that appears to be 1.4.1) but has been noted back to 1.3.1 (the version my app was using at time of first seeing this behavior).

### Affected platforms

- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [x] Other

This is seen only on Android devices, but has been noted across multiple browser versions (all Chrome, since that is the default Android browser) and multiple Android OS versions.

### Additional Notes

This DOES NOT occur when typing with a hardware keyboard rather than a software keyboard.  After further investigation, it appears that using a software keyboard on Android does not send full information to `keyup` and `keydown` events, and doesn't trigger a `keypress` event at all (for further reading, see [this SO post and the linked chromium discussion at the top answer](https://stackoverflow.com/questions/30743490/capture-keys-typed-on-android-virtual-keyboard-using-javascript).
I also noted that the `editor.state.selection` remains of type AllSelection at all times while using the software keyboard until tapping inside of typed text or adding whitespace, whereas on a desktop web browser (or when using a hardware keyboard) it becomes TextSelection as soon as you start typing.  Not sure if this is related, but figured it might be valuable to point out.

**Comment by marijnh** [comment]
Thanks for the detailed description. I can reproduce most of this, except for the second typed letter after adding a mark not being marked—but it's not uncommon for different virtual keyboard to behave differently (adding another dimension to the matrix of compatibility issues). I'm using Gboard.

But yeah, playing with this, I think you initial conclusion that this is a symptom of #543 is correct. When you generate a transaction by pressing the mark button, it can't be rendered immediately because a composition is still in progress, and you get this strange behavior where the display and the state are out of sync.

Fixing this properly is probably going to take a while (I'll comment on #543 with details), but if you want a hack, you could wire up your `dispatch` callback to do something like

```javascript
  if (view.inDOMChange) view.inDOMChange.finish(true)
```

That's accessing internal APIs and not terribly clean, but it'll force the end of the current composition right away when you press a button, and should improve behavior here.

The downside is that, if you also have transactions not directly caused by the user, such as collaborative editing events or async callback doing something when a network request comes back, it'll disrupt composition at unpredictable points in time, which is bad (you could refine the hack by adding a meta property to transactions that don't need to be immediately pushed through).

Merging this back into #543
