### ISSUE TITLE
Feature Request: GapCursor should allow marks

### ISSUE THREAD

**Issue by wes-r** [ProseMirror/prosemirror#845]
GapCursor should allow the setting of marks. If a user arrows to the top or bottom of the document and gets a GapCursor, they should be able to hit **bold** menu item OR `COMMAND+B` to toggle the bold mark on for when they start typing.

**Comment by wes-r** [comment]
I am indeed using `toggleMark`. What about special casing if selection is a `GapCursor`?

**Comment by marijnh** [comment]
The commands package doesn't know the gapcursor package exists, and that's probably the way it should be, since they aren't related. A possibly more promising approach would be to refine the test to allow the command to work in all places that either directly allow the mark, or where the default insertable node is a textblock that allows the mark.

**Comment by marijnh** [comment]
On second thought, don't think it is a good idea, at least by default, to allow inline marks to be manipulated when the selection isn't in an inline context. Closing this (but of course you can implement your own mark-manipulating commands that work differently).
