### ISSUE TITLE
No transaction when clicking on selection in non-editable mode in Chrome and Edge

### ISSUE THREAD

**Issue by Narretz** [ProseMirror/prosemirror#847]
### Steps to reproduce
1. Create a view that is not-editable and has a dispatchTransaction handler
2. Select text
3. Click directly on the selected text
4. The dispatchTransaction handler is not called

I assume the problem is that a certain event is not fired. 

~~One difference I can see is that Firefox doesn't have a "selectionchange" listener on the contenteditable, while Edge and Chrome do have it.~~

It does work when you click on a different (not-selected) part of the text.

One issue is that in Chrome, when you click on the selected text, and then do getSelection() in selectionchange, the anchorNode is null, while in Firefox it's correctly defined.

https://glitch.com/edit/#!/actually-agreement

### ProseMirror version
Latest (i.e. version on glitch)

### Affected platforms

- [x] Chrome
- [x] Edge
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Other

**Comment by Narretz** [comment]
The underlying behavior in Chrome is intended, see this ticket: https://bugs.chromium.org/p/chromium/issues/detail?id=893557#c5

So it seems like Chrome needs to be special cased.

**Comment by marijnh** [comment]
Right, the editor will only update its model of the selection when it sees a new selection inside of the editor, and since Chrome doesn't create a selection in this case, ProseMirror will stick to its old view of the selection. There's not a terrible lot I can do about that without creating a bunch of ugly workarounds, and I think the model of just following what the browser is doing is reasonable, so I don't think I'll try to fix this.

Maybe making whatever code this is causing to malfunction listen to focus changes would help?
