### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by jaysaurus** [ProseMirror/prosemirror#854]
### Issue details

correction in the guide at: https://prosemirror.net/docs/ref/#state.EditorState^fromJSON

### Steps to reproduce

the guide offers the following boilerplate for calling fromJSON:

`static fromJSON(config: Object, json: Object, pluginFields: ?⁠Object<Plugin>) `

when it should say:

`static fromJSON(config: Object, json: Object,) `

because, correctly, as you go on to say, we need to specify the plugins as an array in the configuration object:

    configuration options

    schema: Schema
        The schema to use.

    plugins: ?⁠[Plugin]
        The set of active plugins.

This had me confused for quite some time :)

**Comment by marijnh** [comment]
The call signature as it currently is is correct. That last argument is optional, but can be used to allow plugins to read their own state from the JSON data.

**Comment by marijnh** [comment]
None do, and none of the standard plugins even define a data serialization for their state. But you _could_, for a custom plugin whose state you want to serialize along with the rest of the editor state, define `fromJSON`/`toJSON` methods on its state field and then, if the plugin value was available in the variable `xyzPlugin`, say, pass an object like `{xyz: xyzPlugin}` to `toJSON` in order to get the plugin's state in the `xyz` property of the resulting JSON object.

**Comment by benjie** [comment]
I see 👍 Sounds like I don’t need to worry about it right now, thanks for answering 🙏
