### ISSUE TITLE
Pressing ENTER with the cursor at the beginning of a bullet item removes bullet

### ISSUE THREAD

**Issue by bjoernm** [ProseMirror/prosemirror#88]
# Actions performed
1. Create a new bullet list, e.g. one, two, three
2. Put cursor at the beginning of the first bullet item, in this example before the 'o' in one
3. Press ENTER

<img width="100" alt="bullet_1" src="https://cloud.githubusercontent.com/assets/1728765/11453730/69dbe186-9616-11e5-8c5f-33e034f3b961.png">

# Expected behaviour
A new bullet is created before the first item, in this case before 'one'. This is important if you want to add a new bullet item at the start in a bullet list. This is a widely used behaviour, e.g. in Google Docs.

<img width="113" alt="bullet_2" src="https://cloud.githubusercontent.com/assets/1728765/11453731/72b6e486-9616-11e5-8f2d-a1bccb6137d6.png">

# Actual behaviour
The bullet item of 'one' is removed and converted to a paragraph item.

<img width="110" alt="bullet_example" src="https://cloud.githubusercontent.com/assets/1728765/11453724/3f6023fe-9616-11e5-93aa-c5990b86132d.png">

**Comment by marijnh** [comment]
This is intentional, and it is behavior shared by most other WYSIWYG-style editors. You can override it if you want, but the default behavior isn't going to be changed.

**Comment by bjoernm** [comment]
I tested several WYSIWYG-style editors that share the behavior of adding a new bullet item before the first one, including:
- Google Docs
- Microsoft Word
- LibreOffice Writer
- Etherpad
- Quill JS

Which editors are you referring to?

**Comment by xiel** [comment]
Really confusing, also happens in the middle of a list. On an empty listitem line it would make more sense to remove the list-style.

TinyMCE e.g. also does it as Google Docs, Apple Pages etc.

**Comment by marijnh** [comment]
I see what you mean -- your list item isn't empty, in which case other tools indeed don't seem to lift the paragraph out of the list on enter. So yes, ProseMirror does differ from existing convention there. I'm still partial to ProseMirror's behavior, as it makes it easy to lift non-empty nodes out of their wrapping element, and preserves the symmetry with backspace.

What I don't want to do is adjust my behavior to conform to existing tools whenever someone complains that they didn't expect something, because I'm trying to create a more coherent model than the one found in existing tools, and piling exceptions on exceptions to please users will certainly end up getting us back to an incoherent mess.

**Comment by bjoernm** [comment]
It is a common use case to want to extend a bullet list by one item at the start. How would you go about doing that in the current model?

**Comment by marijnh** [comment]
Type first, press enter second, I guess

**Comment by xiel** [comment]
Can you describe what you mean by "preserves the symmetry with backspace"? Why should Enter and Backspace do exactly the same thing? Why isn't backspace an sufficient way to remove the list-style?

**Comment by marijnh** [comment]
Backspace doesn't do the same thing, it does, in some circumstances, the exact opposite thing. It'll move your current textblock closer to the block above it, so backspace won't, for example, allow you to go back to the top level when you're in a list item that isn't the first list item.

**Comment by bjoernm** [comment]
@marijnh typing first and then pressing enter works, but I think it is unintuitive and undiscoverable. I fully agree on not blindly accepting convention and trying to innovate and improve upon the existing. 

However, I think in most cases it is a more natural interaction to describe the formatting first and then define the content (or at least provide the flexibility to easily to do so). For example pressing enter first to create a new paragraph and then adding the content instead of typing everything together and then adding paragraphs.

**Comment by marijnh** [comment]
My head is full of other stuff right now. I'll come back to this when I have room to think about it.

**Comment by friksa** [comment]
+1 most users will find this confusing

**Comment by k1w1** [comment]
I want to add my 2 cents with regard to the overall philosophy of how the editor should in edge cases like this one. I think it is tempting when thinking about these cases and try to come up with what you think is the most logical, most useful or most powerful behavior. I think this is a mistake, and instead each edge case should be approached from the perspective of "what does Microsoft Word do in this case?" and do exactly the same thing as Microsoft Word.

The rationale for this approach is that a WYSIWYG editor for the web is most useful to help users reproduce experiences that they are familiar with in non-web applications. By far the most common editing experience that the average Internet user is going to have had is with Microsoft tools: Word, Outlook and Powerpoint. Users just naturally expect things to work a certain way in the editor, and each time the editor works a different way the user thinks to themselves: "something is broken". They don't think "oh, this editor must work in a better or different way, let me work it out".

Every behavior that is even slightly different from what users are familiar with is jarring. Whether or not Microsoft Word is the best experience, it is certainly the most common experience and with something as fundamental as text editing, just providing familiarity would make most users very happy.

There is another benefit of this approach: it removes some hard thinking. Trying to rationalize the best behavior in each case is hard work. Just following the existing model means there is a well tested baseline to compare against and the mental energy can go into the implementation.

**Comment by marijnh** [comment]
Well, I finally tied enough other ends to come back to this. Though I still very much resist the 'we must do as Word' line of thought, since once the cases get obscure enough, Word's behavior tends to get downright ridiculous, I do agree that there's value in adopting the more visible conventions from other tools. And this is definitely one of those more visible cases.

Attached patch changes the `"liftEmptyBlock"` command to only fire when the cursor is in an empty block. This makes some things more awkward (you have to know about the 'lift block' command more often since you can't just press home and enter anymore) and other things, such as adding a list item by entering at the start of another item, less awkward.

I'm not declaring this final yet, but let's see how well it works.
