### ISSUE TITLE
Backspacing out inline nodes on mobile sometimes breaks

### ISSUE THREAD

**Issue by marijnh** [ProseMirror/prosemirror#903]
From [this comment](https://github.com/ProseMirror/prosemirror/issues/543#issuecomment-477443537) in #543 via @fredguile:

@marijnh I'm also testing the composition branch and something noticeable happens with inline nodes:

- testing them on desktop works flawlessly:
http://recordit.co/x6kJ3f3fzO

- testing the same on Android Chrome show unexpected result:
http://recordit.co/o7JpstXMpe

As you can see the first time I hit backspace it works, second time actually most of the time it behaves like this) it doesn't delete the node and actually duplicates text after it. 

That's easily reproduceable, you can take my demo example from [here](https://github.com/fredguile/prosemirror-demo) and link it against `prosemirror-view` composition branch. 

Is there anything wrong in my code or could this come from the composition fix?

**Comment by marijnh** [comment]
This seems to also happen when typing directly after such a node. So far, it looks like the _browser_ is actually doing the duplicating, which might be really bad. But I'm still trying to figure out what's going on.

**Comment by marijnh** [comment]
No, that was a false accusation, it's definitely my code. So that's good—it means I should be able to fix it.

**Comment by marijnh** [comment]
On third thought, yes, it is a browser bug. Can be reproduced in this trivial HTML snippet without ProseMirror:

```html
<p contenteditable=true>
  Try typing after the uneditable word: <span contenteditable="false">abcd</span>
</p>
```

So I'm going to build an awkward kludge to try to detect and counteract it. I don't think this was introduced by the new composition code, though—there's nothing about it that depends on that.

**Comment by marijnh** [comment]
So not only does mobile chrome consider the uneditable word before the cursor part of the current composition, and does it then, when it finds it's not actually editable, _copy_ it into the focused textnode, but it aggressively restores that textnode to its nonsense form when a script tries to fix the damage.

I have code which more or less reliably detects this situation, but I have not yet found a way to actually hide the problem—as long as the composition is active, the browser keeps restoring the nonsense text. Maybe the most promising course of action is to try and get it fixed in Chrome (though given the glacial speed speed of response on such issues, that may not help much unless you have strings you can pull in the Chrome team).

**Comment by marijnh** [comment]
(A relatively easy workaround for this is to add a non-word character at the end of the node—a colon or a space or a zero width space. But that won't prevent other people from running into this. I'm going to give up on it for now—I'm happy to work around browser bugs when doable, but I'm stumped here.)

**Comment by fredguile** [comment]
Thanks for the explanation @marijnh! I realise that we have reported this bug already:
https://github.com/ProseMirror/prosemirror/issues/565

(and there's a chromium issue: https://bugs.chromium.org/p/chromium/issues/detail?id=612446)

I'd be happy with setting up a workaround for this using a zero-width character, however, haven't succeed to get satisfying results so far trying to patch the above example. If you get any input you could paste in this issue I'd appreciate!

**Comment by marijnh** [comment]
Ugh, okay, it seems that indeed zero-width spaces don't work. Real spaces mostly do, but visibilly change the look of the node.

One trick that does work is having _two_ wrapper elements on the node, the outer set to `display: inline-block` and the inner to `display: block`—that finally convinces Chrome that there's a block boundary between the text inside and outside the node, and composition won't cross that boundary.

Anyway, let's merge this into #565

**Comment by fredguile** [comment]
I tried this without success:

```
<div contenteditable="true">
      Try typing after the uneditable word:
      <div style="display: inline-block" contenteditable="false">
        <div style="display: block">word</div>
      </div>
   </div>
```

**Comment by marijnh** [comment]
What's going wrong? For me that snippet doesn't show the problem. There's still an issue with the cursor showing up in a weird place, but that's avoided by putting a `<br>` at the end of the editable element (which ProseMirror will do).

**Comment by fredguile** [comment]
Sorry should have given more details. I meant that when trying this in an Android WebView, we may run into another bug where the non contenteditable node can't be deleted anymore.

**Comment by marijnh** [comment]
Ah, okay, yes, that's another bug. But again a difficult one—as you probably know, Chrome Android doesn't fire useful key events for keys pressed on the virtual keyboard. Thus, we can't apply our own, reasonable backspace logic, but have to let the default behavior go through and then check whether it looks like the result of backspace. If a backspace press does nothing, ProseMirror has nothing go to on.

And indeed, it seems like backspacing out an uneditable block doesn't work on mobile. Have you opened an issue on the Chrome tracker yet?

**Comment by marijnh** [comment]
Ohh, hold on, it seems mobile Chrome _does_ fire a beforeinput event with `inputType == "deleteContentBackward"` when this happens. You can't `preventDefault` it, though the standard insists that you can, so it's not great, but we might be able to use that somehow.

**Comment by marijnh** [comment]
Ughhh. That `beforeinput` event is _only_ fired when the uneditable node does not have a `draggable="true"` attribute, otherwise the editor just mysteriously loses focus with no useful events at all. At this point I'm pretty sure some Chrome engineer is intentionally messing with us.

With patch 1a3faa9 (on master) I can now backspace out such nodes, but only when they are set to draggable: false.

Now I'm wondering whether the `draggable` attribute even does anything on mobile (I haven't found a way to drag nodes) and whether it would be safe to omit it there. Any ideas?

**Comment by fredguile** [comment]
Hi @marijnh, at last, I may have good news regarding inline nodes on Android. I've found a way to handle them based on all your aforementioned inputs (thanks for that!), plus working with our seasoned Android developers that found a way to forcefully send the missing keyup/keydown events.

I've made a video that is worth watching instead of a long explanation: 
https://www.dropbox.com/s/y4xy3oqayqfa453/about%20inline%20nodes.webm?dl=0

As you can see it's combining several of our aforementioned tricks:
- using inline divs for representing inline nodes,
- I also found that we would then have to render paragraph using DIVs (instead of Ps),
- and this works of course if we override the Android's InputConnection to forcefully send the missing key events. Without this, we'd end up with the previous symptom where BACKSPACE doesn't delete the inline node.

I'm discussing with the team if we could afford rendering our paragraphs using DIVs (I don't think that a big change).

The good thing is that this solution doesn't depend on `prosemirror-view` composition branch, so we could rollout a fix using the current `prosemirror-view` version. Asides, I think the composition branch is still be beneficial to us for solving different problems, mostly IME related. But now we can tackle these problems separately (and in another issue).

What are you thoughts about this solution?

**Comment by marijnh** [comment]
> I'm discussing with the team if we could afford rendering our paragraphs using DIVs (I don't think that's a huge change, might actually be doable).

Do you really need to do that? Doesn't an inline node (say a `<span>`) styled with `display: block` have the same effect? The problem, as I suppose you're aware, is that the HTML parser will close a `<p>` when it sees `<div>`. It would be nice if you can avoid using nonsemantic markup for your paragraphs.

The video had no sound for me—was the text in the editor its intended content? If so, I'd really prefer just getting the text, next time, without video!

**Comment by fredguile** [comment]
Yes sorry, I made the text as explanation. That's a recording done with Android Studio from a debugging smartphone, not sure how we add sounds.

**Comment by fredguile** [comment]
Hi @marijnh I've tested the variant using SPANs... while it sounds semantically more correct, it definitely breaks on Web & Mobile so I wouldn't recommend it. Closing this track. The wrapped DIVs show some decent results in comparison.

Then, setting `draggable: false` on inline nodes of my example and bumping to your [patch](https://github.com/ProseMirror/prosemirror-view/commit/1a3faa9a1147e504e832659155897ca08ef97553) on `prosemirror-view`, I can comment on this:

- we already have a [similar workaround](https://bitbucket.org/atlassian/atlaskit-mk-2/src/master/packages/editor/editor-core/src/plugins/composition/index.ts?fileviewer=file-view-default) for quite some time in our editor (using a forceful deletion on beforeInput), and honestly, I hoped to get rid of it fixing the root cause (which is the Android bug you described above), so now i'm a bit concerned it's merged into ProseMirror codebase. But I can also understand that you're looking to make it work without implying that Android developers would have to "hack" their Android [InputConnection](https://developer.android.com/reference/android/view/inputmethod/InputConnection) to send the proper key events for ProseMirror. 

- asides, testing this patch on my `prosemirror-demo` with a physical device (recommended!), it unfortunately **doesn't work**, because when I delete my inline node (the simplest one using a SPAN), the received "beforeInput" event owns `inputType==insertCompositionText`. This is what I noticed with testing deletions in this usual [website](https://danburzo.github.io/input-methods/index.html):
   - during composition (which is what I experience when deleting my inline node), you would have to handle `inputType==insertCompositionText` with some fancy data attached to it,
   - outside of composition you would have to handle `inputType==deleteContentBackward`
 
- so it's certainly worth exploring a fix for this but once more, IME makes it more tricky. In the meantime, on my side I'll keep exploring the wrapped DIVs with a custom Android InputConnection....

**Comment by marijnh** [comment]
> i'm a bit concerned it's merged into ProseMirror codebase

It's done in as non-invasive a way as possible—the code only fires when there's no DOM effect happening directly after the event.

> testing this patch on my prosemirror-demo with a physical device (recommended!)

I tested with a physical device, and for me it did work, but I guess when a composition has started before the backspace happened, it's fired as `insertCompositionText` instead. Those are really awful to interpret—the way the standard specifies them doesn't even really specify what they should look like when deleting text. But maybe we can still somehow narrow down the situation that we need to handle by looking both at selection position and the event.

**Comment by fredguile** [comment]
Okay, I'll let you know if the patch has a harmful effect on our editor but it "should" be okay (it may rather have no effect due to the fact we receive "beforeinput" events having `inputType==insertCompositionText`).

> Do you really need to do that? Doesn't an inline node (say a `<span>`) styled with `display: block` have the same effect? The problem, as I suppose you're aware, is that the HTML parser will close a `<p>` when it sees `<div>`. It would be nice if you can avoid using nonsemantic markup for your paragraphs.
> 

To keep you updated, I was indeed able to use your suggestion using SPANs into our Fabric editor. Look forward to fix this issue for good!

**Comment by dakhipp** [comment]
> Hi @marijnh, at last, I may have good news regarding inline nodes on Android. I've found a way to handle them based on all your aforementioned inputs (thanks for that!), plus working with our seasoned Android developers that found a way to forcefully send the missing keyup/keydown events.
> 
> I've made a video that is worth watching instead of a long explanation:
> https://www.dropbox.com/s/y4xy3oqayqfa453/about%20inline%20nodes.webm?dl=0
> 
> As you can see it's combining several of our aforementioned tricks:
> 
> * using inline divs for representing inline nodes,
> * I also found that we would then have to render paragraph using DIVs (instead of Ps),
> * and this works of course if we override the Android's InputConnection to forcefully send the missing key events. Without this, we'd end up with the previous symptom where BACKSPACE doesn't delete the inline node.
> 
> I'm discussing with the team if we could afford rendering our paragraphs using DIVs (I don't think that's a huge change, might actually be doable).
> 
> The good thing is that this solution doesn't depend on `prosemirror-view` composition branch, so we could rollout a fix using the current `prosemirror-view` version. Asides, I think the composition branch is still be beneficial to us for solving different problems, mostly IME related. But now we can tackle these problems separately (and in another issue).
> 
> What are you thoughts about this solution?
> 
> (as usual I've made the code used in the video [available here](https://github.com/fredguile/prosemirror-demo))

Thanks for the info! This would have been a rough one to figure out without your help. I thought I'd share this gist showing how we overrode the Android InputConnection on react-native in case anyone else runs into this issue trying to support RN. https://gist.github.com/dakhipp/72377353da53d9b106d705a0e8c64c81
