### ISSUE TITLE
Limit characters in output (getHTML)

### ISSUE THREAD

**Issue by upendra-web** [ProseMirror/prosemirror#908]
First of all, thanks for making such an awesome library.

I have a question. Can I limit the number of characters from the output of prosemirror editor like 250 characters from given in input in the editor? Thanks in advance.

**Comment by marijnh** [comment]
I don't really understand the question—do you want clip the HTML representation of the content to the first 250 characters of content, or do you want to limit the content so that its HTML representation can't be more than 250 characters? In the first case, I guess just clipping it and letting the HTML parser handle resulting mess is reasonable. In the second case, no such thing is built-in, but you could maybe write a plugin that computes the size of each node's HTML representation and filters transactions out if they would grow the editor's content beyond your maximum size.

Either way, the [forum](https://discuss.prosemirror.net/) is a better place to ask such questions. This is the bug tracker.
