### ISSUE TITLE
Lifecycle methods of custom node view called in wrong order.

### ISSUE THREAD

**Issue by rev-hikari** [ProseMirror/prosemirror#913]
### Issue details

`deselectNode` should call before `destroy`.

- Expected: `create -> select -> deselect -> destroy`
- Actually: `create -> select -> destroy -> deselect`

### Steps to reproduce

https://codesandbox.io/s/9or17v9nxy

1. Open the URL above
2. Click the divider to select it
3. Press `Backspace` key to delete it
4. Open browser's console

### ProseMirror version

1.8.8

### Affected platforms

I didn't test it in all the browsers but I believe this bug is browser-independent.

- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Other

**Comment by marijnh** [comment]
> deselectNode should call before destroy.

That may be a somewhat reasonable expectation, but it isn't specified anywhere that this is the right order, and the way ProseMirror display updates work (first the DOM is updated, which will destroy any node views that are no longer part of the document, then the selection is synced) makes it so that it'd be rather awkward to provide the order you expect.

The only thing I'm surprised by is that `deselect` is called at all on nodes that have already been destroyed. Would changing it so that that doesn't happen help you?

**Comment by jljorgenson18** [comment]
We've bumped into this before but it's fairly easy to workaround. If you are using a class and if your deselect function updates the dom, you can just set a "destroyed" flag on the class when the node is destroyed and return early in the deselect function if destroyed is true.

**Comment by rev-hikari** [comment]
@marijnh Check whether the node is destroyed before `deselectNode` may be a good solution for this issue.

**Comment by marijnh** [comment]
Done in attached patch!
