### ISSUE TITLE
dropcursor: body.offsetParent is null

### ISSUE THREAD

**Issue by kapouer** [ProseMirror/prosemirror#923]
Hi,

dropcursor (i am using 1.1.1):
https://github.com/ProseMirror/prosemirror-dropcursor/blob/ac70fd62c3ff3aca9660dfdfd9b7ac2511d2c51b/src/dropcursor.js#L62
but if the dom is document.body (using body as contentEditable here), offsetParent is null.

**Comment by marijnh** [comment]
It takes the parent because it needs to add an element _outside_ of the editor. If that's not possible because the whole document is an editor, I guess the approach taken by dropcursor just won't work (adding stuff to the editable content would result in it being included in the document, which isn't desirable).

**Comment by kapouer** [comment]
Indeed, i remember
https://github.com/ProseMirror/prosemirror-view/pull/33#issuecomment-425281091
I'm going to check which browsers support body siblings rendering.

**Comment by kapouer** [comment]
I tried https://mirage-moonstone.glitch.me/ on several os/browsers, see screenshots below (the yellow div must be covered by the black rectangle appended after the body):
Works everywhere tested here:
https://www.browserstack.com/screenshots/80e172924ff0d74b31b47e84e49283e8bdf3daba
Failures with IE <= 10:
https://www.browserstack.com/screenshots/d69252133439b48d9b5eef9427bf368c19b9ab14
I had to test live opera >= 11 and it works all right there.

**Comment by kapouer** [comment]
Closed when https://github.com/ProseMirror/prosemirror-dropcursor/pull/7 was closed.
