### ISSUE TITLE
[Question] Description of the third parameter in a command function

### ISSUE THREAD

**Issue by ocavue** [ProseMirror/prosemirror#940]
### Issue details

I'm reading the source code of prosemirror-commands and I noticed that `chainCommands` return a *command* function who accept three parameters: `state`, `dispatch` and `view`. However, the document misses the description of the third parameter `view`. Can anyone explain a little about `view`? I'm using this parameter but I doubt if I used it correctly.

Souce code:

https://github.com/ProseMirror/prosemirror-commands/blob/ac141b606cf776bbbaff352f2d06b4bbcb537d23/src/commands.js#L540

[document](https://prosemirror.net/docs/ref/#commands):

> A command function takes an editor state and *optionally* a `dispatch` function that it can use to dispatch a transaction.

### Steps to reproduce

N/A

### ProseMirror version

N/A

### Affected platforms

N/A

### Screenshots / Screencast (Optional)

N/A

**Comment by marijnh** [comment]
Commands may optionally take a `view` parameter if they need access to the `EditorView` instance (some of those defined in prosemirror-commands, like [`joinBackward`](http://prosemirror.net/docs/ref/#commands.joinBackward), have that parameter). Since `chainCommands` is supposed to work on all types of commands, it passes that third parameter through to its inner commands.
