### ISSUE TITLE
Removing one of a set of overlapping decorations affects cursor position in Chrome

### ISSUE THREAD

**Issue by jonathonherbert** [ProseMirror/prosemirror#942]
### Issue details

Removing one of a set of overlapping decorations sometimes affects the cursor position when the transaction is dispatched outside of the context of a browser event, e.g. setInterval, response to API call etc. This only seems to affect Chrome.

This only seems to be reproducible when the decorations are being mapped to new positions, either because text is added within their range or because inclusiveEnd is set.

### Steps to reproduce

This is the smallest reproduction I could create -- try to insert a character when the leading decoration is green. When the decoration is removed, the cursor sometimes pops back to the start of the red decoration. See the GIF at the end of this issue for example behaviour.

https://codesandbox.io/s/prosemirror-test-r1dze

The same thing doesn't seem to happen when the events are triggered by keypresses:

https://codesandbox.io/s/prosemirror-test-sgqyo

### ProseMirror version

prosemirror-model 1.7.1
prosemirror-state 1.2.3
prosemirror-transform 1.1.3
prosemirror-view 1.9.10

### Affected platforms

- [x] Chrome 74
- [ ] Firefox 67

### Screenshots / Screencast (Optional)

The user here is pressing 'a', 'b', 'c', 'd' in order here, and the cursor skips backwards.

![1](https://user-images.githubusercontent.com/7767575/59965549-9cd49d00-9507-11e9-930a-a1a4f1ef5f7d.gif)

**Comment by marijnh** [comment]
The first `.map` call in your `apply` method is a no-op, and doesn't seem to have an influence on the outcome.

When this happens, ProseMirror still believes the selection to be in the right place, and Chrome's DOM selection API _also_ claims that it is in the right place. But it does draw it in another place, and when you type, that's where text appears. I've seen Chrome bugs like this before, and they are really annoying, because it's hard for the script to react to it isn't even clear how to detect that something is going wrong anyway (as far as the script is concerned, the selection still looks like it's in the correct place).

**Comment by marijnh** [comment]
I've isolated the Chrome issue in a small HTML page:

```html
<!doctype html><meta charset=utf8>

<div contenteditable=true>a<span>b</span></div>

<script>
  let sel = document.getSelection()
  let div = document.querySelector("div")
  div.focus()
  sel.collapse(div, 2)

  // Wrap the 'a' at the start of 
  let sp = document.createElement("span")
  sp.appendChild(div.firstChild)
  div.insertBefore(sp, div.lastChild)
  console.log(sel.focusNode, sel.focusOffset)
</script>
```

After running this, the selection logged to the console will say that the selection node is the editable div and its offset is 2 (which, since it has two children, would be the end), while the visible cursor is between 'a' and 'b' (which would be offset 1).

I've submitted another [Chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=977991&can=2&q=dom%20selection%20wrong%20offset), but those aren't always acted on within a decade.

**Comment by jonathonherbert** [comment]
@marijnh thanks for the quick response, and the tiny repro! Re: the no-op mapping, thanks for pointing it out 👍 I guess there's nothing to action here, I'll have a think about workarounds.
