### ISSUE TITLE
ContentMatch.prototype.matchType compares nodeTypes using ==

### ISSUE THREAD

**Issue by kapouer** [ProseMirror/prosemirror#945]
Using prosemirror-model 1.7.1,
https://github.com/ProseMirror/prosemirror-model/blob/abaf3026e25327064b2681e16484bbe53aa48a2c/src/content.js#L31 can be problematic when one defines a clipboardParser using the same set of node types like this:
```
var spec = {
	nodes: opts.nodes,
	marks: opts.marks,
	topNode: opts.topNode
};
this.parser = Model.DOMParser.fromSchema(new Model.Schema(spec));
this.clipboardParser = Model.DOMParser.fromSchema(new Model.Schema(spec));
```
Since matchType compare the types of Nodes that have been parsed by either the parser or the clipboardParser, and since the schema constructor copies the nodeTypes, when matchType compares them it fails to find equality.
It should be doing `if (this.next[i].name == type.name)` instead.

**Comment by marijnh** [comment]
This is how ProseMirror works, though. You're expected to work with a _single_ schema, and node types from a different schema instance, even if structurally similar, are considered distinct and incompatible. Comparing by name is not a solution, since a its name says very little about the node type. Instead, just make sure you instantiate your schema once and use that when calling `DOMParser.fromSchema`.

**Comment by kapouer** [comment]
Good to now, but http://prosemirror.net/docs/ref/#view.EditorProps.clipboardParser is misleading then ?

**Comment by marijnh** [comment]
Why?

**Comment by kapouer** [comment]
Ha damn i misread you once again. I didn't catch the "same schema instance" thing.
