### ISSUE TITLE
Arrow movement in RTL text with marks creates stuck caret

### ISSUE THREAD

**Issue by johanneswilm** [ProseMirror/prosemirror#948]
### Issue details

When using marks with text in RTL and using arrow keys to move right/left, the caret is getting stuck some places. It doesn't matter if the dir=rtl is set on the paragraph. The issue happens whenever there are words in RTL characters that have different marks. The same markup in raw contenteditable does not show the same issues.

### Steps to reproduce

1. Go to https://glitch.com/~wistful-yacht

2. Click into the line of RTL text.

3. Move the caret left and right with the arrow keys.

### ProseMirror version

prosemirror-view 1.9.11

### Affected platforms

- [X] Chrome 75
- [X] Firefox 67

**Comment by marijnh** [comment]
This was another issue caused by the cursor wrapper kludge. I have a patch in [this branch](https://github.com/ProseMirror/prosemirror-view/tree/no-cursor-wrapper) that removes this kludge (its motivation is dubious since version 1.9.0 of prosemirror-view). I'd like to test this a bit more before I release it though, since it is somewhat invasive.

**Comment by marijnh** [comment]
I've released the patch as `prosemirror-view@19.14-prerelease` for easier testing.
