### ISSUE TITLE
Pasting Code from IntelliJ

### ISSUE THREAD

**Issue by darkfrog26** [ProseMirror/prosemirror#969]
### Issue details

I'm testing various rich editors (ProseMirror, Slant, and Quill) at the moment and the biggest negative of ProseMirror is the pasting results when pasting code.

### Steps to reproduce

Copying multi-line code from IntelliJ into the embedded code editor results in a single-line code block with multiple lines smashed into one.  In the Basics editor, it is completely unformatted as one line.  If I "Paste as Plain Text" it adds empty white lines between each line of code.

Quill looks correct when I paste the code either rich pasting with colors or as plain text.

Slate always seems to add the additional white lines whether I paste plain or rich.

I prefer the ideology and architecture of ProseMirror, but pasting code is an important feature to me.

### ProseMirror version

Whatever version is running on the site.

### Affected platforms

- [X] Chrome

**Comment by marijnh** [comment]
Are you pasting into a code block or a regular paragraph? What kind of HTML does IntelliJ copy onto the clipboard?

**Comment by darkfrog26** [comment]
The HTML when pasted into a raw contenteditable looks like this:
```
<pre style="background-color:#2b2b2b;color:#a9b7c6;font-family:'Inconsolata';font-size:13.5pt;"><span style="color:#cc7832;">def </span><span style="color:#ffc66d;">commit</span>()(<span style="color:#cc7832;">implicit </span>ec: ExecutionContext): Future[<span style="color:#cc7832;">Unit</span>] = {<br>  <span style="color:#cc7832;">val </span>g = <span style="color:#9876aa;font-style:italic;">graph</span>.getOrElse(<span style="color:#cc7832;">throw new </span>RuntimeException(<span style="color:#6a8759;">"Graph not included!"</span>))<br>  g.<span style="color:#9876aa;font-style:italic;">arangoDatabase</span>.transactionCommit(id).map { t =&gt;<br>    t.status <span style="color:#cc7832;">match </span>{<br>      <span style="color:#cc7832;">case </span>TransactionStatus.Running =&gt; <span style="color:#cc7832;">throw new </span>RuntimeException(<span style="color:#6a8759;">"Commit failed, transaction still running!"</span>)<br>      <span style="color:#cc7832;">case </span>TransactionStatus.Committed =&gt; ()<br>      <span style="color:#cc7832;">case </span>TransactionStatus.Aborted =&gt; <span style="color:#cc7832;">throw new </span>RuntimeException(<span style="color:#6a8759;">"Commit failed, transaction aborted!"</span>)<br>    }<br>  }<br>}</pre>
```

**Comment by darkfrog26** [comment]
This is the code sample:

```scala
  def commit()(implicit ec: ExecutionContext): Future[Unit] = {
    val g = graph.getOrElse(throw new RuntimeException("Graph not included!"))
    g.arangoDatabase.transactionCommit(id).map { t =>
      t.status match {
        case TransactionStatus.Running => throw new RuntimeException("Commit failed, transaction still running!")
        case TransactionStatus.Committed => ()
        case TransactionStatus.Aborted => throw new RuntimeException("Commit failed, transaction aborted!")
      }
    }
  }
```

**Comment by marijnh** [comment]
And are you pasting into a code block or a regular paragraph?

**Comment by darkfrog26** [comment]
Here: https://prosemirror.net/examples/basic/ I'm just pasting to the end of the editor in a new line.

**Comment by darkfrog26** [comment]
![Screenshot from 2019-09-03 07-37-07](https://user-images.githubusercontent.com/877534/64173794-a76fb480-ce1d-11e9-8be5-97b75eb8da47.png)

**Comment by darkfrog26** [comment]
If I select, "Type" -> "Code" and then paste, it doesn't look bad.

**Comment by marijnh** [comment]
Ah, the `<br>` nodes were being dropped because their parse rule (for hard_break nodes) doesn't apply in a code block (which only allows plain text). With attached patch, parsing such content (into an empty textblock node) produces better results, because the parser will try converting unplaceable `<br>` nodes to newlines. Does that help?

**Comment by darkfrog26** [comment]
Is there a convenient way for me to test it? I'm still getting up to speed with this library and honestly am not incredibly familiar with JavaScript library building (I come from Scala and Java primarily)

**Comment by marijnh** [comment]
You can try it on prosemirror.net, which is running the current version, or install prosemirror-model 1.7.2 locally if you have your own build.

**Comment by darkfrog26** [comment]
Much better, thank you!  I would very much like to use ProseMirror, but I'm finding it daunting to even try to set it up. Are there any good tutorials on getting it configured and set up for use within my web application?

**Comment by marijnh** [comment]
There's the [examples](http://prosemirror.net/examples/). Some experience with bundlers is definitely required to get started.

**Comment by abarsov** [comment]
It looks as if prosemirror-model 1.7.4 still have issues with pasting code fragment from Intellij IDEA.
I debugged that a bit and experienced strange behavior.

<br> is successfully parsed to dom node, but then it is converted to space inside
```
leafFallback(dom) {
    if (dom.nodeName == "BR" && this.top.type && this.top.type.inlineContent)
      this.addTextNode(dom.ownerDocument.createTextNode("\n"))
  }
```
By some reason, `top.options` is equal to 2 and `\n` got replaced with " " in the following if/else branch
```
      } else if (!(top.options & OPT_PRESERVE_WS_FULL)) {
        value = value.replace(/\r?\n|\r/g, " ")
      }
```

**Comment by marijnh** [comment]
Are you using the code_block node type from prosemirror-schema-basic? The `preserveWhiteSpace: "full"` in that one's parse rule should make sure that, when parsing its content, line breaks are preserved.

**Comment by abarsov** [comment]
It turns out we use `prosemirror-markdown/schema.js` for our WYSIWYG collaborative editor.
It slightly differs from the schema defined in `prosemirror\website\src\collab\schema.js` (which include `prosemirror-schema-basic` mentioned by you) .
Among other differences, `markdown/schema.js` declares `preserveWhitespace: true` for `code_block`.
I am a bit confused now what to do with those differences... Why two different schemas are defined in prosemirror codebase? (`prosemirror\website\src\collab\schema.js` and `prosemirror-markdown/schema.js`). What those differences matters? It looks as if `markdown/schema.js` supports a bit more parameters. Is it due to the fact that it was updated recently, but `schema-list/schema-list.js` and `schema-basic/schema-basic.js` were not or is it by design? Perhaps, some issues were fixed, but fixes were applied to one of schemas only?

_Differencies of basic nodes:_
|Node|collab(basic+list)|markdown|
|------|------------|-------------------|
| **blockquote**|  has attr `defining: true` | `defining` is not set|
| **horizontal_rule** | `toDOM() { return ["hr"] }` | `toDOM() { return ["div", ["hr"]] }` |
|**code_block**|`marks: ""`|`marks` is not defined|
|**code_block**|`attrs` is not defined|`attrs: {params: {default: ""}}`|
|**code_block**|`parseDOM: [{tag: "pre", preserveWhitespace: "full"}]`|`parseDOM: [{tag: "pre", preserveWhitespace: true, getAttrs: node => (
        {params: node.getAttribute("data-params") || ""}
      )}]`||
|**code_block**|`toDOM() { return ["pre", ["code", 0]] }`|`toDOM(node) { return ["pre", node.attrs.params ? {"data-params": node.attrs.params} : {}, ["code", 0]] }`|
|**text**|`toDOM(node)` is not defined|`toDOM(node) { return node.text }`|
|**image**|`toDOM(node) { let {src, alt, title} = node.attrs; return ["img", {src, alt, title}] }`|`toDOM(node) { return ["img", node.attrs] }`|

_Differencies of list nodes:_
|Node|collab(basic+list)|markdown|
|------|------------|-------------------|
|**ordered_list**/**bullet_list**|`attrs: {order: {default: 1}}`|`attrs: {order: {default: 1}, tight: {default: false}},`|

Thera are some differencies in marks as well...

**Comment by abarsov** [comment]
By the way, a good new is that there is no bug in prosemirror code regarding pasting code snippets.
It started working as expected after I updated imported `markdown/schema.js`
(changing `preserveWhitespace` from `true` to `full`).

**Comment by marijnh** [comment]
> Why two different schemas are defined in prosemirror codebase?

Because markdown covers a different content shape than what the default schema covers.

Some of these differences were accidental (the markdown schema wasn't updated when new features were introduced). I've fixed those in attached patch.
