### ISSUE TITLE
After deleting text in IE 11 the rest of the line is selected

### ISSUE THREAD

**Issue by TheRealNic** [ProseMirror/prosemirror#973]
### Issue details

When you select some text at the beginning of a line and remove it with backspace, the rest of the line gets selected after the deletion.

### Steps to reproduce

1. Go to http://prosemirror.net/ in IE 11
2. Select the word "Like" in the first line
3. Hit Delete or Backspace

### Affected platforms

- [ ] Chrome
- [ ] Firefox
- [x] Internet Explorer 11
- [ ] Other

### Screenshots / Screencast (Optional)

![image](https://user-images.githubusercontent.com/8322279/64847389-31363380-d60f-11e9-8209-1e86262552af.png)

**Comment by marijnh** [comment]
The reason I couldn't reproduce this before is that (at least for me) it only happens when I keyboard-select the word, as opposed to using the mouse.

After deleting like this, IE would _claim_ the DOM selection was at the start of the paragraph, as expected, but _show_ a different selection. I.e. the selection it presents to the user and the one it presents to the script differ. Attached patch forces a DOM selection reset after deletes to clear this situation, which seems to work.
