### ISSUE TITLE
Another IE typeover problem with decorated marks

### ISSUE THREAD

**Issue by cmlenz** [ProseMirror/prosemirror#977]
### Issue details

We have a mark with inline decoration. In IE11, when we select text with that mark and type, the mark is automatically ended when we enter a space character.

### Steps to reproduce

Clone https://github.com/mediatis/pm975-repro and do the build and open IE as described in the README. Then:

1. Select the word "placeholder" (it should be light blue). Don't include the space following the placeholder in the selection.
2. Type a character (or word)
3. Type a space
4. Type another character
5. Observe that the mark was automatically ended when the space was entered

### ProseMirror version

prosemirror-view 1.11.3

### Affected platforms

- [ ] Chrome
- [ ] Firefox
- [x] Internet Explorer
- [ ] Other

### Screenshots / Screencast (Optional)

![mark_ends](https://user-images.githubusercontent.com/11300/65580254-97a94300-df79-11e9-94e4-5ebef156cac3.gif)

**Comment by marijnh** [comment]
Thanks for the report. This one is going to have to wait until next month.

**Comment by marijnh** [comment]
[This patch](https://github.com/ProseMirror/prosemirror-view/commit/1da5801076d230919835f30923cb446b21338bbf) should help (though I only tested with a local reproduction of the issue, not with the precise code in your example). The issue was that, sometimes, when you press space before another space, IE will insert a non-breaking space _after_ that other space, which confused ProseMirror's DOM reading code.

**Comment by cmlenz** [comment]
Thanks @marijnh, this also fixes the problem in our example.
