### ISSUE TITLE
Ctrl+Shift+number not working on azerty keyboard

### ISSUE THREAD

**Issue by lcswillems** [ProseMirror/prosemirror#997]
### Issue details

The keyboard shortcut `ctrl+shift+1` doesn't work for azerty keyboard (all keyboard shortcuts `ctrl+shift+number`).

### Steps to reproduce

https://glitch.com/edit/#!/remix/prosemirror-demo-basic

Use an azerty keyboard and press `ctrl+shift+1`.

**Comment by marijnh** [comment]
Which browser are you using, and what are the `key` and `keyCode` properties of the keydown event that's being produced?

**Comment by lcswillems** [comment]
I am using Google Chrome 78.

This is the keydown event when I press `ctrl+shift+1`:

![image](https://user-images.githubusercontent.com/5437552/68929625-02624800-078d-11ea-8e4b-6f406559a8d3.png)

**Comment by marijnh** [comment]
Ah, is it correct that shift-1 actually produces a "1" character on your keyboard? And you are on macOS?

There was a Chrome Mac bug where ctrl-shift-1, on keyboards that _do_ create a different character when shift is held, would still set `event.key` to `"1"` for ctrl-shift-1. See #715. So the library assumes that when ctrl-shift is held _and_ the event has the `key` property expected for the shift-less version of that key, it should be overridden.

I don't have a macOS machine handy right now. Could you tell me what the `key` property of the event for ctrl-shift-x is? Is it a lower or an upper case 'x'? (Maybe the bug was fixed again in recent Chrome versions.)

**Comment by marijnh** [comment]
Huh, you're also on Linux, the diagnosis I produced before didn't apply at all.

Instead, this was related to another kludge, where people would want to bind 'Ctrl-Shift-z' as an equivalent to 'Ctrl-Z', and the keymap module tried both names, but used assumptions about a US keyboard to do so, which went wrong on yours. Attached patch tries to further complicate the kludge to at least address this case.
